### ISSUE TITLE
Two fixed options on shipping

### ISSUE THREAD

**Issue by npinelo** [wojodesign/simplecart-js#10]
Hi,

I need a simple cart with the option for US/worldwide fixed shipping cost, does this cart can do that? how to do this?

Best regards

**Comment by wojodesign** [comment]
Presently, you would need to change the shipping fields via javascript based on the users location.  Thanks for the idea, I will try and work it in to the next update.

**Comment by j-greig** [comment]
I'm attempting the same using a shipping dropdown, and have got the shipping rate being updated, but can't work out how to update the total price? (It's only correctly updated when you add another item to the cart)

```
<SELECT name="number" onchange="simpleCart.shippingFlatRate = this.options[selectedIndex].value; simpleCart.updateTotals">
```

Lovely shopping cart though, thank you! :)

**Comment by j-greig** [comment]
My bad(s)... you need to call update(); .... and I was missing the brackets :)

```
<SELECT name="number" onchange="simpleCart.shippingFlatRate = this.options[selectedIndex].value; simpleCart.update();">
<OPTION selected value="blank">Choose shipping type</OPTION>
<OPTION value="0">Normal (Free)</OPTION>
<OPTION value="5">Express UK (+£5)</OPTION>
<OPTION value="10">Express World (+£10)</OPTION>
</SELECT>
```

**Comment by grahamx** [comment]
code:
<input type="radio" onchange="simpleCart.shippingFlatRate = this.value;simpleCart.update();" name="shipping" value="5" /> &pound; 5<br />
    <input type="radio" onchange="simpleCart.shippingFlatRate = this.value; simpleCart.update();" name="shipping" value="10" /> &pound; 10

will work if you want radios instead of the drop down options

**Comment by robocutstudio** [comment]
I tried this code and it seems that the cart is being updated (simpleCart_finalTotal) but the amount is not passed through when checking out to paypal..
anybody else got that or konws how I could make it work ?
thanks
