### ISSUE TITLE
Why is only letting put a maximum of 13 items?

### ISSUE THREAD

**Issue by ragtech** [wojodesign/simplecart-js#102]
See my example (I've removed all other .js and other instruments on the page) just have simplecart.js and some css...

http://friendlyfumes.com/new/product_detail/spa_test.html

I'll change the fragrance name and it correctly enters another item up to 13 (it will go higher but when you refresh the page or got to the cart... only 12 or 13 show up...)  what gives?

Please I really need to know... I've configured my entire site with simplecart and just now am noticing this limit...
HELP!

**Comment by ragtech** [comment]
It's the Cookie limits that are restricting the cart sizes...

This may be something you want to mention in your documentation on limitations; too bad it was a terrific script but it now seems I will have to look at another solution...

**Comment by drivebass** [comment]
Does this issue still apply? I have tested the script and it works even for 100 items.
