### ISSUE TITLE
Send to 2nd email address (PP checkout)

### ISSUE THREAD

**Issue by chintz** [wojodesign/simplecart-js#103]
I have a PayPal checkout implemented, client now needs the notification containing all options sent to another email address in addition to the Paypal address. Is this possible at all?

The purchase combines two choices and has a couple of text fields to pick up, if that has any bearing on it at all.

Thanks in advance...

**Comment by wojodesign** [comment]
You can try to create a custom script by modifying the email branch to send your data.
