### ISSUE TITLE
...Contributing (Checkbox to add state sales taxes)

### ISSUE THREAD

**Issue by ragtech** [wojodesign/simplecart-js#104]
Simply Check the box and it add a specific States Sales Tax; by the same token... if you Remove the Check it removes the Sales Tax...

I Posted an Example Here...

http://uswebsitecreation.com/tax_example/tax_example.html

Someone with more js skills may want to check my coding... my js is very limited. But I have tested it on most browsers and it seems to work on all of them.

Regards,
ragtech

**Comment by ragtech** [comment]
Forgot to mention... it uses ''jquery.cookie.js'' to set a cookie so it will remember whether the Checkbox was 'CHECKED' or 'UNCHECKED' apply the sales taxes according on each page... just make sure to add the additional javascript to any page where you want the taxes.

Regards,
ragtech

**Comment by joeNmass** [comment]
Just what I have been looking for. Thank you!
There is just one issue I don't know how to correct it (on your example it works fine but on my page it does not).
The tax shows up correctly in the cart when the tick box is checked but when it goes to PayPal for payment the taxes are not calculated in the price for PayPal.
What I am I doing wrong?

**Comment by joeNmass** [comment]
I figured it out!
I forgot to add the "simpleCart.js" file into my "js" folder.

Thanks again for sharing this code.
