### ISSUE TITLE
Changing text generated at PayPal checkout for each item

### ISSUE THREAD

**Issue by nickharambee** [wojodesign/simplecart-js#105]
Hi,

Thanks for a great simple script.  I have successfully linked up simpleCart to my PayPal account, but am wondering how to customise the text for each item shown at PayPal checkout.  At the moment each item looks something like this:

undefined
Item number: 1
Item price: £17.00
Options: Options: 
Quantity: 2

When I would like it to look like this:

[Name of item]
Item price: £17.00
Quantity: 2

Is there any way of removing the Options and the Item Number and changing 'undefined' to the name of the Item that is being purchased?

Thanks

Nick

**Comment by wojodesign** [comment]
The Options issue is an open bug, I should have that fixed soon.  It looks like you aren't giving your item a name, so it is showing up as undefined.  The item number is required by paypal, I believe.  I will look into that.

**Comment by nickharambee** [comment]
Thanks. I have the item name sorted now (I didn't close the class).  I'll look out for the options issue bug being fixed
