### ISSUE TITLE
Specifying URL for redirect on successful PayPal payment

### ISSUE THREAD

**Issue by nickharambee** [wojodesign/simplecart-js#106]
Hi,

Prior to installing simpleCart I was using PayPal buttons for handling payments through PayPal, and there is a facility with these buttons where you can specify a URL for redirecting the user back to a specific page on your website after a payment has been made successfully.  Is it possible to do so with simpleCart?

Thanks,

Nick

**Comment by wojodesign** [comment]
v2.2.dev now has this option.  you can set the success and failure urls with simpleCart.successUrl and simpleCart.cancelUrl, respectively.
