### ISSUE TITLE
Error when removing item from cart

### ISSUE THREAD

**Issue by ricpersi** [wojodesign/simplecart-js#107]
hi there, if I add an item from the shelf to the cart and then remove it everything seems fine until you reload the page. After reloading you get the cart filled with a product that has no name, no thumb, no description, price set to 0 and quantity set to 1. Maybe it has to do with the new cookies code?

Steps to reproduce:
1) go to http://demo.simplecartjs.com/ 
2) add an item (such as "Sample DVD") from the shelf
3) scroll to the cart and either decrease quantity until you remove the item or empty cart
4) reload the page, scroll to the cart and you get the "ghost" item

Regards,

  Riccardo

**Comment by ricpersi** [comment]
the following modification solves the problem for me. cheers

https://github.com/ricpersi/simplecart-js/commit/0e75644c7b50a5802cc2555368dd6cfb1e5ef71e

**Comment by wojodesign** [comment]
Thanks ricpersi! I have merged your update into the master branch and I am updating the tests and compressed version now

**Comment by ricpersi** [comment]
You're welcome thewojogroup. Actually I have to thank you for simplecart-js, it's such a great tool!

**Comment by wojodesign** [comment]
of course! we appreciate the feedback and contributions, let us know if there is anything else we can do
