### ISSUE TITLE
Looking for an exsisting variable that I can use...

### ISSUE THREAD

**Issue by ragtech** [wojodesign/simplecart-js#109]
Looking for an existing variable that I can use to place a message like "Your Cart Seems to be Empty" in the My Cart/Check out page...

Simply put; when/if the visitor clicks on the "My Cart" page and there are no items yet; they get the above message... seems simple but I'm having difficulties... Please help...

Can anyone help me out?

regards
~ragtech

**Comment by wojodesign** [comment]
you can simply check simpleCart.quantity === 0 and output that message if its true

**Comment by ragtech** [comment]
Excuse my ignorance when it come to js... but what am I doing wrong?

<xmp>
if(simpleCart.quantity === 0)   {
        document.getElementById('cart_is_empty_banner').innerHTML = '<img src="../images/cart_empty.jpg"  alt="Cart is Empty Banner" />';
    }
    else {
        document.getElementById('cart_is_empty_banner').innerHTML = '';
    }
</xmp>

**Comment by ragtech** [comment]
If I do a document.write(simpleCart.quantity);

it always shows a value of 0

is this correct?

**Comment by brettwejrowski** [comment]
hey ragtech, the quantity will be 0 until simpleCart initializes.  You can output the quantity like so:

``` html
<span class="simpleCart_quantity"></span> 
```

simpleCart(js) will automatically update that with the quantity.  If you need to check the quantity, in some code, you can add a function call at the end of the initialize function.
