### ISSUE TITLE
Up/Down Arrows Next to Quantity

### ISSUE THREAD

**Issue by zooshme** [wojodesign/simplecart-js#11]
Hi,

I'm trying to figure out how you've created the up/down arrows next to quantity in the shopping cart in the demo. I would like to add similar graphics on my own website to replace plus/minus but I don't know how to do it. Could you please help me? Thank you very much for such a great product.

Ovi

**Comment by wojodesign** [comment]
You can use css to change the background image for the classes of the buttons.  Let me know if you need help and I can point you to where our designer did this in our demo
