### ISSUE TITLE
little shopping bag module - "Your cart is empty"

### ISSUE THREAD

**Issue by westsomething** [wojodesign/simplecart-js#110]
How to write a simple script which will checked the quantity of ordered products in cookie and makes the text message - "Your cart is empty" or "You have 2 items in your cart" - like in every standard shopping bag module on the side of the web site - where is the main cart not present?

**Comment by iamstevemckinney** [comment]
While handling empty carts with custom text isn't currently supported, you could do something like this

```
you have <span class="simpleCart_quantity"></span> items in your cart
```

If the cart is empty it'll look like this

```
you have 0 items in your cart
```

**Comment by westsomething** [comment]
I think it will work. Thanks.
