### ISSUE TITLE
All the wiki links are returning 404

### ISSUE THREAD

**Issue by bledek** [wojodesign/simplecart-js#111]
This may be more of a Github problem, or none of the articles are written yet... 

Which one is it? :)

Thanks!
- Brian

**Comment by brettwejrowski** [comment]
Hey thanks @bledek for letting us know. We recently changed our account name from 'thewojogroup' to 'wojodesign' and that probably caused the issues. I will clean that up this weekend. 

Thanks again,  

Brett

**Comment by funky-monkey** [comment]
Hi Brett, 

The links still dont work. Although the do work if you go directly to the Pages section under Wiki.

Cheers, 
Sidney

**Comment by brettwejrowski** [comment]
They should be updated now
