### ISSUE TITLE
thumbnail in the cart

### ISSUE THREAD

**Issue by robocutstudio** [wojodesign/simplecart-js#112]
Hi!
 I was wondering how can you resize the thumbnail of a product to be displayed smaller in the cart ? I've tried to see how Wojo did in the demo but I'm pretty new to firebug ;)

I see where it is initialized in the header
    simpleCart.cartHeaders = ["Thumb_image_noHeader", "Name" , "Size_input_div_div", "Price" , "decrement_noHeader" , "Quantity", "increment_noHeader", "remove_noHeader", "Total" ];
but I'm not sure how to edit this class.. is it modified on the fly with a GD script or something like that or is it another image that is loaded somewhere  ?

any ideas ?
thanks in advance!
Phil

**Comment by robocutstudio** [comment]
ok I hardcoded the answer to my question ;) 
this is how I've done it:

```
<li class="simpleCart_shelfItem">
  <a href="<?=$url?>products/boulon1.php"><img src="<?=$url?>/img/products/boulon1/boulon1_shop.jpg" width="200" height="250"/></a>
  <img src="img/products/boulon1/boulon1_thumbCart.jpg" width="100" height="125" class="item_thumb" style="display:none; visibility:hidden" />
```

works fine in all browsers..
suggestions still welcome

Phil

**Comment by brettwejrowski** [comment]
You could always handle the resize with CSS

**Comment by valeria-io** [comment]
HI, I really  don't know where to resize the thumbnail? Where should I include that???
