### ISSUE TITLE
Script not sending the shipping cost to paypal site 

### ISSUE THREAD

**Issue by irphan** [wojodesign/simplecart-js#113]
Hi, I am using  simplecart-js  this is great script but I have some problem with this .when i am adding items to cart it working perfectly and calculating shiping  and tax etc but when i checkout the only item's actual cost is send to paypal by script  and not shipping cost.like i have item cost=$50 and shipping cost =$10 and total is $50+$10= $60. It should  send $60  to paypal but the script is sending only $50 instead of $60. can anyone help me ? help w'll be greatly appreciated. Thanks

**Comment by limjunk2015** [comment]
Same here... even using the sample index.html file spends total item cost and tax to PayPal but not shipping costs!

**Comment by brettwejrowski** [comment]
It should be sending the shipping as a single total sent to paypal in the shipping_ field.  Let me do a couple tests and see if I can't track down the issue.

**Comment by limjunk2015** [comment]
Thanks Brett, I appreciate you looking into the issue. Using the example right out of the box here's is what is being sent to PayPal:

https://www.paypal.com/cgi-bin/webscr?cmd=_cart&upload=1&business=brett@wojodesign.com&currency_code=USD&tax_cart=$15.04&item_name_1=Zebra&item_number_1=1&quantity_1=1&amount_1=$187.95&on0_1=Options&os0_1=thumb=http://<removed>.co.uk/test/e.png, size=Small&shipping=$25.25

As you can see it IS sending a shipping value but it isn`t appearing in the PayPal 'cart' so it may be related to a PayPal change I guess.

**Comment by limjunk2015** [comment]
I can get this to work if I append handling_cart to the formed URL:

https://www.paypal.com/cgi-bin/webscr?cmd=_cart&upload=1&business=brett@wojodesign.com&currency_code=USD&tax_cart=$2.80&item_name_1=baby lion&item_number_1=1&quantity_1=1&amount_1=$34.95&on0_1=Options&os0_1=size=tiny, thumb=e.png&shipping=$5.25&handling_cart=$5.25

I am new to this (PayPal shopping carts) so I am not sure if that's a valid fix though?

**Comment by brettwejrowski** [comment]
From you example, it looks like the "shipping" variable is not being sent but the handling is.  I checked the paypal site to make sure the variable is correct, so I think it may be an option within a PayPal account.  I haven't found anything about it yet, but I'll continue to dig. 

In the meantime, you can change the "shipping" value to "handling_cart" in the paypal checkout function if that is working.

**Comment by mayersdesign** [comment]
I am seeing a similar problem. I had the script working locally a few days ago, but now it refuses to pass the shipping to paypal, would love to hear what your investigations turn up Brett. I'm afraid if I trawl through my paypal profile options any more today my eyes will fall out!

**Comment by mayersdesign** [comment]
If it helps, I am sending the following to a UK paypal account:

amount_1    10.00
business    x@x.com
cmd _cart
currency_code   GBP
item_name_1 Test Product DO NOT BUY
item_number_1   1
on0_1   Options
os0_1   size=10, colour=test/, reference=test
quantity_1  1
shipping    5.95
upload  1

via: 

https://www.paypal.com/cgi-bin/webscr?cmd=_cart&upload=1&business=x@x.com&currency_code=GBP&item_name_1=Test%20Product%20DO%20NOT%20BUY&item_number_1=1&quantity_1=1&amount_1=10.00&on0_1=Options&os0_1=size=10,%20colour=test/,%20reference=test&shipping=5.95

I too can get "Postage and packing" to show up by switching to "handling_cart" - did something happen PayPal's end?

**Comment by brettwejrowski** [comment]
I have scoured documentation and examples, and everything says you need to allow "order specific shipping" to override any settings, and then the "shipping" variable should show up correctly.  However, this doesn't seem to do the trick for me.  

I also noticed that paypal's html variable documentation says that "handling" is the correct variable, even though it should be "handling_cart"....

I will keep looking around... this is the curse of working with PayPal - the worst documenters ever.

**Comment by mayersdesign** [comment]
Hi Brett,

Thanks for taking the time to look into it.

I hear you with Paypal. Their website is like something from a Kafka novel! Especially the UK documentation that frequently leads nowhere (literally 404) or else does that "redirecting" thing.. Nooooooooo! haha

Just to confirm I definitely did try that terribly labelled box "allow override" without success, but this DID work two weeks ago when I tried the system before going live!

I can also confirm that using "handling_cart" has solved my problems when I substitute it for "shipping" where the url is constructed, on line 283:

//itemsString = itemsString +   "&shipping=" + me.currencyStringForPaypalCheckout( me.shippingCost );
itemsString = itemsString   +   "&handling_cart=" + me.currencyStringForPaypalCheckout( me.shippingCost );

Of course if Paypal changed that variable they must have known they would bust a thousand scripts, but hey...it's paypal. Look on the Brightside, they aren't SagePay hahaha

PS, I just sent you a drink on PayPal, as should all users of the script, especially when you take the time to respond to users directly....

**Comment by brettwejrowski** [comment]
there is also a variable called "no_shipping" which is set to 2 by default (asks for address info to calculate) and should be set to 1 (do not ask for shipping info) in order to allow custom shipping values to be set.  Unfortunately, this did not work for me either, but it might be help someone.

**Comment by brettwejrowski** [comment]
Well I've had no luck in figuring out the 'shipping' variable, but I did look through the source of Ubercart for Drupal, which has support for PayPal Standard, and they use the 'handling_cart' variable for the shipping cost as well.  So it looks like I will be updating simpleCart(js) to use that as a standard.

**Comment by mayersdesign** [comment]
That seems like the best way forward Brett. We are using you're the script here: http://www.newforestfootwear.com with a slight adjustment for choosing the flat rate shipping. We went with "handling_cart" and are doing fine - and this site is pretty high traffic.

**Comment by brettwejrowski** [comment]
Changed the 'shipping' paypal variable to 'handling_cart' in 2.2.1 in the master branch and in 2.3.dev.  

Thanks for all your help guys!

**Comment by antonyf** [comment]
Hi, I tried all the fixes for this shipping problem. The 2.3 dev sends the shipping, but not the tax. V3 a little too much to adapt my site to now. Can you give me the quick fix to send shipping and tax and total to Paypal for version 2.2.
regards
Antony

**Comment by antonyf** [comment]
Never mind: this works perfectly.. thanks mayersdesign
I can also confirm that using "handling_cart" has solved my problems when I substitute it for "shipping" where the url is constructed, on line 283:

//itemsString = itemsString + "&shipping=" + me.currencyStringForPaypalCheckout( me.shippingCost );
itemsString = itemsString + "&handling_cart=" + me.currencyStringForPaypalCheckout( me.shippingCost );
