### ISSUE TITLE
Checkout in Modal, passing variables to rest of serialized array

### ISSUE THREAD

**Issue by Braunson** [wojodesign/simplecart-js#114]
Hello,

I have a modal pop up when the customer presses "checkout" and they have to fill in their contact details and what I have working is that the modal form on submit emails me with the filled information using the code (at the link below), however I can't figure out how to include in the same data array the shopping cart information (which I can expand on via PHP and make it look nice in their the email I receive).

Any ideas, I'm trying to get this dang thing finished asap? All and any help is appreciated!

http://jsfiddle.net/uDS7A/

**Comment by Braunson** [comment]
Anyone have any ideas?

**Comment by brettwejrowski** [comment]
I would modify the checkout function to add the extra info you are collecting from the form.  If you save the details to an object literal in simpleCart like "simpleCart._extra_info = { name: "Bob" };" you can pass these as extra parameters when you checkout.  

Where are you checking out to now (paypal, google, custom..) ?
