### ISSUE TITLE
jquery mobile not showing 

### ISSUE THREAD

**Issue by eplixo** [wojodesign/simplecart-js#115]
I was wondering if anyone has experienced this working okay in Dreamweaver 5.5 multiscreen and live view but not working when uploaded to remote server. I am using jquery mobile 

All the functionality works fine on the local machine just getting a blank screen when on remote....

**Comment by brettwejrowski** [comment]
What device are you testing on? Have you tested in an emulator?

I will add test cases for jquery mobile in the next version to help avoid these issues in the future, but it will help to have more details about where you are running into the errors

**Comment by eplixo** [comment]
Hi Brett

I have not had a chance to test it on any device up to this point other than online and also using the Ripple Emulator which is a Chrome emulator that works across Phonegap and other such frameworks.

AIt works fine when I am building the app in Dreamweaver 5.5 and Live View but is a blank screen when I try it online or in the Ripple Emulator.

I also tried to place it before and after the js in jquery-mobile but this had no effect. I am continuing to work with it while building the app it is just that at some point (fairly soon) I am going to have to find a solution. It is a nice piece of code, just that for the moment it is causing me a slight headache :)

Gerry@eplixo

**Comment by brettwejrowski** [comment]
Do you have an example of the code on a dev server I can look at?

**Comment by eplixo** [comment]
Brett you can check out the basic item on http://d.eplixo.com/gf4us/index.html it is a prototype without any database web services. Just right click to view the source and you can see the code

**Comment by brettwejrowski** [comment]
eplixo, where is the cart supposed to be loaded up? I can't find the html or js for it

**Comment by eplixo** [comment]
Brett can you give me an email address and I can send over more information

Gerry

**Comment by brettwejrowski** [comment]
sure its just brett@wojodesign.com
