### ISSUE TITLE
Limit Cart Quantity

### ISSUE THREAD

**Issue by vegaix9** [wojodesign/simplecart-js#116]
From reading through various issues and failed attempts of my own, I am submitting this request for help.

I am trying to limit the quantity of the cart to 10 items. That means any attempt to add items to the cart beyond 10 disables all "add to cart" buttons and increments on items in the cart. I have succeeded in removing the increment on all items within the cart, but the "add to cart" buttons continue to increase the quantity of the cart.

I do have an alert that prevents a checkout for a cart quantity over 10, but I'd much prefer the alert to appear as soon as the cart quantity attempts to reach 11.

Any suggestions?

Thanks

**Comment by brettwejrowski** [comment]
I would add some code at the end of the add to cart function that checks the item quantity and sets it to 10 if it is above that.  You will also want to modify the increment function on the cart item model to do the same

**Comment by vegaix9** [comment]
Thanks for the pointer. I was able to limit the quantity to 10 by using the code below, however I cannot get the alert to function upon the attempted addition of an 11th item. What do you suggest? Code is below.

```
if( me.hasItem(newItem) ) {
        var foundItem=me.hasItem(newItem);
        if(parseInt(simpleCart.quantity) <= 9) {
            foundItem.quantity= parseInt(foundItem.quantity,10) + parseInt(newItem.quantity,10);
            newItem = foundItem;
        } else if (parseInt(simpleCart.quantity) > 10) {
            alert("The maximum number of items per order is 10. Please remove some items and try again.");
        }
    } else {
        me.items[newItem.id] = newItem;
    }
```

**Comment by brettwejrowski** [comment]
Hi vegalx9,  you just need to change the else if inequality to a greater than or equal to.  When the cart has a quantity of 10 in that code, it doesn't match either test.  ( 10 <= 9 === false , 10 > 10 === false ).  In fact, I would just removed the second test for whether it is larger that 10, it is a redundant check.

**Comment by vegaix9** [comment]
Thanks, that is a simple fix. No sense in complicating things.

**Comment by FletcherPink** [comment]
Hello,
I try to set the "item_add" link to "display none" (css) when the limit is over. I follow this tips and the alert is working. I thought i just have to use getelementbyclass but it didn't works.
Can you show me the way ? 
Thanks a lot.

**Comment by perlingon** [comment]
This way worked fine for me, just hook it into the beforeAdd event and use the .quantity

<pre><code>simpleCart.bind( 'beforeAdd' , function( item ){
            if(simpleCart.quantity() === 10 ){
                alert("The maximum number of items per order is 10. Please remove some items and try again.");
                return false;
            }
    });
</code></pre>
