### ISSUE TITLE
Is there a way of getting text for item names to show up only on PayPal page?

### ISSUE THREAD

**Issue by nickharambee** [wojodesign/simplecart-js#120]
Hi,

I am trying to find a way of having some text show up on only the PayPal payment page.  So I am either looking for a way of hiding some of the text in the span class for item name on my webpage, but having it show up in PayPal, or a way of adding an overall title for all items which would only show up, on the PayPal page, perhaps above the items.

Are either of these possible?

Thanks,

Nick

**Comment by brettwejrowski** [comment]
I would set up a Shelf Item with the text you want in a custom field, which you can hide with CSS or put in a hidden form input.  Then as long as you don't show it in the cart, it will only show up once the user gets to PayPal

**Comment by nickharambee** [comment]
Thanks.  I am not sure what you mean by "set up a Shelf Item with the text you want in a custom field".  I have tried adding a span (surrounding the text that I want hidden within the item_name span) with a class that I hide with CSS, but then it is hidden at PayPal checkout as well, so this can't be what you mean.  I'd be grateful for some more clarification.
