### ISSUE TITLE
Simple Cart pre-sales questions

### ISSUE THREAD

**Issue by ryankent** [wojodesign/simplecart-js#121]
Hello.

I am looking for a simple cart for a site that I am migrating to Joomla. RokQuickCart is a bridge which uses SimpleCart. I am hoping someone can answer a few questions which can help me determine if SimpleCart will work for me.
1. Will SimpleCart retain a customer's information so when they log in on future visits they do not need to re-enter their address and credit cart info?
2. Will SimpleCart integrate with my site's current login so users do not have to log in twice?
3. Does SimpleCart offer customers the ability to review their order history?
4. With SimpleCart am I able to retain control over the page's URL, page title and meta description? 

I appreciate any responses. Thank you for your time.

**Comment by brettwejrowski** [comment]
Hi Ryan,

simpleCart(js) is a javascript only, simple front end shopping cart.  All of your questions would most likely pertain to RokQuickCart or another system, as they all deal with server-side issues.  

I encourage you to look into RokQuickCart further for integrating simpleCart(js) with your Joomla site. 

Thanks,

Brett
