### ISSUE TITLE
Out of the Box.

### ISSUE THREAD

**Issue by webiter** [wojodesign/simplecart-js#122]
I am not a Cart or a Box expert. Not sure if this is an 'Issue' or a 'Start Up' teething problem! 
I am looking for a simple cart that I could offer to SME's locally that would let them get a feel for eCommerce and increase their sales.  
Just unpacked simpleCart(js) and proceeded to get a simple trial up and running. I done this by opening a file and placed the unzipped cart components into it. I then opened my editor and created a basic html document with a head and body section. I then installed the following between the head tags:

<TITLE>(JS) CART TRIAL</TITLE>

<script type="text/javascript" src="simpleCart.js"></script>

```
<script type="text/javascript">
    simpleCart.email = " ";
    simpleCart.checkoutTo = PayPal;
    simpleCart.cartHeaders = [ "name", "thumb_image" , "Quantity_input" ,  "increment",  "decrement", "Total" ];        
</script>
```

and between the body tags I copied and pasted source code from the simpleCart(js) main demo page. This comprised the 6 demo products and the cart component in the demoContainer. I then saved and opened the file in Firefox.
I then see along with the other text the Add to Cart, Empty Cart and Check Out buttons presented in blue. I then click on the Add to Cart buttons hoping to see the the shopping total accumulate somewhere on the page as the "cartTotal"  and "simpleCart_total" components are installed in the cart. Nothing happens..... what do I need to do to get it working?

**Comment by brettwejrowski** [comment]
Did you include the simpleCart.js or simpleCart.min.js files?

**Comment by webiter** [comment]
Sorry, I had included them but had the paths incorrect. 
Getting somewhere now!
Thanks again.

**Comment by brettwejrowski** [comment]
No problem, thanks for using simpleCart(js)!
