### ISSUE TITLE
passing on shipping information to paypal

### ISSUE THREAD

**Issue by ky0ung** [wojodesign/simplecart-js#125]
Hey this is a great script! Its very easy to use and beautifully made. I feel that a great addition would be to pass on shipping information to paypal, but how would I do this? Could you refer me to a certain line number in the javascript file that deals with paypal?

Thanks,

Kyle

**Comment by iamstevemckinney** [comment]
Please see the configuration settings area of the docs. 
http://simplecartjs.com/documentation.html
