### ISSUE TITLE
Shipping based on weight and volume?!

### ISSUE THREAD

**Issue by ghost** [wojodesign/simplecart-js#126]
I put a weight, girth, length, and width with each item.  

<span class="item_weight" id="ItemWeight" style="display:none;" value="1.23"></span>

Then a couple of different items are added to the cart.  How can the sum of the weights, sum of the girths, max. length and max. width be found out of all the items in the cart?

Something like this?  
var w = max(cart.quantity.width)
var x = max(cart.quantity.length)
var y = sum(cart.quantity.weight)
var z = sum(cart.quantity.girth)
I know that's not right, but I have been trying to figure this out for hours and have gotten nowhere.  If no one knows to do this, I would really love to know how to send the 4 pieces of data to Paypal so maybe I can calculate weight and volume there?  Thank you!

**Comment by brettwejrowski** [comment]
you can use the simpleCart.each function to iterate through them and find these values.  something like this:

``` javascript

var maxWidth = 0, maxLength = 0, weight = 0, girth =0;
simpleCart.each(function(item){

  maxWidth = item.width > maxWidth ? item.width : maxWidth;
  maxLength = item.length > maxLength ? item.length : maxLength;
  weight += item.weight;
  girth += item.girth;

});

```
