### ISSUE TITLE
Images in cart appearing as text links

### ISSUE THREAD

**Issue by ghost** [wojodesign/simplecart-js#127]
In the shopping cart below the Image header it says http://www.mySite.com/images/myImage.jpg - but the real image link.  It doesn't show the image.  Everything else works and appears in the shopping cart.  I made sure Image is capitalized in cart headers in the code.  How can I fix this?
img style="display:none;" id="ItemImage" class="item_image" name="Image" src="http://www.mySite.com/images/myImage.jpg"

**Comment by ghost** [comment]
The image still doesn't appear if I get rid of style="display:none;".

**Comment by brettwejrowski** [comment]
Do you have a link to the page?

**Comment by guvas** [comment]
I have same problem, can any one help me pleas?

I do not know how to display image,  i did everything possible and not possible, but  I just do not get it.

I did not go the tag <img  and displays only the path to the image like this images/picture.jpg

Explain  to me please in thoroughly , how  can  i fix this?
