### ISSUE TITLE
Problem with changing currency

### ISSUE THREAD

**Issue by netsatan** [wojodesign/simplecart-js#128]
Hi,

I've got a little problem with setting the currency. I did as said on the documentation: I mean added simpleCart.currency = PLN;  line in the code and everything seems to work fine, except of what happens when I want to go to checkout. PayPal still uses USD, no matter what currency is set in the simplecart. div class="simpleCart_total" shows price in PLN, but PP wants me (I mean as a customer ;) ) to pay in USD.  How can I fix it? 

Thanks for your help,
netsatan :)

**Comment by fjpena** [comment]
I have the same issue. Setting up the cart to EUR or Euro, everything seems to work fine until I go to PayPal. Then, the amount is shown in USD.

Thanks in advance,
Javier

**Comment by fjpena** [comment]
I think I got it. It turned out to be a simple issue. In simplecart.js, line 272, it reads like this:

```
    form.appendChild(me.createHiddenElement("currency_code", "me.currency"));
```

me.currency is a variable, so it should not be between quotes. The line should read:

```
    form.appendChild(me.createHiddenElement("currency_code", me.currency));
```

Hope it helps,
Javier

**Comment by netsatan** [comment]
Oh, so it was that simple! Thanks for your help. :)
