### ISSUE TITLE
How to open checkout in new window?

### ISSUE THREAD

**Issue by netsatan** [wojodesign/simplecart-js#130]
Hi,

It may sound funny to you, but my problem is... how to open checkout (I mean PayPal Checkout) in a new window? My website is build with frames, so it doesn't look good when PayPal window shows up in the main frame. Does anyone know how to open it in a new window/card in browser? Thanks. :)

Regards,
netsatan

**Comment by netsatan** [comment]
Ok, solved it myself. What you need to do is add form.target = "_blank"; line in the script, inside paypal checkout function.

**Comment by ghost** [comment]
Can you let me know where exactly you put it, I tried to figure it out but cant seem to find it.

**Comment by escusado** [comment]
For anyone looking for a solution to this, (I'll assume you are using the minified version), in your text editor "search/find" for `"method"` this is the part where the dynamic form is created it should look like this:

```
...ction);d.attr("method",a.method);b.each(a.da...
```

edit it so it looks like this:

```
...ction);d.attr("method",a.method); /* blankMod */ d.attr("target", "_blank"); /* /mod */ b.each(a.da...
```

This will launch the checkout into a "_blank" target.
