### ISSUE TITLE
[SOLVED] Empty cart after payment

### ISSUE THREAD

**Issue by irob** [wojodesign/simplecart-js#132]
Solved... just deleting the cookie using a simple function [http://javascript.about.com/library/bldelck.htm]

```
    function del_cookie(name) {
        document.cookie = name + "=; expires=Thu, 01-Jan-70 00:00:01 GMT;";
    }

    del_cookie("simpleCart");
```

---

Hi everyone

I had implemented SimpleCart into my site, but in the last step, after the payment, the cart still contein the products.... I did't get to empty it.... how could I do it????

Thanks 4 all
;)

**Comment by Dudikowski** [comment]
Where did you put that code?

**Comment by seanvwolf** [comment]
This isn't appearing to work in my site.  Can you give a full description of how this function called and were you placed it?

I put this after the simplecart script, within &lt;head&gt; :

&lt;script&gt;
function del_cookie(name) {
document.cookie = name +
'=; expires=Thu, 01-Jan-70 00:00:01 GMT;';
}

$(function(){
    del_cookie("simpleCart");
});
&lt;/script&gt;

**Comment by DanielRuf** [comment]
Did this not work? http://simplecartjs.org/documentation/simplecart-empty

**Comment by fransu** [comment]
This works for me:

var i = localStorage.length, key;
while (i--) {
  key = localStorage.key(i);
  if (key.slice(0, 16) == "simpleCart_items") {
    //   alert('This is the one');
    //  localStorage.clear();  // works also
    localStorage.removeItem(key);
  }
}
