### ISSUE TITLE
Shipping by Location

### ISSUE THREAD

**Issue by ytokgoz** [wojodesign/simplecart-js#133]
hello, how can i add shipping like for uk x price on top of items, for europe y price and rest of the worlz z price.
how can i do it and how can i put it in code.
thank you

**Comment by brettwejrowski** [comment]
You could have a select for location on the page, and add an event to change simpleCart shipping costs based on the value when its changed.

**Comment by ALaf** [comment]
i would like to do this too, but cannot really wrap my head around "add an event" part.  i'd appreciate if someone can describe this a bit for me.  i don't know much how js works.  thank you in advance.
