### ISSUE TITLE
Configurable characters for increment/decrement/remove

### ISSUE THREAD

**Issue by mattbishop** [wojodesign/simplecart-js#135]
Simplecart hard-codes the text for the increment/decrement/remove links as '+', '-', 'Remove'. This has two problems:
1. It isn't localizable.
2. It isn't replaceable with alternate chars.

OK, the two problems are the same but right now I have to change the code to my chars, which incidentally are "▲", "▼" and "✖".

**Comment by brettwejrowski** [comment]
Thanks Matt, this will be completely customizable in v3, but will have to be changed individually on the current code if needed.
