### ISSUE TITLE
Clear cookie when cart emptied

### ISSUE THREAD

**Issue by TurboPCI** [wojodesign/simplecart-js#136]
I know almost no javascript and working with this cart has helped - but not enough.  Neither has scouring the internet.  I cannot figure out how to completely empty the cart via a button. My document is DTD XHTML Transitional.  I'm using dhtmlwindow (http://www.dynamicdrive.com/dynamicindex8/dhtmlwindow/index.htm) with its plugin dhtml modal window 1.1 (http://www.dynamicdrive.com/dynamicindex8/dhtmlwindow/dhtmlmodal.htm) along with simpleCart.js v2.2.  The cart opens in an iframe. Here are the scripts in the parent window:

```
<script type="text/javascript" src="simpleCart.js"></script>
<link rel="stylesheet" href="dhtmlwindow.css" type="text/css" />
<script type="text/javascript" src="dhtmlwindow.js"></script>
<link rel="stylesheet" href="modal.css" type="text/css" />
<script src="modal.js" type="text/javascript"></script>
<script type="text/javascript">
function wopen() {
cartwindow=dhtmlmodal.open("cart","iframe","cart.html","TurboPCI Shopping Cart","scrolling=1,resize=0,width=660px,height=600px,left=40px,top=100px");
}
</script>
```

First of all, this line in the body of the iframe (cartwindow) isn't working correctly:
`<a href="javascript:;" class="simpleCart_empty">Empty Cart</a>`
 It empties the cart in the modal window but doesn't _actually_ empty the cart.  If I close the modal window and add something else to the cart, the previous item is still there.  I know I need to delete the cart cookie but I've tried adding "eraseCookie('simpleCart')" to the empty cart function in simpleCart.js, no deal.  I didn't mess with the code in simplecart.js otherwise.

And to complicate matters further, I want to hide the modal window when "Empty Cart" is clicked. I was trying to do it all via one line, but calling the class doesn't seem to allow me to do anything else on click...

`<a href="javascript:;" class="simpleCart_empty" (PLUS) eraseCookie('simpleCart') (PLUS) parent.cartwindow.hide();return false>Empty Cart</a>`

BTW, parent.cartwindow.hide() works fine with my "continue shopping" button....

PLEASE help, I know it's something simple but can't figure it out.  If I need to throw all of this up on the web just let me know...
Thanks!

**Comment by mattbishop** [comment]
The way I am doing this is looking for a hash in the url and then calling empty directly. In my HTML page, I have this code:

  if ('#ordercomplete' == window.location.hash) {
    simpleCart.empty();
    window.location.hash = '';
  }

The way it works is that if the browser uses a URL with the "#ordercomplete" hash, the code will empty simplecart and clear out the hash. For instance:

http://myserver.com/store.html#ordercomplete

Will trigger this script in store.html to empty the cart and clear out the "ordercomplete" hash. This step is important to keep the user from accidentally clearing their cart when they hit refresh or bookmarking it.

When would this URL be used? It is used as the return page from paypal or google checkout. When the page loads, I set the successUrl like this:

  var successHref = window.location.href;
  var hashLoc = successHref.indexOf('#');
  if (hashLoc > -1) {
    successHref = successHref.substring(0, hashLoc);
  }
  simpleCart.successUrl =  successHref + '#ordercomplete';

simpleCart will pass this successUrl to Paypal/google and when the user successfully checks out, they get redirected to the successUrl. This triggers the empty cart code, and you now have a completed order with an empty cart.

**Comment by antonyf** [comment]
this is helpful thanks. I was wandering if you could give a fix to delete the cookie on empty cart. Reason being, For me. Is when i clear cart, and refresh the page, and then click to add to cart to ad a product to cart. It also adds a mysterious 0.00 product without a name, just a total one.. 
This has happened on all the versions of simple cart.. 
I figure if i could delete the cookie on empty cart. my problems would be solved.

**Comment by Dudikowski** [comment]
@antonyf 

I could see this problem too and there is a second cooke that needs to be deleted.
sc_simpleCart_chunks

Take a look at this thread
https://github.com/wojodesign/simplecart-js/issues/67

**Comment by antonyf** [comment]
Thanks Dudikowski.
I did clear the mystery with the cookies in the end.
Im currently battling with this issue:

https://github.com/wojodesign/simplecart-js/issues/177

I cant seem to get the email function to pass the cart items. I used the example to set up the forms here:
https://github.com/wojodesign/simplecart-js/issues/84

The function does work with the original older version of simpleCart.js. But with version 2.2 which i got working nicely. It does not work.
Can you take a look at this issue?
https://github.com/wojodesign/simplecart-js/issues/177
I have been at it for 7 days now.
I get two different errors:
when i get result i get like this:
<div class=\"simpleCart_items\">\" div.innerHTML \"</div>Success!

and another way i get also like this:
[object HTMLDivElement]

?? my javascript is not too good.
Regards
Antony

**Comment by dalegrant** [comment]
@mattbishop 

Your method seems the best solution but I don't really understand how to implement it. Where exactly am I putting the code?

**Comment by dalegrant** [comment]
No problem, all sorted now. I'll try and lay it out as simply as possible...

Edit simpleCart.js  ( for me its at /wp-content/themes/viroshop/includes/js/simpleCart.js) with notepad or other text editor (download it and rename it simpleCart.js.txt)

At the very bottom, change the code so it reads:

var simpleCart = new Cart();

if( typeof jQuery !== 'undefined' ) $(document).ready(function(){simpleCart.initialize();
if ('#ordercomplete' == window.location.hash) {
simpleCart.empty();
window.location.hash = '';
}

})
else if( typeof Prototype !== 'undefined') Event.observe( window, 'load', function(){simpleCart.initialize();});
else window.onload = simpleCart.initialize;

Then, upload it back to your site (remember to remove the .txt)

Login to Paypal and change your profile settings there so when payment is made it redirects to www.yoursite.com/yourpage#ordercomplete

For example, mine is http://www.chunkyjunkie.com/payment-successful#ordercomplete.

I hope this helps someone, I'd been struggling for a couple of days now.
