### ISSUE TITLE
paypalCheckout missing 'charset' hidden element

### ISSUE THREAD

**Issue by mattbishop** [wojodesign/simplecart-js#138]
The paypalCheckout() method needs to provide a charset field to communicate what encoding should be used to display the cart contents. The missing line should be at line 273:

```
form.appendChild(me.createHiddenElement("charset", "utf-8"));
```

**Comment by brettwejrowski** [comment]
Is this not accomplished by setting the charset of the form?

`264|       form.acceptCharset = "utf-8";`

**Comment by mattbishop** [comment]
Not enough; you need to actually create a form entry for charset:

https://www.paypalobjects.com/en_US/ebook/PP_WebsitePaymentsStandard_IntegrationGuide/formbasics.html#1052289

**Comment by brettwejrowski** [comment]
thanks matt, i have updated this in both the master branch and v3
