### ISSUE TITLE
paypalCheckout doesn't set the currency (though it tries to)

### ISSUE THREAD

**Issue by mattbishop** [wojodesign/simplecart-js#139]
In simplecart.js, please see line 272:

```
    form.appendChild(me.createHiddenElement("currency_code", "me.currency"));
```

The evaluation of "me.currency" will be "me.currency" rather than the actual shopping cart currency setting. Remove the quotes please:

```
    form.appendChild(me.createHiddenElement("currency_code", me.currency));
```

**Comment by brettwejrowski** [comment]
Same issue as https://github.com/wojodesign/simplecart-js/issues/144 - fixed in current master branch.
