### ISSUE TITLE
Only first option recognized?

### ISSUE THREAD

**Issue by Yra** [wojodesign/simplecart-js#14]
Hello and thanks for the shopping cart.

I have set up the cart and it's working fine but I have an issue regarding multiple options.
When I set up multiple item_Something (I use one select and 3 checkbox for a total of 4 different item_something) only the first one is passed to paypal, all the others are ignored. Is there a way to make them appear?

**Comment by Schop** [comment]
Did this problem ever get resolved? Is this forum actually active at all?

**Comment by ghost** [comment]
Schop I was feeling abandoned like you and went to their blog. The answer is tere (ain't good at all) http://www.thewojogroup.com/2010/05/update-from-the-wojo-group/

**Comment by loraxio** [comment]
I had this same issue drive me crazy... my solution was to do this:

<div id="item_Description">
        <select class="item_Whatever" name="Whatever" id="Whatever">
              <option value="6">6</option>
              <option value="5">5</option>
              <option value="4">4</option>
        </select>
        <select class="item_OtherThing" name="OtherThing" id="OtherThing">
              <option value="Green">Green</option>
              <option value="Blue">Blue</option>
              <option value="Red">Red</option>
        </select>
</div>


What I found, is that you have to put everything that you want passed to PayPal (or Google Checkout) that is a custom field within the DIV "item_Description".  Otherwise, the custom fields just sorta vanish into thin air.

Hope this helps.

**Comment by loraxio** [comment]
Ooooops...forgot the PRE tag.  Here is the HTML I used to get all of the option to show up:

<pre>
<div id="item_Description">
<select class="item_WHATEVER" name="WHATEVER" id="WHATEVER">
   <option value="Green">Green</option>
   <option value="Red">Red</option>
   <option value="Blue">Blue</option>
</select>
<select class="item_ANOTHER" name="ANOTHER" id="ANOTHER">
   <option value="1">1</option>
   <option value="2">2</option>
   <option value="3">3</option>
</select>
</div>
</pre>


This way, all of the things that are in between the item_Description tags taht are selected by the user, gets passed.

-j

**Comment by loraxio** [comment]
Aaaargh, can't get code to show up... visit http://bapjc.org/custom_archer/bows.html to see what I am talking about

**Comment by brettwejrowski** [comment]
options improved for paypal checkout in 2.3
