### ISSUE TITLE
Add a Date item in simplecart ??

### ISSUE THREAD

**Issue by Mediabahn** [wojodesign/simplecart-js#141]
HI !

I like to put a date item on simple cart is it possible, like:

<div class="achat">
<a href="javascript:;" onclick="simpleCart.add('name=solidworks', 'price=400.00','date=15 septembre 2011','quantity=1');" >Ajouter au panier</a>
</div>

 Possible ?

TIA

Need a french traduction, i'm your man ! ;-))

**Comment by Mediabahn** [comment]
Sorry !

The source:

 onclick="simpleCart.add('name=ÉCOUTE ACTIVE', 'price=40.00', 'date=15 septembre 2011','quantity=1');" >Ajouter au panier

**Comment by Mediabahn** [comment]
Solutions:

simpleCart.cartHeaders = [ "Name" , "date", "Quantity", "Price" ,  "Total" ];

css .itemsdate

Nice script

;-))

**Comment by shaustre** [comment]
Hi Mediabahn how did you resolve this, i saw your code, and i changed the headers but everytime the cart is updated, my date dissapear, thanks in advance.
