### ISSUE TITLE
SimpleCart doesn't work on my site

### ISSUE THREAD

**Issue by naranili** [wojodesign/simplecart-js#143]
Hi !

I can't get the simpleCart run on my site http://boobsings.com.

When i 'add to cart' something i will be redirected to the checkout, but there is nothing displayed.

I updated to the last release of simpleCart and also make the it the first loaded JS.

I need help.

Regards
Ralf

**Comment by iamstevemckinney** [comment]
You have jQuery included twice (you also have simpleCart.js included twice, but that doesn't seem to be breaking it, just not a good idea).

simpleCart.js will use jQuery to help with some stuff if jQuery is present. Including jQuery twice is causing an error with this. Removing this script seems to remove those errors.
http://boobsings.com/wp-content/themes/duotive-three/js/jquery.custom.js
