### ISSUE TITLE
Create quantity based shipping per item?

### ISSUE THREAD

**Issue by giandy13b** [wojodesign/simplecart-js#145]
I'm selling more then one type of item on my website, and I'd like to know how to make it so that if I purchase more then one item it doesn't give just a fixed "shippingQuantityRate" price, because this doesn't work when I am selling large and small items. 

If there was a way to add something to each shelf item like "(input class="item_shipping_quantity_rate" value="2.00" type="hidden")" would work so I could make it add a certain price for more quantities of this particular item and not the others.

Thanks.

**Comment by brettwejrowski** [comment]
You could overwrite the shipping function and iterate through the products, creating a different shipping quantity rate based on a certain item value.  For example, lets say all "Blue Shirts" had a shipping quantity rate of 2, and all "Red Shirts" had a shipping quantity rate of 3.  The code would look like this:

```
simpleCart.shipping = function(){
  var total = 0;
  simpleCart.each( function( item ){
    if( item.name == "Blue Shirt" ){
      total += 2*item.quantity;
    } else if( item.name == "Red Shirt" ){
      total += 3*item.quantity;
    }
  });
  return total;
};
```

Hope that helps!
