### ISSUE TITLE
can't add to cart

### ISSUE THREAD

**Issue by warburtonlabs** [wojodesign/simplecart-js#146]
everything was running great with my simplecart store for a couple months.
(http://warburtonlabs.blogspot.com/p/printlab.html)
then one day i realized that items couldn't be added to the cart.
so i re-did the 'add to cart' scripts...
and it was back to normal.
then a couple days later it stopped working again.
only worse.
now it takes me to a blogger error code-- bX-v2a0xl
and i can't get it to work at all.

let me add that i know virtually nothing about html.
i simply copied and pasted all the simplecart stuff in
(and was quite shocked i got it to work)

here's a sample item:

<span style="font-weight: bold;">NUMBUH ONE</span>

<a href="http://4.bp.blogspot.com/-rUmas2SQL78/TcmzGI80YfI/AAAAAAAACko/PVUjlWxbZ4E/s1600/Numbuh%2BOne%2B%2528smaller%2529.jpg"><img alt="" border="0" id="BLOGGER_PHOTO_ID_5605208129302454770" src="http://4.bp.blogspot.com/-rUmas2SQL78/TcmzGI80YfI/AAAAAAAACko/PVUjlWxbZ4E/s400/Numbuh%2BOne%2B%2528smaller%2529.jpg" style="cursor: hand; cursor: pointer; display: block; height: 309px; margin: 0px auto 10px; text-align: center; width: 400px;" /></a>
8.5" x 11" digital print of Nigel Uno aka Numbuh One!
Printed on high quality Arches Aquarelle Rag.
Inscribed to whoever you like and signed by Mr. Warburton himself!
Price : $25 (domestic shipping included)
<a href="http://www.blogger.com/post-edit.g?blogID=6148971677114312551&amp;postID=5475843517164143590#"> add to cart</a>

is this enough for anyone to know what i'm doing wrong?

**Comment by warburtonlabs** [comment]
oops... thought the code would show up.
here's the add to cart code:

a href="http://www.blogger.com/post-edit.g?blogID=6148971677114312551&amp;postID=5475843517164143590#"> add to cart

**Comment by brettwejrowski** [comment]
Looks like your add to cart link doesn't have any simpleCart code in it.  maybe it got overwritten in Blogger?
