### ISSUE TITLE
Add item only one time into the cart

### ISSUE THREAD

**Issue by alexistkd** [wojodesign/simplecart-js#147]
Hi its possible to customize this great shop cart like this: client see list of items and the button to the right named: Add to cart but when click it it turns into Remove so only one time can be added the item add or remove nothing else. Can be done? some tips?

Thanks in advance.

**Comment by brettwejrowski** [comment]
I'm not sure I understand what you are trying to do, but I believe you only want to have one item in the cart at a time.  The best way to do this would be by using the 'beforeAdd' event:

```
simpleCart.bind( 'beforeAdd' , function( item ){
  // remove the other items
  simpleCart.empty();

  // if you only want the quantity of this item to be one:
  item.quantity = 1;
});
```

Hope that helps!

**Comment by ALaf** [comment]
hi brett, could you clarify this a bit for me?  i think my question is basically the same, i sell one-of-a-kind products and would be convenient if customers cannot add more than 1 of the same item.  

with the code above, naturally the shopping cart only lets me have one item at a time.  

how can i make it so the cart allows only 1 each but as many of different products? thanks!

**Comment by ggeiger** [comment]
ALaf, I resolved this with great help here:

https://github.com/wojodesign/simplecart-js/issues/202
