### ISSUE TITLE
Setting page to redirect to on successful PayPal checkout

### ISSUE THREAD

**Issue by nickharambee** [wojodesign/simplecart-js#148]
Hi,

Using standard PayPal buttons I can set a page to redirect the user to on my website on successful completion of checkout.  I am wondering if there is a method of doing this using simplecart with PayPal.

Thanks,

Nick

**Comment by ghost** [comment]
simpleCart.successUrl = "http://your-domain.com/";

**Comment by mlbbarnes** [comment]
This is kind of an old post but the successUrl leaves you on Paypal and the user has to click "return to <Company Name>" in order to get to that page. Is there a way to auto redirect it?

**Comment by valeria-io** [comment]
Where should I include "simpleCart.successUrl = "http://your-domain.com/"; ?????
