### ISSUE TITLE
custom checkout

### ISSUE THREAD

**Issue by blackwingedangel** [wojodesign/simplecart-js#149]
Hi, 
I was able to set up and run simpleCart, I don't want to check out using paypal and google because i want buyers to fill up a form and send it directly to my email. I created a .php checkout page and was able to show view cart details on the page. "The only problem is I cannot make the cart details to send together with the filled up form" because the the shelf items are in div element. Is there trick to make this work?. ALL HELP and ANSWER are HIGHLY APPRECIATED.

**Comment by twitchsbrew** [comment]
You'll need to make your own custom checkout.  There is an empty custom checkout function in the simpleCart.js file.
Here is an example of my custom checkout code.  This code essentially pushes my cart quantities to an array called "products" that gets stored in a text field called "products" that the checkout code creates. (the productid of each product stores various info about the product separated by _ for example 12_150. so I can explode it by _ in php when processing the checkout)  This text field is then appended to the form on my page as a hidden field (in this case the form id is "search") then submits the form.  Once submitted I process the products array using php.

me.customCheckout = function() {
        var me = this
        var form = document.getElementById("search"),//<--THIS WOULD BE THE ID OF YOUR FORM
            counter=1,
            current,
            item,
            descriptionString;

```
    form.style.display = "none";
    form.method = "POST";
    form.action = "reservation.php";
    form.acceptCharset = "utf-8";

    var products = [];
    me.each(function(item,iter){

        counter = iter+1;

        products.push(item.productid+"_"+item.quantity);//<--put products in the products array
            });//end each

        form.appendChild( me.createHiddenElement( "products", products      ) );//<--create the hidden products field and set the products array as it's value


    document.body.appendChild( form );
    form.submit();//<--submit the form
    document.body.removeChild( form );
    simpleCart.empty();//<--empty the cart
};
```

Hope this helps.

-Twitch
