### ISSUE TITLE
Webpage in € but paypal see in $?

### ISSUE THREAD

**Issue by uNbAs** [wojodesign/simplecart-js#152]
Good morning!

First of all excuse my writing, I am Spanish and I do not write well in English, I am using a translator.

I have a little problem, I created a test site with currency EUR (€) but if you buy something, the paypal page is displayed in USD ($)

http://img528.imageshack.us/img528/1813/webpage.png
http://img521.imageshack.us/img521/9823/paypalz.png

You help me fix this?

**Comment by anderstn** [comment]
Hi

I am having the same issue with Norwegian Krone (NOK).
Thanx in advance for a fast solution to the problem :-)

**Comment by fjeldstad** [comment]
This seems to be caused by a bug in the `paypalCheckout` method. See [line 272](https://github.com/wojodesign/simplecart-js/blob/master/simpleCart.js#L272) - note how the form field value is set to the string `me.currency` instead of the property value?

**Comment by anderstn** [comment]
Yepp that solved the problem. Thankyou :)

**Comment by uNbAs** [comment]
Hihaj Thank you very much for your response, it is clear that there is the problem, but now I have another I am not a programmer and not find a way to fix it, can you help me?

TinyDancer As you solved?

Thanks for all

**Comment by TomDubyes** [comment]
uNbAs
open file simpleCart.js

find 272th line -> form.appendChild(me.createHiddenElement("currency_code", "me.currency"));
and remove "" from me.currency, so your line should looks like this -> form.appendChild(me.createHiddenElement("currency_code", me.currency));

if it didnt help, find line 49 -> me.currency = USD; and change it as well
save file, and everything should work fine.

**Comment by anderstn** [comment]
removing "" should do the trick assuming me.currency is set to the apropriate value.
It worked just fine when i tried it. make sure you edit the correct file and the correct method. 
think someone posted the exact line number of the method in an earlier post.

**Comment by brettwejrowski** [comment]
Thanks for finding this guys, the master branch has been updated with the quotes removed.
