### ISSUE TITLE
Incrementing doesn't add shipping cost. 

### ISSUE THREAD

**Issue by ReechApparel** [wojodesign/simplecart-js#154]
When you are in the shopping cart and press the + button, it updates the total but does not add additional shipping cost. I have a shipping flat rate set at $2.50 per shirt but if I had 2 of the same item it keeps the shipping at $2.50 and not $5.00, any ideas?

**Comment by glenpike** [comment]
You need to use the "shippingQuantityRate" variable instead of "shippingFlatRate"

Look at the Shipping info on the docs page: http://simplecartjs.com/documentation.html

**Comment by ReechApparel** [comment]
THANK YOU! Such a great program and I was going nuts in the .js file for no
reason. Thanks again
On Oct 17, 2011 5:25 PM, "glenpike" <
reply@reply.github.com>
wrote:
