### ISSUE TITLE
Shelf item with id of "s#" does not exist. 

### ISSUE THREAD

**Issue by twitchsbrew** [wojodesign/simplecart-js#156]
I'm seeing "Shelf item with id of "s#" does not exist."  in the console when I click and item to add to cart.  The cart appears to work, but I was curious as to what was going on.  Just want to make sure it won't cause problems in the future.

Absolutely love this cart though.  Is exactly what I was looking for.  Wish I would have found it sooner...haha

Thanks in advance.

-Twitch

**Comment by scttrgd** [comment]
Could you elaborate a little more? It might be something you have in the html? 

Ben

**Comment by twitchsbrew** [comment]
Thanks for the reply, Ben.  I believe it was in the html.  It has since stopped throwing those errors.  Working great now.

-Twitch
