### ISSUE TITLE
Shipping by Total Price

### ISSUE THREAD

**Issue by scttrgd** [wojodesign/simplecart-js#157]
I'm looking to set the shipping cost by how much the total cost is. (eg. if total > then shipping = £9  else shipping = £0) 

However I'm not really comfortable in where to put this or what to change.

I do also have a problem in general that the shipping isn't added if I have the standard code within the HTML. However if the shippingflatrate is changed in the js file then it adds it. 

Cheers for the help 

Ben

**Comment by ghost** [comment]
Around line line 934 of simpleCart.js change :
        return shipping;
To (where 50 is the threshold for free shipping) :
if((me.total + me.taxCost) >= 50){
        shipping = 0;
        }
        return shipping;

**Comment by brettwejrowski** [comment]
The easiest thing to do would be to overwrite the simpleCart.shipping function like this:

simpleCart.shipping = function(){
  if( simpleCart.total < 50 ){
    return 9; 
  } else {
    return 0;
 } 
};
