### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by twitchsbrew** [wojodesign/simplecart-js#158]
Is there a way (or where would I put the code) to sort the items by a certain attribute?  For instance, when a new product is added to the cart I would like all products of a certain type to be grouped together (next to each other).  Probably not a simple thing, but just thought I'd ask if anyone has done something like this and has code to share.

Thanks in advance.  Absolutely love this cart.

-Twitch.

**Comment by brettwejrowski** [comment]
There is currently not a way to do this, but I will see if I can work it into v3.  If you were to add it to this version, I would probably sort the array of items at the top of the "updateCartView" on line 543.  

If you have a sorted array of items called MyArray, you can pass that to the ".each" function as the first parameter on line 567.  Hope that helps! I'll let you know if I find a better way to do it on v3

**Comment by twitchsbrew** [comment]
Thanks for the quick reply, Brett.  I may try that when I get some time.  I'll let you know if I come up with something useful...haha

-Twitch
