### ISSUE TITLE
Adding text fields/email to paypal check out option

### ISSUE THREAD

**Issue by AllanSMW** [wojodesign/simplecart-js#159]
Great script (although I don't know CSS well enough to make it look as nice as the demo!).
I've tinkered with some bits, I think there's an errors in line 49 and 50 which makes it hard coded for USD and Paypal - just need to put "" in simpleCart.js (it was showing ok on the page as £ GBP, but when I went to check out Paypal showed USD $).

Anyway my problems are this:
I'm using it to book tickets and want to gather text information, however there is no guarantee that any given ticket/item will be brought but I want to collect text form entries for: Name, email, Telephone, Dietary needs.

As far as I can tell my options are:
a) I add it to the Paypal bill as a "0" price item, except I can't figure out how to automatically enter it into the cart.  (It also shows up on the cart total.)  This seems to be a limitation of paypal.

b) The alternative is that I have the text fields and they are sent to my email when I click on "Pay Now".

Any ideas? I've gone through most of the GIT, and have seen mention of email, but seems to be instead of Paypal checkout rather than as well as.
This text field issue is a pain!

**Comment by brettwejrowski** [comment]
Hey AllanSMW, I believe what you are doing is trying to attach some custom fields that describe the user, independent of the items in the cart.  As far as I can tell, you will either have to do the "extra item" for the info with a price of zero or have a custom script email some details to you (assuming PayPal doesn't gather the data for you).  I'm not sure there is a solution that does this right now, but I would say the easiest thing would be the "extra item".
