### ISSUE TITLE
update cart total after initialize function

### ISSUE THREAD

**Issue by twitchsbrew** [wojodesign/simplecart-js#160]
Can't say enough how much I enjoy working with this cart.  I was wondering if anyone has successfully loaded the cart from a database table instead of the cookie.  I am using the cart for reserving certain products.  I want the user to be able to go in and edit what they have reserved so I need the cart to show products that were stored in the database.  The PHP code to create the products from the database is easy enough (I generate the itemContainer template with the values filled from the database), however I need the javascript that will parse the itemContainer and figure out quantities and prices of the products like it does when it gets the products form the cookies.  When I loop through the reserved products the "load from cookie" code overrides the products I create from the database.  If I comment out the load from cookie code, the products appear properly in the cart but totals and quantities don't update.

I know there isn't a simple solution but I was just hoping someone as already done this and has some sample code.

[UPDATE]
Ok I'm closer to getting this to work.  I can populate the cart with products stored in the database by copying the html of the itemContainer of each item that was in the cart, however, the cart totals don't update and the  increment, remove, decrement buttons, and quantities don't work.  I know it's because the cart needs to know what is in it.  Which function(s) can I rerun after the products are generated in the cart so they work normally again?

Really need to get this going so if anyone can help I would really appreciate it.

Thanks in advance,
Twitch

**Comment by brettwejrowski** [comment]
Hey Twitch, I'm not sure I'm following what you are trying to do here.... You are loading the cart contents from a database instead of the cookies?

**Comment by twitchsbrew** [comment]
Correct, that's the goal.  Items in the cart are reserved, not bought so check out is essentially tying the products to the reservation.  The user has the option to go in after the reservation is created and change which items they want.  Everything works great on saving the reservation.  I use the cookie to populate the cart contents on page reload while making the reservation.  I just can't figure out how to populate the cart in the same way from the products stored in the database when editing the reservation.  I'm guessing I need to figure out the format the cookie uses to store the products and pull the products out of the database in that format so I can feed it to the read from cookie function since SimpleCart knows what to do with that format.  That's the theory anyway...haha 
I believe the cookie stores the info in a url which sounds simple enough to recreate but I tried looking at the cookie so i could figure out what the url looks like and it looked like greek to me...haha

Hope my explanation makes sense.  Thank you so much for the reply. 

-Twitch
