### ISSUE TITLE
Minimum Order

### ISSUE THREAD

**Issue by scttrgd** [wojodesign/simplecart-js#161]
Hi, quite simply, I'm looking to add a minimum order charge of $30. That is to say, you cannot get to the checkout unless there is at least $30 in the cart

Thanks

**Comment by brettwejrowski** [comment]
In v2, the best way would be to edit the .checkout() function and just return false and throw an alert if the minimum order isn't met.

**Comment by scttrgd** [comment]
Thanks Brett. Next question. How would one go about implementing this? I'm pretty useless when it comes to changing the Js. 

Cheers

Ben

**Comment by soydemadrid** [comment]
Hi I'd be interested too please in how to implement this? I need to add a minimum quantity before a customer can order please?
