### ISSUE TITLE
Dynamic Price changes

### ISSUE THREAD

**Issue by mudmaps** [wojodesign/simplecart-js#163]
This cart is really neat - thank you.

The prices of my services change according to 3 user-entered parameters. I use javascript to do the proper calculation but wonder ... how do I insert the final price variable into the simpleCart.add function?

**Comment by brettwejrowski** [comment]
This depends on how you are adding items, from code or a shelf Item.  You can also tie into the beforeAdd event like this:

simpleCart.bind('beforeAdd',function( item ){
  // set the item price here depending on your inputs
  if( item.color == "Blue"){
    item.price = 4;
  } else {
    item.price = 5;
 } 
});

**Comment by mudmaps** [comment]
Great thanks Brett.  I'll drill down into that function a bit more.

cheers
