### ISSUE TITLE
Extending to custom payment gateways

### ISSUE THREAD

**Issue by seyekuyinu** [wojodesign/simplecart-js#165]
I want to find out if this was made extensible for other payment gateways.

**Comment by laucb** [comment]
I also want to know

**Comment by brettwejrowski** [comment]
Which payment gateways are you looking to use?  v3 is currently built to use paypal, google, and amazon.  It also has a form method that will send a checkout form to any script, so you can checkout to anything.  We have set it up in the past to use both Authorize.net and PayPal Pro.

Let me know what gateways you are looking for an I can try to either add it to the core code, or create an extension for it.  

I do not have the docs ready yet, but creating your own payment gateway is much easier in v3.

**Comment by seyekuyinu** [comment]
Sorry for the late response. I am thinking of using it with the Interswitch payment gateway. It's the major payment gateway we use at this part of the world. 

Thanks.

BTW HOW SOON IS v3 coming????? Excited already

**Comment by ALaf** [comment]
Will it be possible to have more than one payment options for the customer to pick from in the new version?  that would be fantastic.

**Comment by bkeating** [comment]
Hey @brettwejrowski, On supporting Authorize.net... do you mean to say you used the SendForm to submit back into your site (Python, PHP, whatever) and then use another means to send the request to Authorize.net? Or can you send the payment request, similar to how PayPal works--where you just show up on Authorize.net with the total amount for checkout?

Im starting to assume that the correct approach is to submit it back into my site for further processing before being taken to Authorize.net.

Appreciate any help on this. Im sooo close to finishing my project.
