### ISSUE TITLE
Thumb in cart V3 ?

### ISSUE THREAD

**Issue by Dennis-BC** [wojodesign/simplecart-js#167]
When I use this:

simpleCart.add({name:"test",thumb: "thumbnail_1322043189.png",   price: "10",quantity:1});

The thumbnail is not added to the cart and it says undefined. Can someone help me with this?

Tnx

**Comment by brettwejrowski** [comment]
What is it that says undefined, a value or in the cart?  v3 uses setters and getters, so to view the thumb of an item you would use item.get("thumb").

**Comment by Dennis-BC** [comment]
I understand ;)

, image: function( item , column ){
                //alert ("<img src=\"" + item.get(column.attr) + "\" />");
                return "<img src=\"" + item.get("thumb") + "\" />";
            }

It's when displaying the thumb in the cart. Then in firebug it says:NetworkError: 404 Not Found - http://www.123dagaanbieding.nl.cl1.intention.nl/undefined"

Looks like the var is empty. At first it's filled with the url and then suddenly it's empty..

**Comment by brettwejrowski** [comment]
Hmm alright let me look into it. Thanks for posting

**Comment by brettwejrowski** [comment]
I added a test for it and using an image view for a "thumb" attr seems to work.  Can you send a link to an example?

**Comment by Dennis-BC** [comment]
Hi,

I did edit the simplecart script for a supply Ajax check..

It's on http://www.123dagaanbieding.nl.cl1.intention.nl

Tnx in advance!!

Op 27 nov. 2011 om 18:21 heeft brettwejrowski reply@reply.github.com het volgende geschreven:

**Comment by brettwejrowski** [comment]
Hey drijken, It turns out this was an error with the storage of non-standard options.  It is fix in the latest commit.  If you want to update your file, you simply need to change "!==" to "===" on line 745 

https://github.com/wojodesign/simplecart-js/commit/6009aedf79390ca69d868bd07f3eac324ae75949
