### ISSUE TITLE
Email result mess up

### ISSUE THREAD

**Issue by ndisain** [wojodesign/simplecart-js#170]
Hi All,

I use email as checkout option. But the result when I receive in my email is very mess up. Is just like this:
Name
Price
Quantity
remove
Total
Zebra
$187.95
1
Remove
$187.95

Is there anyway to make my email result more better? Like this maybe?
Name: Zebra
Price: $187.95
Qty: 1
Total: $187.95

Thank you.

**Comment by antonyf** [comment]
Hi ndisain.
I cant help you im afraid. my javascript is quite useless.. But i am interested in the email function you use to send the email.
Could you post it here?

As for your problem with funny emails, The email is sent in .html format.. Maybe include a custom style sheet, or use tables and in the table that sends the data maybe something like text-align:center
