### ISSUE TITLE
ID not passed to html page

### ISSUE THREAD

**Issue by antonyf** [wojodesign/simplecart-js#172]
Hi, I tried all the version of Simplecart.js... Nothing solves my issue.
If i run the simple cart on its own (direct link to the html page) the cart script works fine. But when i access it via my website. The add to cart and the cart scripts don't work.

If i use Firebug, I noticed that the ID="sx" is not passed to anything in my Shelf and cart.

I tried changing the id from "S" to something else but that didn't work either. I Dynamically populate my store, so i cannot run it in a iframe.

What can i do?

I was thinking to change the Header references to something else, but i don't know where or how or what is causing the conflicts.. MY guess is that i need to take an existing name/var somewhere and change it to something unique..

simpleCart.cartHeaders = [ "name", "item_image" , "Quantity_input" ,  "increment",  "decrement", "Total" ]; 

My site relies on Heavily Javascript, and jquery... 
Can anyone tell me what to change to prevent the issue?

**Comment by antonyf** [comment]
17 hours of troubleshooting the not adding to cart episode. i figured it out. 
My site is setup to the root folder by default. So adding 

<script type="text/javascript" src="simpleCart.js"></script> 

didnt work.
i had to add:

<script type="text/javascript" src="http://www.xxxxxxx.com/folder/folder/js/store/simpleCart.js"></script>


In my defence why i didnt notice it before:
when i viewed the cart page on its own, it worked fine. it was when i viewed it in my site that it didnt work, and With hundreds topics on xxxx number of forums complaining about javascript errors (and conflicts), i assumed the worst...

Hope this helps someone.
Thanks for an awesome script

**Comment by mboperator** [comment]
What did you add exactly?
