### ISSUE TITLE
Bugfix on shelf css

### ISSUE THREAD

**Issue by bitlyfied** [wojodesign/simplecart-js#18]
Hi everybody.
I found a bug on the css parsing code.
If, for instance, the "Add to cart" link on the shelf has another class with an underscore, it doesn't work correctly. 

<a class='my_button item_add'>This won't work</a>

I suggest replacing line 808 with this:

var data = /item_([^ ]+)/.exec(node.className);

Regards

**Comment by wojodesign** [comment]
I have replaced the line with this:

var data = /item_[^ ]+/.exec(node.className)[0].split("_");

thanks for the help!
