### ISSUE TITLE
checkout display

### ISSUE THREAD

**Issue by bhunk** [wojodesign/simplecart-js#181]
ok so i have been playing with this great script for quite some time. i have manipulated the my css to have the items display out horizontally. now my only problem is that it doesnt line up neatly. i have product name, the price and the quantity. however it doesnt line up with name price and quantity. ive tried nudging the margin and spacing out the cartheader but longer product names will nudge it further down the page then i wanted. can anyone help me? point me in the right direction? or if imnot clear enough ask me a question. 

thanks

**Comment by Shruti-Bhati** [comment]
Could you please let me know how you did this(getting them horizontally)?
Its been a while and i seem to be losing my head.
All the products are displayed horizontally.

**Comment by bhunk** [comment]
this website doesnt like when u actually put the code in here so ill write it out. put this code inside your head tag. i bypassed the css bc im tired of going thru that huge css page. make sure you start it off with a style tag...im still having trouble with alignment and this still took me a while to figure out. let me know how it goes.

<style >

        .itemContainer{
            width:100%;
            float:left;
        }

        .itemContainer div{
            float:left;
            
            margin: 5px 20px 5px 20px ;
        }

        .itemContainer a{
            text-decoration:none;
        }

        .cartHeaders{
        
            width:100%;
            float:left;
            
                    }

        .cartHeaders div{
        text-indent:60px;
            float:left;
            margin:  5px 20px 5px 20px ;
            
         
        }


    .style1 {
        font-size: small;
    }


    .style2 {
        margin-left: 0px;
    }


    </style>

**Comment by mayersdesign** [comment]
If you want to post an url, I can have a look for you?

**Comment by bhunk** [comment]
www.mgdsealy.com   just play with adding orders youll see that they dont line up.... i would like a kinda grid set up but ive been moved onto another project and idk when ill get back to it.

**Comment by mayersdesign** [comment]
I think it's nothing more than a CSS/Markup problem. Feel free to email me directly tom@myusername.com and perhaps send a sketch of how you'd like it and I can sort it out for you. CSS is my bag....not JS! haha

**Comment by bhunk** [comment]
i emailed you. check your spam

**Comment by iamstevemckinney** [comment]
V3 of simpleCart allows you to display the cart in divs or a table. Most likely the table option would assist anyone else trying to do what bhunk was doing with one of the older versions. You can also view http://simplecartjs.org/ and add some demo products to your cart to see some CSS styling a "div" cart view.

I'm going to go ahead and close this issue due to inactivity.
