### ISSUE TITLE
Tax rate not working properly

### ISSUE THREAD

**Issue by bythewiseman** [wojodesign/simplecart-js#195]
When I have something that has Tax calculated at 1.998, the display rounds to 2.00 which is fine, but you send 1.998 to PayPal.  PayPal then disregards this value and doesn't include it in the value of the sale.

**Comment by bythewiseman** [comment]
simpleCart.js added a alert(me.taxCost) at line 276 to prove this.

**Comment by bythewiseman** [comment]
Where I added alert(me.taxCost) at line 276, i have now changed this to me.taxCost = me.taxCost.toFixed(2); in my local copy.  Let me know if this gets fixed in your version so I can update.

**Comment by brettwejrowski** [comment]
Merged pull request
