### ISSUE TITLE
Thumb src undefined

### ISSUE THREAD

**Issue by ggeiger** [wojodesign/simplecart-js#197]
I'm using simple to create a Wish List kind or thing. The image source is not sending to the next page, wishlist.php. Any help would be much appreciated!

http://geigercomputers.com/susansilver/products.php

**Comment by iamstevemckinney** [comment]
You have the item_thumb element outside of the simpleCart_shelfItem. All attributes for a product must be child elements of an element with the class name of "simpleCart_shelfItem"

**Comment by ggeiger** [comment]
Depending on the layout, this can be an easy mistake to make. Thanks for your help!
