### ISSUE TITLE
Different price for sizes

### ISSUE THREAD

**Issue by swfredrik** [wojodesign/simplecart-js#200]
Hi, would be a nice feature to be able to have custom prices for a products with options. I believe the intent is to have sizes like smal, medium, large. But I've got different models of the same product. 

<select class="item_Size">
                <option value="plastic">Plastic</option>
                <option value="gold">Copper</option>
                <option value="gold">Gold</option>  
</select>

**Comment by brettwejrowski** [comment]
This can be done with the beforeAdd event.  Please check closed issues for help.

**Comment by timfellin** [comment]
Where can I find the "closed issues" list?  Or are you referring to the "beforeAdd" documentation on your site?  Thank you, Brett!
