### ISSUE TITLE
Help: Formatting CartHeader Simplecart

### ISSUE THREAD

**Issue by Lilli73** [wojodesign/simplecart-js#201]
I would Evere headers of the truck in the Italian language. I always appear CardHeaders English.
 Name = Nome
 Size = Peso
 Price = Prezzo

How do? On site documentation says:

<div class="simpleCart_items">
  <div class="cartHeaders">
    <div class="itemName">Name</div>
    <div class="itemSize">Size</div>
    <div class="itemPrice">Price</div>
    <div class="itemdecrement">decrement</div>
    <div class="itemQuantity">Quantity</div>
    <div class="itemincrement">increment</div>
    <div class="itemremove">remove</div>
    <div class="itemTotal">Total</div>
    </div>
    <div class="itemContainer">
    <div class="itemName">Maglia Mario Rossi</div>
    <div class="itemSize">Small</div>
    <div class="itemPrice">€20.00</div>
    <div class="itemdecrement">
     <a href="javascript:;" onclick="simpleCart.items['c2'].decrement();">
     -
     </a>
    </div>
    <div class="itemQuantity">1</div>
    <div class="itemincrement">
     <a href="javascript:;" onclick="simpleCart.items['c2'].increment();">
     +
     </a>
    </div>
    <div class="itemremove">
      <a href="javascript:;" onclick="simpleCart.items['c6'].remove();">
      Remove
      </a>
    </div>
    <div class="itemTotal">€20.00</div>
  </div>
</div>

 How can I create a class to get the headers in Italian?
Cosa va scritto nel css?
Nel file simplecart.js cosa va modificato?

Grazie by Lilli

**Comment by iamstevemckinney** [comment]
This issue was resolved with v3 of simpleCart. Now you can write out your own cart headers. simpleCart.js is completely language agnostic.

Here's the doc page that applies: http://simplecartjs.org/documentation/cart_columns
