### ISSUE TITLE
Check if item already exists?

### ISSUE THREAD

**Issue by ggeiger** [wojodesign/simplecart-js#202]
I'm using simpleCart to create a list of favorite items. Each item should only be added to the cart once. I'd like to toggle the 'add to cart' button with a 'saved' button that is disabled, so the user cannot add it again until it is removed.

I thought to check against the item name, or the quantity. Then realized I don't know how to do that!

The toggle I have so far is:

simpleCart.bind( 'afterAdd' , function( item ){ 
    $(".item_add").fadeOut(function(){
        $('.saved').fadeIn();
    });
});

This toggles all items to show the 'saved' button. I need a way to check the cart to see if it's in there already.

**Comment by brettwejrowski** [comment]
You can iterate through all the items in the cart with the .each() function, and you can do this when simpleCart initializes.  First, lets say every item you add to the cart has a field called 'item-el-id' that saves the #id of the DOM element that has the simpleCart_shelfItem class:

``` html

<div class="simpleCart_shelfItem" id="item-432" >
  <h2 class="item_name">Cool Thing</h2>
  <a class="item_add" href="javascript:;">Add to Favorites</a>
  <input type="hidden" class="item_item-el-id" value="item-432" />
  <div style="display:none;" class="saved">Saved!</div>
</div>

```

You could then do something like this:

``` javascript


simpleCart.ready(function(){

  // iterate through all items, and show the saved button for it
  simpleCart.each( function( item ){

    // get the shelf item and hide/show its children
    $("#" + item['item_el_id'] ).find(".item_add").hide();
    $("#" + item['item_el_id'] ).find(".saved").show();

  });
});

```

**Comment by ggeiger** [comment]
Thanks for the great response. I like the concept of .each() going through each item looking for an ID. Unfortunately I can't get it to work, and I'm not sure what I'm missing. If I provide a link to my work, perhaps it would help reveal the issue.

I have the console echoing out the item ID, and it returns #item-undefined. The item does get passed to the cart.

http://ssilver.com.s113974.gridserver.com/product/chinoiserie-chest/

Thanks!

**Comment by brettwejrowski** [comment]
Sorry for the confusion, I didn't realize you were using version 3! Thanks for using it by the way.  Same idea, but instead use this: 

``` javascript

simpleCart.ready(function(){

  // iterate through all items, and show the saved button for it
  simpleCart.each( function( item ){

    // get the shelf item and hide/show its children
    $("#" + item.get('item_el_id') ).find(".item_add").hide();
    $("#" + item.get('item_el_id') ).find(".saved").show();

  });
});

```

**Comment by ggeiger** [comment]
Thanks for that!

I needed this to work the moment the user clicks the item_add button. This is the working script I ended up with:

```
simpleCart.bind( 'afterAdd' , function(){ 

    // iterate through all items, and show the saved button for it
    simpleCart.each( function( item ){

        // get the shelf item and hide/show its children

        $("#" + item.get('item-id') ).find(".item_add").hide();
        $("#" + item.get('item-id') ).find(".saved").show();

    });
});
```

And this is the HTML:

```
<div id="item-<?php echo $id; ?>" class="product-buttons">
    <a class="save button item_add" href="javascript:;">Save This</a>
    <input type="hidden" class="item_item-id" value="item-<?php echo $id; ?>" />
    <span class="saved">Item Added</span>
</div>
```

**Comment by ggeiger** [comment]
And now...!

I'd love to be able to iterate through the items again after I REMOVE the item from the cart. I realize there is no .afterRemove() callback (too bad!)

Using the add example above, how can I ask simpleCart.each to look for the item-id after the .simpleCart_remove button is clicked?

**Comment by joanneee** [comment]
Hi, I would like to do the same 
(each item can only be added ONCE to cart, 
when attempting to add an existing item in cart, an error message is displayed)

But not use php. Is that possible? I'm intending to implement it on a site that doesn't support php....

I can't figure out how to code the javascript and HTML to implement the "item id"(in HTML) and retrieve the "item id"(javascript function) to check if it exists in the cart already, assuming that the "item id" is generated with every item added to cart.
- using v2.2.2

Any assistance is greatly appreciated! :)
Related issue:
https://github.com/wojodesign/simplecart-js/issues/147

This one doesn't work for me - when i add 4 different items to cart, and move to checkout page, it only shows i have 3 in cart.
http://stackoverflow.com/questions/8167675/simplecartjs-quantity-limit

**Comment by brettwejrowski** [comment]
hey @ggeiger I have added an event called "beforeRemove" in v3 that will fire right before an item is removed from the cart.  You can use it like this:

``` javascript

simpleCart.bind( 'beforeRemove' , function( item ){
  // do something with the item
  console.log( "Item '" + item.id() + "' has been removed from the cart" );
});

```

**Comment by brettwejrowski** [comment]
@joanneee your question is different from this issue. For your problem, you can use the beforeAdd event:

``` javascript

simpleCart.bind( 'beforeAdd' , function( item ){
  // return false if the item is in the cart, 
  // so it won't be added again
  return !simpleCart.hasItem( item );
});

```

I also posted this answer on the stackoverflow issue
