### ISSUE TITLE
Adding Second Custom Option

### ISSUE THREAD

**Issue by catsniffer** [wojodesign/simplecart-js#216]
Hullo, great script! Really useful. 

I'm getting to grips with it but in addition to the first "Custom" option, I'd like to add a second custom option as a blank text box the customer can fill.

So you have a rough idea. 1st box is for size (s, m, l). 2nd box would be for the name of the customer. Both then showing up on the PayPal invoice so I know.

Thanks so much for any help!

**Comment by ovg** [comment]
I'd be interested in this too if anyone can help? =)

**Comment by brettwejrowski** [comment]
You can add any number of custom values on an item; it is not just one attribute named "Custom." You can set as many custom values as you would like.

**Comment by catsniffer** [comment]
Hullo and thanks for your reply! I see I can add as many fields as I'd like, but only one custom field will be sent to PayPal. Therefore on the invoice only one variable will show up at checkout in PalPal.

Thanks!
