### ISSUE TITLE
Steps to get a event everytime a item from the cart is removed

### ISSUE THREAD

**Issue by shaustre** [wojodesign/simplecart-js#218]
check the steps here, i hope this helps everybody
http://www.eyegowide.net/?p=954

**Comment by brettwejrowski** [comment]
Thanks @shaustre.  However, I would be careful with that method, as a custom cart format could have multiple links, such as increment/decrement links. Also, an item could be removed programmatically or by changing the quantity via a text input in the cart... I will try to add an event inside the code.  In the mean time I would take a look at the item.remove function and tie into that.

**Comment by brettwejrowski** [comment]
hey @shaustre in the latest commit of v3, I added an event called 'beforeRemove' that will be fired every time an item is removed from the cart.  You can use it like this:

``` javascript

simpleCart.bind( 'beforeRemove' , function( item ){
  // do something with the item
  console.log( "Item '" + item.id() + "' has been removed from the cart" );
});

```
