### ISSUE TITLE
cart isn't carrying more than 18 products between pages.

### ISSUE THREAD

**Issue by peersyichi** [wojodesign/simplecart-js#219]
I have a cart set up between multiple pages with items on each page. my issue is that when more than a specific amount of items are in the cart it will not save any more items afterwards. i'm not certain if this is an issue with a conflict with another jquery file or that the cookies are becoming too large. i'm wondering if anyone else has had this problem and really hoping there is a solution.

I'm working with version 2.2 and on a deadline so updating to version 3 isn't really an option at the moment.

sorry i can't really give any source files and i wouldn't be certain what to post.

just to be a little clearer, i havn't got an issue with quantity of each item. its the ammount of seperate products in my cart is the issue. 

hope someone can help me, thank you

peersyichi

**Comment by peersyichi** [comment]
any possible reasons would be welcome. I've explored the possible jQuery conflicts and it doesn't seem to be the reason. i'm thinking it might be an issue with cookies. tried editing the MAX.COOKIE from 4000 to a higher number and doesn't seem to have any effect. i'm now completely clueless on what might be the issue and am having a huge problem implementing simplecart.js v3 as it has large conflicts with some of the jquery scripts i've used with-in the website so isn't working. really need help so any recommendations would be greatly appreciated

**Comment by peersyichi** [comment]
just a little more information because i could really do with some sort of answer, in local tests in chrome the cart gets emptied between pages. in firefox, ie and safari's local test it does let 18 items through to the next page.

i am using jQuery and email checkout on html pages.

tested deleting all js scirpts apart from jquery source and simplecart.js and still have same problem. the only thing i've edited is the simplecart.js was the email.checkout area

help

**Comment by peersyichi** [comment]
have just tested putting 30 products using the original test files supplied on the simplecart website and it actually has the same issue so amazed this doesn't seem to be a common problem. If you add a specific ammount or more on one page using the jquery page and link to another page with the cart on, you loose the last two products on you list. seems to be a cap on how many seperate products you can put in so now thinking this has to be a cookie size issue.

hope someone knows at least what the problem is so i know what to try to tackle

**Comment by peersyichi** [comment]
anyone got any idea, it really does seem to be an issue with the way the cart works rather than something I have done myself. either someone has realised this happening or i'm completely lost my mind. would be nice to get any response to this. 

cheers

**Comment by igorsk** [comment]
I have the same problem. When refreshing the page (or moving to page with cart list) its only 6 items in the cart list. Checked cookies of site and every time it have ~4000 symbols. So i can't add more than 6 items. Can anybody help with this?
Thanks

**Comment by brettwejrowski** [comment]
This problem should be fixed with the chunking of data to stay under the max cookie size.  Try changing the MAX_COOKIE_SIZE to a lower number and see if that helps.  I will investigate a little more in the mean time.

**Comment by brettwejrowski** [comment]
Okay guys I have integrated the v3 storage code into the master branch as v2.2.3.  This means that the master no longer uses cookies, and you should be able to avoid the length limitations.  I left in the 2.2.2 code incase you want to switch back to using cookies, but try it out.

I created a test that added 100 items to the cart and it seems to load okay in safari.  Let me know if you run across any issues.

**Comment by dalagupa** [comment]
Hello brettwejrowski , i need your help please. How did you solve this problem ?

"Okay guys I have integrated the v3 storage code into the master branch as v2.2.3. This means that the master no longer uses cookies, and you should be able to avoid the length limitations. I left in the 2.2.2 code incase you want to switch back to using cookies, but try it out"

Coz i cannot find the solution. Please, help
