### ISSUE TITLE
updating v2.2 to have html5 local storage

### ISSUE THREAD

**Issue by peersyichi** [wojodesign/simplecart-js#222]
wandering if this is possible as it would save me a great deal of time. the storage system for version 3 is greatly enhanced from the previous versions but the new version has ended up conflicting with everything i've done so far so to be able just to update this one area would be amazing. 

any recommendations appreciated

Thank you 

Peersyichi

**Comment by brettwejrowski** [comment]
I can take a look at this to see how difficult it would be. It might be a good option as people are having some issues with the old storage code and there are a lot of existing v2 sites out there. Thanks for the input!

**Comment by brettwejrowski** [comment]
hey @peersyichi I have integrated the v3 localStorage methods into v2 as 2.2.3.  You can get the code from the master branch, let me know if it helps!

**Comment by peersyichi** [comment]
thank you, you've helped me more than i could of hoped. worked on a project using that version of simplecart for a long time now and was distressed at having to change everything (don't think i could of managed it)

You're a legend mate

Peersyichi
