### ISSUE TITLE
Chrome Not Remebering Cart Contents

### ISSUE THREAD

**Issue by advancedsoftwarecanada** [wojodesign/simplecart-js#228]
There are 2 previous discussions, which were not investigated and closed. 

Google Chrome is having an issue remembering cart contents on new pages. I'm not the only one having this issue, so please don't dismiss it!

Other browsers work great.

URL:    https://www.4magazinesfor40dollars.com/

**Comment by advancedsoftwarecanada** [comment]
It appears as though Chrome does not store LOCAL cookies - has to be uploaded to a server. It is now, but still won't work.

**Comment by advancedsoftwarecanada** [comment]
I have solved the problem with the following code, and by using the Jquery cookie plugin. Lord knows why.

```
// OLD COOKIE MAKER
//document.cookie = name + "=" + escape(value) + expires + "; path=/;"; 

// NEW COOKIE MAKER
$.cookie(name, value, { path: '/', domain: 'website.com', expires:7});
```

**Comment by brettwejrowski** [comment]
Hey @Solacex thanks for bringing this up.  I believe the previous threads were closed because it was thought to be the local cookie issue.  The cookie code used is from PPK, and it should work across all browsers.  However, it is relatively old and there might be some newer issues that have arisen with new browsers.

v3 uses a storage library that avoids cookies, so you may want to try that.  

Did you get js errors when using that cookie code?

**Comment by advancedsoftwarecanada** [comment]
I thought I was using V3, I'll check it out and reply back here. Thanks for the information, I appreciate it.

**Comment by advancedsoftwarecanada** [comment]
I thought I was using V3, I'll check it out and reply back here. Thanks for the information, I appreciate it.

Edit 1: It doesn't appear that a version number is kept within the .js - how am I to know which version I'm using. I believe I'm using the code posted 2 months ago from today.

**Comment by brettwejrowski** [comment]
v2 has a version number at the top, v3 is still in dev and does not.  However, v3 does not use any cookies, so you must be on v2.  Look around line 35 for something like this:

``` javascript

    me.Version = '2.2.2';

```

**Comment by brettwejrowski** [comment]
Hey @Solacex I have integrated the v3 storage into v2 as 2.2.3.  It is currently in the master, please try it out and see if it fixes your problems.

**Comment by advancedsoftwarecanada** [comment]
How very nice of you. I'll try it out now. This is the site it's running on, by the way:

www.4Magazinesfor40Dollars.com

**Comment by advancedsoftwarecanada** [comment]
Changes start at line 420? I've got some other stuff I changed in there, don't wanna just copy/paste. Am I missing anything?

**Comment by brettwejrowski** [comment]
Just change the save and load functions, and remember to add the extra code in bottom of the page for JSON and localStorage polyfills
