### ISSUE TITLE
Successful checkout event

### ISSUE THREAD

**Issue by bongoyozo** [wojodesign/simplecart-js#229]
I see that in v3 there's an event called checkoutSuccess, that I believe should be triggered when customer makes successful payement, right? Tho, I don't see it being triggered anyway in the code.

After payment, I want to add to database customer's user name, email, generate his license, and then e-mail login to him for the customer area.

What's the procedure to do these things in v3?
Thank you!

**Comment by brettwejrowski** [comment]
That is the idea for that event, but it hasn't been implemented yet for a couple reasons.  That event heavily depends on the checkout method, and how the process is setup. I haven't figured out a great way to implement it for all users, but I have been able to do it in the past with v2 actually.  

What checkout method are you using?

**Comment by bongoyozo** [comment]
Oh, I see...
I'm using paypal.

**Comment by brettwejrowski** [comment]
Essentially, what you have to do is set the return success page, and then on load see if you are on that page. If you are, make sure the person was sent from paypal, and then you know that the checkout has completed.

**Comment by greatkingrat** [comment]
Although while you know that a checkout has completed, you still don't know the details of that transaction (i.e. customer's name, email address, address, etc.) - is that correct? Or does PayPal send that information across to the success page?

**Comment by brettwejrowski** [comment]
PayPal can send that info with as GET params, but I believe you have to set up some settings in the PayPal admin

**Comment by adelphiaUK** [comment]
I'm having an issue with PayPal returning to the success page.  It doesn't appear to be doing anything (I am only testing in sandbox mode right now). I am adding simpleCart.success = "checkoutsuccess.php" but it doesn't appear to be doing anything except giving me the default "Your order has been placed" in PayPal itself.  Not sure what I'm missing!

**Comment by brettwejrowski** [comment]
Do you have an example page I can take a look at?

**Comment by adelphiaUK** [comment]
Thanks for responding. You can take a look at my site, http://www.consolesxtreme.co.uk/xbox360.php but please be aware that this is LIVE. Is there a way I can setup a test page for it to use sandbox whilst still keeping it the site live?

**Comment by brettwejrowski** [comment]
Not sure if our docs are out of date, but try setting simpleCart.successUrl instead of simpleCart.success

**Comment by adelphiaUK** [comment]
OK, I tried this and it still doesn't work.  It still takes me to the standard "Your payment has been successfull" PayPal page.  I currently have the site running under a sandbox so you can test and let me know what I'm doing wrong.

**Comment by adelphiaUK** [comment]
OK. I think I may have found the problem.  I think its the settings in PayPal auto return feature.  I'm going to check it out now and will let you know the outcome.

**Comment by adelphiaUK** [comment]
OK. That's sorted it although I don't think your "successURL" has any effect anymore as you have to configure the return page within the profile of the account in PayPal.

**Comment by adelphiaUK** [comment]
OK. Fully sorted now.  I was putting successURL instead os successUrl (I added an alert to your js file to see if it was getting the success page and it wasn't.).  One other thing, it looks like the success/cancel page has to be a full URL, not just a page from within your site, or, if you use sandbox, it tries to get the page from the paypal sandbox site.  Anyway, all sort now thanks.
