### ISSUE TITLE
simpleCart.shippingFlatRate & simpleCrt.shippingCost should use shipping_1

### ISSUE THREAD

**Issue by richtestani** [wojodesign/simplecart-js#23]
Using this variable on an upload cart, this will be applied to the cart as Shipping & Handling below the total instead as a line item. The line items are nice if you have a per item shipping function, but for a total, it should be listed under the total.

<a href="http://img25.imageshack.us/i/screenshot20091020at120x.png/" target="_blank"><img src="http://img25.imageshack.us/img25/8894/screenshot20091020at120x.th.png" border="0"  /></a>

**Comment by wojodesign** [comment]
Fixed in 2.2.dev
