### ISSUE TITLE
Empty product stored in cookie

### ISSUE THREAD

**Issue by skyhirider** [wojodesign/simplecart-js#231]
Using Simplecart 2.2.

When I load the store page the first time, the cart is empty. If I don't add anything to the cart and reload the page the cart has ONE item in it with zero price and zero quantity.

I've tried looking at the code but couldn't figure it out.

The site is: http://194.1.130.117/web2.0/brany/site/price.html

Reload it twice without ordering anything to see the bug in action. An empty item gets stored in the cookie.

**Comment by brettwejrowski** [comment]
Yep this looks to be an old bug in v2.2, I would suggest upgrading to at least 2.2.2

**Comment by skyhirider** [comment]
Thanks, that solved the issue. Could you update the 2.2 Zip download file to version 2.2.2, so that others download the latest and do not run into similar issues?

**Comment by brettwejrowski** [comment]
no problem, its up there
