### ISSUE TITLE
show prices including tax

### ISSUE THREAD

**Issue by swfredrik** [wojodesign/simplecart-js#234]
I want to show item_price including tax in the simpleCart_shelfItem

Then in my cart I need some new variables like:

simpleCart_total_without_tax
simpleCart_grandTotal_without_tax

An example with tax_rate= 0.25:
 item_price = 1000
simpleCart_tax = 200
simpleCart_grandTotal = 1000

**Comment by brettwejrowski** [comment]
what version are you using?

**Comment by swfredrik** [comment]
V3 latest

3 maj 2012 kl. 06:46 skrev brettwejrowskireply@reply.github.com:

**Comment by brettwejrowski** [comment]
Awesome! You can bind your own custom outputs like this:

``` javascript

// run on .ready() so we make sure simpleCart is ready:
simpleCart.ready(function(){

  simpleCart.bindOutlets({
    // create selector that goes after the "simpleCart_"
    "grandTotal_without_tax": {
      callback: function () {
        // return currency formatted grand total - tax
        return simpleCart.toCurrency( simpleCart.grandTotal() - simpleCart.tax() );
      }
    }
  });

});

```

**Comment by brettwejrowski** [comment]
actually @swfredrik I just just updated the latest v3 to remove the 'callback' keyword for simplicity, so you would instead use:

``` javascript

simpleCart.ready(function(){

  simpleCart.bindOutlets({
    // create selector that goes after the "simpleCart_"
    "grandTotal_without_tax": function () {
      // return currency formatted grand total - tax
      return simpleCart.toCurrency( simpleCart.grandTotal() - simpleCart.tax() );
    }
  });

});


```

**Comment by swfredrik** [comment]
Thanks a bunch!! Really simple and flexible shoppingcart, I really love it :)
