### ISSUE TITLE
'Add to cart' always adds 1 item to cart regardless of number entered into the item quantity field

### ISSUE THREAD

**Issue by aarronc** [wojodesign/simplecart-js#236]
Ive tried the test page to see if this would work for me but i need to work with a large number of items '5000 screws' or '4321 s hooks' ive tried to change the value in the field from 1 to 5000 and them press add to cart but all i get it 1 item added t othe cart at the price stated. is there a way i can get it to add more than 1 item at a time

thanks

Aarronc

**Comment by brettwejrowski** [comment]
Could you send a link to your page? You should be able to add any number you want at a time.

**Comment by aarronc** [comment]
i have been using the test page included to try out the different features and played around with that to try and get the features i was looking for before i rolled it out to a custom page of my own, in the wojodesign-simplecart-js-10c266a.zip i have been using the index.html in a folder called test

**Comment by brettwejrowski** [comment]
hey @aarronc thanks for bringing this to my attention, I fixed the bug and updated the master branch.  You can download again you shouldn't have any issues.
