### ISSUE TITLE
How to customize the cart?

### ISSUE THREAD

**Issue by edwincwh** [wojodesign/simplecart-js#237]
i had try the code in the Cart formatting> styling cart..
but it seem cannot work.. 

can i put the header and item container into table form? (due to the align problem..) 
when the name diff length then the column will run..

eg:
FF01     Rm10     -     1     +     Remove     RM10
B01     Rm12     -     1     +     Remove     RM12
Egg Roll Salad     RM8     -     1     +     Remove     RM8

the column are nt tat organize..

Second is how to change the + sign to a image form???

Thanks and regards.

**Comment by brettwejrowski** [comment]
What version are you using?

**Comment by edwincwh** [comment]
simpleCart2.2

**Comment by brettwejrowski** [comment]
Please search through the issues, there are several examples of how to style the cart.  You should also consider upgrading to 2.2.2, 2.2.3, or 3.0
