### ISSUE TITLE
beforeAdd event triggered in every page refresh

### ISSUE THREAD

**Issue by swfredrik** [wojodesign/simplecart-js#238]
I've bound beforeAdd event to simplecart to update the price if a product with model1 is added. This works perfect. The problem is that this code executes during every page request after that. So the price escalates..

```
simpleCart.bind('beforeAdd', function (item) {
    if (item.get('model') === 'Model1') {
        item.set("price", item.get('price') + 304);
    }
});
```

**Comment by swfredrik** [comment]
Ohh I must have lost my head there for a moment I could set the new price direct without adding + 304. But I still believe it's not right that the function gets called on every refresh.

**Comment by brettwejrowski** [comment]
Yeah @swfredrik you are right, in the next update I will make sure it does not get called when loading.  If you need to differentiate in the meantime, you can check the simpleCart.isReady variable:

``` javascript
simpleCart.bind( 'beforeAdd' , function(){

  if( simpleCart.isReady ){
    // this is when an item is normally added to the cart
  } else {
    // this is when an item is added during load
  }
});

```

**Comment by brettwejrowski** [comment]
@swfredrik this is now fixed, please download the latest and you should be all set.
