### ISSUE TITLE
taxShipping not applied

### ISSUE THREAD

**Issue by swfredrik** [wojodesign/simplecart-js#239]
```
Setting the shipping and tax as follow: 
```

// flat rate shipping option
        shippingFlatRate: 24,

```
    // added shipping based on this value multiplied by the cart quantity
    shippingQuantityRate: 0,

    // added shipping based on this value multiplied by the cart subtotal
    shippingTotalRate: 0,

    // tax rate applied to cart subtotal
    taxRate: 0.25,

    // true if tax should be applied to shipping
    taxShipping: true,
```

simpleCart_shipping will give me 24
simpleCart_grandTotal will give me 24, I believe the tax should apply to the grandTotal so the grandTotal would be 30. 

setting the taxShipping true or false does no effect.

**Comment by brettwejrowski** [comment]
@swfredrik thanks for bringing this up, I'll make sure it is being applied correctly in the next patch (I should actually get to this and your other issue today)

**Comment by brettwejrowski** [comment]
hey @swfredrik I just fixed this and merged to master, you should be all set now.

**Comment by swfredrik** [comment]
Hi, Great thanks! Really nice! Thanks a bunch!!
