### ISSUE TITLE
email checkout ETA?

### ISSUE THREAD

**Issue by ghost** [wojodesign/simplecart-js#24]
Interested to know what the ETA would be on the Email Checkout option?

**Comment by ghost** [comment]
The thewojogroup said 26 days ago, but after my reply still nothing?

How do I use SimpleCart with ZAR(South Africa) and email checkout?
Does anyone have any demos, scripts or even ideas?

Any help appreciated.

**Comment by richardlawrence88008** [comment]
I need to do likewise (email only checkout)

**Comment by richardlawrence88008** [comment]
Actually, its all here http://github.com/thewojogroup/simplecart-js/tree/email
