### ISSUE TITLE
V3 - error management is not work!

### ISSUE THREAD

**Issue by dodysugianto** [wojodesign/simplecart-js#241]
I use v3. Please tell me how use alert ?

<div class="highlight"><pre>
me.checkout = function() {
        if( me.quantity === 0 ){
            <span class="s2">error("Cart is empty");</span>
            return;
        }
</pre></div>

and almost all of the command error ("......."); does not work in v3.
i want to show alert alert after add item into cart.
and show alert alert after checkout if quantity=0.

**Comment by brettwejrowski** [comment]
the error outputs to console, open up dev tools in safari or chrome or firebug in firefox.
