### ISSUE TITLE
SimpleCart adding form input validation to email checkout submit

### ISSUE THREAD

**Issue by dodysugianto** [wojodesign/simplecart-js#242]
I  add new checkout method to simplecartjs:

<div class="highlight"><pre>
me.emailCheckout = function() {    
    itemsString = "";
    for( var current in me.items ){ 
        var item = me.items[current];
        itemsString += item.name + " " + item.quantity + " " + item.price + "\n";
    }   
    var form = document.createElement("form");
    form.style.display = "none";
    form.method = "POST";
    form.action = "sendjs.php";
    form.acceptCharset = "utf-8";
    form.appendChild(me.createHiddenElement("jcitems", itemsString));
    form.appendChild(me.createHiddenElement("jctotal", me.total));
    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
}
</pre></div>

This will create new form element and submit cart data to sendjs.php. 
create a new sendjs.php file:

```
      <?php
                $to      = 'you@example.com';
                $subject = 'the subject';
                $jcitems = $_POST['jcitems'];
                $headers = 'From: webmaster@example.com' . "\r\n" .
                        'Reply-To: webmaster@example.com' . "\r\n" .
                        'X-Mailer: PHP/' . phpversion();
               mail($to, $subject, $jcitems, $headers);
               Header('Location: thankyou.html');
     ?>
```

How do I create "sendjs" on the blogspot page ??

**Comment by brettwejrowski** [comment]
Seems like this is a question for blogspot, not specifically about simpleCart(js)?

**Comment by dodysugianto** [comment]
Thank you so much..
to the creator SimpleCart(js) that inspired so many people make SimpleCart(js) can be used to shop online.

yeah brettwejrowski you're right, slightly deviates from the others. thank you for replying.
but I use SimpleCart(js) in blogspot. see: http://javatemplates.com/2011/blogger-store-v2/view/

Here I don't use paypal to checkout, allows customers to send the cost of shopping through the bank.
how do I create "sendjs.php" as above to "sendjs.html", while the php file can not be created on blogspot.
such as creating form input validation on the blogspot page for shopping list to send email?

I'm sure you can help me.
