### ISSUE TITLE
HTML Classes

### ISSUE THREAD

**Issue by m477r33d** [wojodesign/simplecart-js#245]
Hello, can you please update/add documentation for native HTML classes?

For example:
"http://simplecartjs.org/features/" shows that a class of "simpleCart_finalTotal" should display total of the cart after tax & shipping, but it seems that "simpleCart_grandTotal" does this.  Likewise "simpleCart_taxCost" should show taxRate X total displayed as currency, but it seems that "simpleCart_tax" does this. 

Is there a definite list of HTML classes? (this native functionality is preferred to using custom JS). 

Thanks!
Matt

**Comment by brettwejrowski** [comment]
Thanks Matt, I updated the classes on the features page.  I will add a page to the documentation that will have a full list of the outputs.

**Comment by m477r33d** [comment]
Thanks for the quick update, Brett. Looking forward to seeing a page on this - will be most helpful.

**Comment by brettwejrowski** [comment]
hey Matt, it took me longer than I would've liked to get around to it, but: http://simplecartjs.org/documentation/displaying_cart_data

Thanks!
