### ISSUE TITLE
Tax Rate & Shipping to PayPal

### ISSUE THREAD

**Issue by m477r33d** [wojodesign/simplecart-js#246]
The tax rate and shipping (even though working correctly on my site) do not seem to be passed to PayPal on checkout - only the items and subtotal are visible.

**Comment by m477r33d** [comment]
I used Live HTTP Headers to smoke out what I believe is the cause - the variables (tax_cart and handling_cart) are being passed, but they are not being rounded to two decimal places, and so PayPal must choose to ignore them. I've added this sort of code to resolve (simpleCart.js about line 924):

, tax_cart      : ( Math.round( simpleCart.tax()_100 ) /100 )
, handling_cart     : ( Math.round( simpleCart.shipping()_100 ) /100 )

**Comment by brettwejrowski** [comment]
Thanks @m477r33d I will add this fix into the dev branch

**Comment by brettwejrowski** [comment]
I added tests and fixed the error in the dev branch: [17333ba3](https://github.com/wojodesign/simplecart-js/commit/17333ba3a58bfcc718e7d14dfd7f7b7b836531d4)
