### ISSUE TITLE
selectors dont work with MooTools latest(mootools-core-1.4.5)

### ISSUE THREAD

**Issue by pellucide** [wojodesign/simplecart-js#249]
Thanks for the awesome simpleCart. I have been trying to integrate simpleCart  to enable online ordering. The issue I am facing is selectors don't work with mootools-core-1.4.5. They work nicely with jQuery.  I could change to jQuery, but that entails a lot of work that has been already done with MooTools.  Also I like mootools style of javascript coding . Here is a simple piece of code that shows the problem. In this code the selectors are

.simpleCart_increment
.simpleCart_decrement
.simpleCart_shelfItem  .add_item

I would appreciate some help on this 
Thanks

<pre>

&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
 &lt;title&gt;simpleCart(js) - Test&lt;/title&gt;
 &lt;link href=&quot;test.css&quot; rel=&quot;stylesheet&quot; media=&quot;screen&quot; type=&quot;text/css&quot; /&gt;
&lt;/head&gt;

&lt;body&gt;
   &lt;div class=&quot;itemsview&quot; id=&quot;shelf&quot;&gt;
      &lt;div class=&quot;simpleCart_shelfItem&quot;&gt;
         &lt;h2 class=&quot;item_name&quot;&gt;Item1&lt;/h2&gt;
         &lt;select class=&quot;item_choice&quot;&gt;
             &lt;option value=&quot;choice1&quot;&gt;Choice1&lt;/option&gt;
             &lt;option value=&quot;choice2&quot;&gt;Choice2&lt;/option&gt;
         &lt;/select&gt;
         &lt;input type=&quot;text&quot; value=&quot;1&quot; class=&quot;item_Quantity&quot;&gt;
         &lt;span class=&quot;item_price&quot;&gt;$2.00&lt;/span&gt;&lt;br&gt;
         &lt;a class=&quot;item_add&quot; href=&quot;javascript:;&quot;&gt; Add to Cart &lt;/a&gt;
      &lt;/div&gt;
   &lt;/div&gt;

   &lt;div class=&quot;cartview&quot; id=&quot;cart&quot;&gt;
      &lt;span class=&quot;simpleCart_quantity&quot;&gt;&lt;/span&gt; items &lt;br&gt;
      total - &lt;span class=&quot;simpleCart_total&quot;&gt;&lt;/span&gt; &lt;br&gt;
        tax - &lt;span class=&quot;simpleCart_tax&quot;&gt;&lt;/span&gt; &lt;br&gt;
      grandTotal - &lt;span class=&quot;simpleCart_grandTotal&quot;&gt;&lt;/span&gt;
      &lt;h2 class=&quot;&quot;&gt; Cart Items &lt;/h2&gt;
      &lt;div class=&quot;simpleCart_items&quot;&gt;&lt;/div&gt;&lt;br&gt;
         &lt;div class=&quot;checkoutEmptyLinks&quot;&gt;
         &lt;a href=&quot;javascript:;&quot; class=&quot;simpleCart_empty&quot;&gt;empty cart&lt;/a&gt;
         &lt;a href=&quot;javascript:;&quot; class=&quot;simpleCart_checkout&quot;&gt;Checkout&lt;/a&gt;
      &lt;/div&gt;
   &lt;/div&gt;
   &lt;br&gt;
   &lt;br&gt;

   &lt;script type=&quot;text/javascript&quot;  src=&quot;http://mootools.net/download/get/mootools-core-1.4.5-full-nocompat.js&quot;&gt;&lt;/script&gt;
   &lt;!--
   &lt;script type=&quot;text/javascript&quot;  src=&quot;http://mootools.net/download/get/mootools-core-1.4.5-full-compat.js&quot;&gt;&lt;/script&gt;
   &lt;script  type=&quot;text/javascript&quot; src=&quot;jquery.js&quot;&gt;&lt;/script&gt;
   --&gt;

   &lt;script type=&quot;text/javascript&quot;  src=&quot;simpleCart.js&quot;&gt;&lt;/script&gt;
   &lt;script type=&quot;text/javascript&quot; &gt;
       simpleCart({
           checkout: {
               type: &quot;PayPal&quot; ,
               email: &quot;you@yours.com&quot;,
           },
           taxRate:0.075,
           currency:&#39;USD&#39;,
           cartStyle:&#39;table&#39;,

       });

   &lt;/script&gt;&lt;/body&gt;&lt;/html&gt;

</pre>

**Comment by brettwejrowski** [comment]
hey @pellucide thanks for posting the issue,  I will add some tests and try to figure out why it isn't working.  (we run our tests against the 3 latest major release of mootools).

**Comment by brettwejrowski** [comment]
hi @pellucide I have fixed this issue in the dev branch with [c1a033d](https://github.com/wojodesign/simplecart-js/commit/c1a033de60ee1e68807ae9cf80a2b215c5d031c1)

let me know if you have any other issues. thanks!

**Comment by pellucide** [comment]
That was unexpectedly quick. Thanks a lot

**Comment by pellucide** [comment]
I was going through the fix. I am a newbie with javascript. what does the **":relay(" + selector + ")"** do ? Its in the file simpleCart.js

**Comment by brettwejrowski** [comment]
Ah, yes. I actually had to look this one up (I am much better with jQuery).  Basically, you can delegate event listeners to a containing element.  

So lets say I have a table with a 100 rows that I am removing and adding, and I want to know when a row is clicked, it would be crazy to attach an event listener to every row added and then remember to remove it.  

Instead, I can attach an event to the table and say "tell me whenever a row inside of you gets clicked," because the event will "bubble up" the DOM. This way, I can tell when any row is clicked with a single listener. The code would look like this:

``` javascript

document.id( "myTable" ).addEvent( 'click:relay(tr)' , function( e ) {
  console.log( "A table row was clicked!");
));

```

The "click:relay( selector )" tells mootools to watch for a click event on any of its children that match the selector.

I use this method with simpleCart(js) so that I don't have to attach and remove click events to elements every time the page is updated.  I just add the listener to the body, and you can change the entire DOM without simpleCart(js) knowing, and it will still "catch" the click events.  This method of using the body or document as the delegate is similar to jQuery's .live() method.

**Comment by pellucide** [comment]
This is pretty sweet. Thanks. I am starting to like java-script more than java. Its a very powerful language.
