### ISSUE TITLE
Demo not working - Checkout button not working

### ISSUE THREAD

**Issue by nbaosullivan** [wojodesign/simplecart-js#25]
After uploading a clean download of simpleCart along with the example included to subsplash.co.uk/shop/ the checkout button seems to be completely unresponsive?!

Any ideas?

**Comment by honzzz** [comment]
I have the same problem with last simpleCart.js - the one that I downloaded from http://simplecartjs.com - Simplecart 2.0

I noticed that their demo seems to be working just fine so I tried to download impleCart.js used in that demo (which is different than the one @ homepage) and it seems to be OK. 

You can try to use it: http://demo.simplecartjs.com/javascripts/simpleCart.js
I am going to compare those two but I am no JavaScript guru.

**Comment by nbaosullivan** [comment]
Ah nice one, they should update that lol
