### ISSUE TITLE
Consider submitting simpleCart(js) to cdnJS?

### ISSUE THREAD

**Issue by marceltt** [wojodesign/simplecart-js#250]
simpleCart(js) would be right at home on cdn.js so I think you should consider including it there so it's a lot more easier to get up and running with it.

https://github.com/cdnjs/cdnjs

**Comment by brettwejrowski** [comment]
Thanks for the idea! I will submit it as soon as I finish up testing 3.0.5 (hopefully sometime tonight)

**Comment by brettwejrowski** [comment]
Thanks @MarceI, I just submitted my pull request for simpleCart(js) 3.0.5 to be added.
