### ISSUE TITLE
Edit Look of Cart

### ISSUE THREAD

**Issue by Swaartbaard** [wojodesign/simplecart-js#258]
Hi

Can i change the look of the cart at all? When I use the following code it bunches all the text together.

```
!<div class="simpleCart_items"></div>
```

Is there a way to space it out at all and make it look a bit more pro?

Also can i change the text to Arial instead of times new roman?

Thank you in advance

**Comment by iamstevemckinney** [comment]
You'll need to use CSS. simpleCart(js) only provides the functionality of the cart, not the look and feel.
