### ISSUE TITLE
IE limit on querystring with paypal checkout

### ISSUE THREAD

**Issue by altdesign** [wojodesign/simplecart-js#26]
I see that when you press "checkout" button the cart is converted in a querystring and it open a new window with a long url.
If a user buy a lot of items this url can be extremely long. Does this can be a problem for IE?
As far as I know there is a limit on the query string on IE, about 2Kb or 4000 chars. No?

**Comment by altdesign** [comment]
why you haven't use the same approch of the GoogleCheckout method? (That create an hidden form and then submit via POST method)

**Comment by iamstevemckinney** [comment]
The paypal checkout uses a post with a form in the latest version. Thanks for the input!
