### ISSUE TITLE
'Unidentified Item Added to Cart'... Why?

### ISSUE THREAD

**Issue by Swaartbaard** [wojodesign/simplecart-js#262]
Hi,

I cant figure out why with the afteradd function it keeps saying 'Unidentified item added to cart'...

Any idea what im doing wrong?

http://www.sunshineinabottle.co.za/

**Comment by nlounello** [comment]
You have an alert statement in the afteradd obviously - what are you using to display the name of the item? I would think it would be  

alert(item.get('name') + "added to cart");

**Comment by Swaartbaards** [comment]
Hi,

Thank you for the reply.

I managed to get it work!  Thank you
