### ISSUE TITLE
Set the currency symbol after the price (V3)

### ISSUE THREAD

**Issue by FletcherPink** [wojodesign/simplecart-js#269]
Hello,
Congratulations for your work !
Is there a way to set the currency symbol (€) after the price (23 €) ?

Thanks a lot

**Comment by iamstevemckinney** [comment]
Yes there is, here's a link to the relevant documentation,
http://simplecartjs.org/documentation/currency

**Comment by FletcherPink** [comment]
Thanks for your answer ! I just found it !
;-)
