### ISSUE TITLE
For...in statement issue

### ISSUE THREAD

**Issue by altdesign** [wojodesign/simplecart-js#27]
I'm running on several javascript error on every loops that use that statement.
As suggested by JSLint this statement:
 for( header in me.cartHeaders ){
Problem at line 431 character 9: The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.

as an example.
Seems that, in my environement, there is an additional "$family" property in the array that breaks the javascript execution.
I resolved by changing all for..in loops in simple for loops, like:
for(var x=0, xlen=me.cartHeaders.length;x<xlen;x++){}

hope this help.

**Comment by wojodesign** [comment]
for...in issues resolved in 2.2
