### ISSUE TITLE
item_size option not being passed to PayPal.  Any help?! 

### ISSUE THREAD

**Issue by dschiffner** [wojodesign/simplecart-js#270]
I have used simplecart several times with no problems whatsoever, But I'm a bit confused with this one, because I haven't done anything different... that I can see.

Basically, I have shelf items with an included item_size option.  Everything gets passed onto paypal through checkout EXCEPT the size.  

Here's what I have:

``` html
        <div id="box1" class="boxes">
            <div class="simpleCart_shelfItem">
            <h2 class="item_name">Mens Tee</h2>
            <a id="single_image" href="i/male-full.jpg"><img class="itemimage" src="i/male-small.jpg" /></a>
             <select class="item_size">
                <option value="Extra Small"> Extra Small </option>
                <option value="Small"> Small </option>
                <option value="Medium"> Medium </option>
                <option value="Large"> Large </option>
                <option value="Extra Large"> Extra Large </option>
             </select>              
             <span class="item_price">$1.00</span>
             <a class="item_add button" href="javascript:;"> Add to Cart </a>
            </div>
        </div>
```

Am I missing something?

**Comment by dschiffner** [comment]
Just to update everyone, I seem to have figured this out on my own.  It was an issue with the version of the script.

I changed the script back to an older version I used on prior projects and now item_size is passed to PayPal with no issues....

**Comment by dellacroce** [comment]
is there a way to pass this item_size option to PayPal without going back to the previous version?

**Comment by AdamIsrael** [comment]
What version were you on, and what version did you revert to?
