### ISSUE TITLE
when trying to create item which includes also item_productID this does not post

### ISSUE THREAD

**Issue by labrouss** [wojodesign/simplecart-js#271]
i'm trying to create an item like that

``` html
<tr class='simpleCart_shelfItem simplecart'>
<td><a class='item_add' href='javascript:;'><h4 class='item_name btn btn-black'>Espresso</h4></td>
<td><input type='text' class='item_productID' value='1'></td>
<td><i class='icon-shopping-cart'></i></a></td>
<td><input value='1' class='item_Quantity' type='text'></td>
<td><colspan class='item_price'>€ 1.50</colspan></td>
</tr>
```

This posts the following array(9) { ["currency"]=> string(3) "EUR" ["shipping"]=> string(1) "0" ["tax"]=> string(1) "0" ["taxRate"]=> string(1) "0" ["itemCount"]=> string(1) "1" ["item_name_1"]=> string(8) "Espresso" ["item_quantity_1"]=> string(1) "1" ["item_price_1"]=> string(3) "1.5" ["item_options_1"]=> string(12) "productid: 1" }

item_productID gets into item_options variable. Does anyone have any idea how i could fix it so that i get an item_productID variable post ?

**Comment by labrouss** [comment]
I now can use php explode function to get all values from options variable. So problem is not a problem after all.

**Comment by killperucita** [comment]
Please can you write the code?
