### ISSUE TITLE
how good is the security?

### ISSUE THREAD

**Issue by DanielRuf** [wojodesign/simplecart-js#274]
are the prices the customer has to pay created from th html / javascript markup?
can not somebody manipulate the values using tools like firebug to "cheat"?

**Comment by brettwejrowski** [comment]
There are always going to be security concerns with client side issues.  Originally, this script was meant to be used on relatively small sites, where orders were handled by hand.  

However, we use it on several large scale sites where we add some server side checks for price before checking out as well.
