### ISSUE TITLE
The script does not work for me

### ISSUE THREAD

**Issue by MiguelOSX** [wojodesign/simplecart-js#28]
I simply uploaded the files in the. Zip to my server. But nothing else works, are only the letters and all white. It is possible css problem? Here is the demo: http://kedmacos.com/tienda

Sorry my english!

Bye!

**Comment by iamstevemckinney** [comment]
Your demo seems to work fine for me. There is no CSS with simpleCart(js) as it is not a theme or a design, but instead its a javascript shopping cart script. Its meant to be styled to fit your design as it was built to be very flexible in this way.
