### ISSUE TITLE
Limit cart to add only one of each item type

### ISSUE THREAD

**Issue by craigpearson** [wojodesign/simplecart-js#289]
Like another user I would like to restrict the cart to only allow one item of each type to my cart.

I have found this solution for my problem:

<pre>simpleCart.bind( 'beforeAdd' , function( item ){
  // return false if the item is in the cart, 
  // so it won't be added again
  return !simpleCart.hasItem( item );
});</pre>

However, I get the error <pre>Uncaught TypeError: Object function (a){if(h(a))return b.ready(a);if(i(a,"object"))return b.extend(k,a)} has no method 'hasItem' </pre>

Am I missing something here? :S

Thanks a million in advance

**Comment by SB3K** [comment]
Hi Craig, I found a way to do this. Not sure if it is correct, but it works.

On line 192 of simpleCart.js comment out the line 

oldItem.increment(newItem.quantity()); 

This will simply prevent the cart from adding another quantity of the same item. 

Cheers!

**Comment by rodrigoAbril** [comment]
Hi, what about limiting items of the same type, i.e. if I have 3 items of the type A, how do i toggle the cart item when the user selects another item of this type.

Thanks in advance

**Comment by petermanser** [comment]
This is very very late, but this is how you'd do it:

``` javascript
simpleCart.bind('beforeAdd', function(item){
    return !simpleCart.has(item);
});
```
