### ISSUE TITLE
Internet Explorer 6 and 7 localStorage issue.

### ISSUE THREAD

**Issue by prostoroman** [wojodesign/simplecart-js#293]
Hi, IE6 and IE7 return error be cause they have no localStorage support.

Do you know how to fix it?

**Comment by dmnkhhn** [comment]
Well, you could use https://github.com/wojodesign/local-storage-js as an alternative when localStorage isn't supported.

Both libraries are by the same author. I don't think he will integrate it into simpleCart but he might provide some help on combining them.

**Comment by prostoroman** [comment]
Thank's for response, I'll already resolve this issue for myself.
I just use cookies when LocalStorage is no supported.
