### ISSUE TITLE
currency grand total bug

### ISSUE THREAD

**Issue by lozz3r** [wojodesign/simplecart-js#299]
Added currency as:

simpleCart.currency({
            code: "XXX" ,
            name: "Netherlands" ,
            symbol: "€ ",
            delimiter: "." , 
            decimal: "," , 
            after: false ,
            accuracy: 2
        });

The cart total was displaying an amount of 4,99 (i.e. a decimal value of 4.99) as 499,00 (i.e. a decimal value of 499.00). This is obviously incorrect.

To fix, I changed the price function as below, but not sure if it may break something elsewhere.

ORIGINAL PRICE FUNCTION:

price: function (val) {
                    return isUndefined(val) ?
                            parseFloat((this.get("price",true).toString()).replace(simpleCart.currency().symbol,"").replace(simpleCart.currency().delimiter,"") || 1) :
                            this.set("price", parseFloat((val).toString().replace(simpleCart.currency().symbol,"").replace(simpleCart.currency().delimiter,"")));
                }

NEW PRICE FUNCTION:

price: function (val) {
                    var delimiter = simpleCart.currency().delimiter == "." ? "" : simpleCart.currency().delimiter;
                    return isUndefined(val) ?
                            parseFloat((this.get("price",true).toString()).replace(simpleCart.currency().symbol,"").replace(delimiter,"") || 1) :
                            this.set("price", parseFloat((val).toString().replace(simpleCart.currency().symbol,"").replace(delimiter,"")));
                }

**Comment by yar0d** [comment]
Thanks for the patch, you saved me a headache.
