### ISSUE TITLE
Cart won't change from USD to GBP

### ISSUE THREAD

**Issue by franhaselden** [wojodesign/simplecart-js#303]
I've done as was suggested and changed USD in the script to GBP, but nothing is happening. The cart still remains in USD. It's so frustrating, I've copied the currency example given in the documentation but it appears to be incorrect?

My script reads:

<script>
  simpleCart({
    checkout: {
      type: "PayPal",
      currency: "GBP"
}
});
</script>

Live example:
www.rubytuesdaycreative.co.uk/testsite/snood.html

I knew that anything claiming to be 'simple' would end up being anything but :(

**Comment by luistinygod** [comment]
Just put the currency part outside the {}s which are defining the checkout.
