### ISSUE TITLE
SendForm : A dding customer name, email and etc to checkout?

### ISSUE THREAD

**Issue by alexjong** [wojodesign/simplecart-js#305]
Hi.  I seriously need help on how to get this done.  Basically I am able to use the SendForm feature to check out via email.  Only problem is that, I am only able to send out the products they purchase.   How do I add on such as customer details, name, email, address and etc to the email?

I thought of using the extra_data {  }  feature, but unfortunately I was not able to use a variable to replace the value of the.  Example

extra_data {
  customer_name : document.getelementbyid("customer_name")

}

A little help would be appreciated as I need to get this done quick.

I'm currently using version 3.

**Comment by iamstevemckinney** [comment]
If you're just doing document.getelementbyid("customer_name") that will return a dom element. Not the text value inside of it. Try document.getelementbyid("customer_name").innerHTML. Or if you're using jquery $("selector").text()

**Comment by alexjong** [comment]
Hi Steve,
  Thanks for the prompt reply.  I did what you suggested and placed it under the data_extra {  }, but it will redirect me to paypal instead.

Here's what I did..

script>
simpleCart({

```
checkout: { 
    type: "SendForm" , 
    url: "email.php" ,

    // http method for form, "POST" or "GET", default is "POST"
    method: "POST" , 

    // url to return to on successful checkout, default is null
    success: "success.php" , 

    // url to return to on cancelled checkout, default is null
    cancel: "cancel.php" ,

    // an option list of extra name/value pairs that can
    // be sent along with the checkout data
    extra_data: {
    cust_name : document.getelementbyid("customer_name").innerHTML


    }
} 
```

});
/script>

form name ="mail" id="mail_frm" action="#">

label for="customer_name"><b>Full Name</b> /label>
input type="text" name="customer_name" id="customer_name">
    /form>

Your Order
div class="simpleCart_items"> /div>
a href="javascript:;" class="simpleCart_checkout"> span class="button">Checkout</span> /a>

Thanks!

**Comment by iamstevemckinney** [comment]
I think its because you have a syntax error with your get element by id. My bad I should've caught that in the first message as well. It is case sensitive. "getElementById"

**Comment by alexjong** [comment]
Hi Steve,
  Thank you for your time.  I did try to changing to case sensitive.  But still no avail.  Do I need to change anything inside the simpleCart.js for this to work?

**Comment by iamstevemckinney** [comment]
Ok looking through all your code I notice you're trying to get an input value. innerHTML won't work to grab that. Also, you'll need to use the beforeCheckout event to get the value at checkout rather than on initial load since the user will change that value. I made an example with your code and the checkout event. http://playground.simplecartjs.org

for more info on the beforeCheckout event see, http://simplecartjs.org/documentation/beforecheckout-event

**Comment by alexjong** [comment]
Hi Steve,
  Thank you so much for helping me out with this one.  I have another problem here and I hope you can help me with this one.

I can't seem to find the "Buy You A Cup of Coffee" button.  If you could direct me to that button (preferably Paypal), and let me buy you a cup of coffee for helping to solve this problem.

Thanks again!

**Comment by coldes** [comment]
Hello Alex - I too am after the ability to send cart data along with basic form details like customer name, etc. I have looked at the comments above and at the source code in http://playground.simplecartjs.org. All makes sense, however, what I need to fully test this is the actual source code of "email.php". Would you have this available or a link to where this may be found?

thanks in advance, Col

**Comment by danharding** [comment]
Hi guys,

I'm trying to load up http://playground.simplecartjs.org to see the examples, but Steve, it appears to be defunct?

I am wanting to put a step between clicking 'checkout' and paypal that is a form that takes customer details (shipping etc). I haven't found any examples of this other than the production site www.flightstar.com.

Are there any code examples/tutorials available?

Dan

**Comment by alexjong** [comment]
Hi Dan,
I'm attaching the source code that I used for sending forms.  Here it is.  Hope this helps you :)
https://skydrive.live.com/redir?resid=885C11E63084CA1D!397

Basically there are 3 files attached..
Index.php - Where the items I store to be added onto the cart where you can have 2 options to either checkout via paypal or bank transfer (brings you to cart.php)

cart.php - Here is where my customer details to be sent via email.  You are still able to modify the shopping cart from here.  should you click on check out it will send you to the next page for the email.php which I changed to validate.php

validate.php - Basically it will prompt you an error message if you have not filled up the correct field.  But should everything validates, it will instead send the order email to you.

**Comment by danharding** [comment]
thanks! Appreciate it

On Sat, Jan 5, 2013 at 6:34 PM, alexjong notifications@github.com wrote:

> Hi Dan,
> I'm attaching the source code that I used for sending forms. Here it is.
> Hope this helps you :)
> https://skydrive.live.com/redir?resid=885C11E63084CA1D!397
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wojodesign/simplecart-js/issues/305#issuecomment-11911640.

## 

Regards,

Dan Harding
Bach. Information Systems
ITC Consultant

+61 (0) 402 301 568
www.invertedtomato.com
[image: Inverted Tomato Logo]

PO Box 453
Indooroopilly QLD 4068

The information contained in this email message may be confidential. If you
are not the intended recipient any use, distribution, disclosure or copying
of this information is prohibited. If you receive this email in error,
please tell us by return email and delete it and any attachments from your
system.

**Comment by merckspb** [comment]
Hi alexjong. 
Your link does not work now, but to me it would be very useful. could you make the link again or send the files to me by email tyzspb@mail.ru. I would appreciate it very much. You have helped me very much. Thanks in advance.

**Comment by arrgh11** [comment]
Hey alexjong, I too could use those source codes, if you could upload them again for merckspb and I, that be very appreciated :)
