### ISSUE TITLE
stock levels?

### ISSUE THREAD

**Issue by moimikey** [wojodesign/simplecart-js#31]
I really do enjoy this shopping cart system which I've integrated into my site. I know that this script lacks separate shipping costs and tax rates. I added this into the script myself and it is working fine, although it would be lovely if a better version of this was integrated.

My other problem which I thiink would be extremely beneficial which I'm trying to personally integrate -- but will be irritating to do so... -- is to add some sort of jquery code to call my mysql database and get stock levels. I think it would be amazing if you guys maybe did a flat file version of this? It would be quite painstaking to continuously keep up with what's sold and what's not, and the stock levels of each product, even with just 10 or so products.

Suggestion for an easy peasy code that i can start to integrate myself into this?

**Comment by iamstevemckinney** [comment]
I'm not sure if you saw this, but simpleCart(js) 2.0 does have separate shipping costs and tax rates built in. Perhaps further clarification would help to know if the built in implementations aren't meeting your needs. You can view the docs on shipping and tax rates at, http://simplecartjs.com/documentation.html (click configuration on the left)

And we're currently in the planning stages of building some add-ons that will better integrate with people's back end shopping cart systems.

**Comment by nickpelton** [comment]
I was looking for a way to have a different Tax rates per state the item will be shipped to. This isn't possible in simpleCarts 2.0 as you can only set one tax rate (unless I'm wrong?). I know Paypal can handle multiple state shipping taxes; is it possible to let paypal handle the tax calculation?

P.S. Awesome cart!
