### ISSUE TITLE
Display cart Data

### ISSUE THREAD

**Issue by Lyrith** [wojodesign/simplecart-js#311]
Hi, I have a problem with de cart data. 
I put this script code in the head 

<script >
simpleCart({
cartColumns: [
                { attr: "name", label: "Nombre"},
                { view: "currency", attr: "price", label: "Price"},
                { view: "decrement", label: false},
                { attr: "quantity", label: "Qty"},
                { view: "increment", label: false},
                { view: function(item, column){
                    return  ""+ item.size() +"" ;} , 
                attr: "custom", label: "Size"},
                { view: "currency", attr: "total", label: "SubTotal" },
                { view: "remove", text: "X", label: false}
            ]
)};
</script>

And the code "< div class="simpleCart_items"></ div>"  in the boddy, but it doesn't work. It shows the default options, but not the personalized ones. Even the remove option. It shows "remove" instead of the x.

Someone helps?? Thanks!!

**Comment by dicentiu** [comment]
put the initialization of simpleCart at the bottom of the page, before closing the body tag.
