### ISSUE TITLE
Need help to add price to item

### ISSUE THREAD

**Issue by davidperroud** [wojodesign/simplecart-js#313]
Dear, 

i'm trying to do this : 

i have an item with a price (ex; 1500.-) and a material tax (ex: 100.-)
so i need that when i add to cart the result shoud be : 

for item 1x : 1500 + 100 = 1600.-

for item 2x : 1500+1500+100= 3100.-

And i dont find how to do this, if someone could help me...

**Comment by dicentiu** [comment]
read documentation http://simplecartjs.org/documentation/setup_initialization . at the end you'll find some options for taxes
