### ISSUE TITLE
RE: Link Item Name in Shopping Cart to the Item Page

### ISSUE THREAD

**Issue by carpalwatch** [wojodesign/simplecart-js#315]
Hi,

I am trying to link the item back to the item page in the shopping cart but I could not quite figure out how the add function works in the source file.

In other words, I would like visitors to be able to click on the item in the cart to return to the item page.

Any help would be very much appreciated.

Here is my blogstore URL : http://plus.carpalwatch.com

Edit : Solved.

**Comment by jonoweb** [comment]
I'm still trying to do this has anybody else got a solutiion??

**Comment by carpalwatch** [comment]
Hi,

You can check out my blogstore. http://plus.carpalwatch.com.

**Comment by jonoweb** [comment]
Hi, 

From your code I see you get the itemname using a seperate function:

var itemName = document.getElementById(s+'_n').innerHTML;

how could I use this in my script?

```
$(document).ready(function(){

    simpleCart({
        checkout: { 
            type: "" , 
            email: "" 
        },
        cartColumns: [
    { attr: "name", label: ""},
    { view: "remove", text: "Remove", label: true},
    { view: function(item, column){
      return"<img src='"+item.get('myimage')+"'>";
   },
  attr: 'myimage' },      
],
    cartStyle: 'div'
    }); 

});
```

**Comment by cleo-1001** [comment]
heyy can you help me to do this?

**Comment by carpalwatch** [comment]
Hi, please email me at verie.inc@gmail.com.

**Comment by jonoweb** [comment]
Here's how I did it, the code returns the inner HTML so you're only getting the text link rather than the complete href tag itself.
JS:

```
 { view: function(item, column){
   return"<a href='"+item.get('pagelink')+"' class='btn btn-primary'><span>Buy NOw</span></a>";
 },
attr: 'pagelink'}
```

HTML:

```
 <div class="item_pagelink">
<a href="http://www.yoururl.com/">http://www.yoururl.com/</a>
</div>
```
