### ISSUE TITLE
Can anybody share a working sendcart.php while using the SendForm method? 

### ISSUE THREAD

**Issue by DahmaniAdame** [wojodesign/simplecart-js#316]
I spent hours Googling and searching this repo to find a clear and straight answer to how to use the SendForm checkout method. 

So far, I'm pretty sure that this code is working properly to initiate the SendForm checkout : 

```
simpleCart({
  checkout: { 
    type: "SendForm" , 
    url: "sendcart.php" ,
    method: "POST" , 
    success: "success.php" , 
    cancel: "cancel.php"
  }
}); 
```

What I need now is the sendcart.php content :) that I couldn't find anywhere. 

If anybody can help out please! I'm pretty sure that no one will ever ask about the SendForm basic set up again. Ever. 

Thanks!  

PS.: People share their issues without thinking about posting full solutions once it's solved :) Give back what you learn guys :)

**Comment by DahmaniAdame** [comment]
Struggled but got it work, at last : 

```
<?php
$to = 'mail@someshop.com';
$subject = 'Simple Cart Order';
$content = $_POST;
$body = '';
for($i=1; $i < $content['itemCount'] + 1; $i++) {
  $name = 'item_name_'.$i;
  $quantity =  'item_quantity_'.$i;
  $price = 'item_price_'.$i;
  $body .= 'item #'.$i.': ';
  $body .= $content[$name].' '.$content[$quantity].' '.$content[$price];
  $body .= '<br>';
}
$headers = 'From: webmaster@example.com' . "\r\n" .
          'Reply-To: webmaster@example.com' . "\r\n" .
          'X-Mailer: PHP/' . phpversion();
mail($to, $subject, $body, $headers);
Header('Location: thankyou.php');
?>
```

A bit sad coz no body helped this time, or even cared! :( 

http://www.adamedoe.com/2012/11/simplecartjs-v3-php-code-for-sendform.html

**Comment by drivebass** [comment]
Very nice Adamdoe, but how do you collect the customer's data (Name, Email, Tel, Address etc) to send with the cart's data? Any ideas?

**Comment by DahmaniAdame** [comment]
This guy is trying to do so #317
Stick around him :) He promised to share his final / working file.

**Comment by season90** [comment]
Thank you, Adamedoe! This really helped me :)
