### ISSUE TITLE
PLEASE HELP! Items in Cart Being Overwritten!!

### ISSUE THREAD

**Issue by jewelyetta** [wojodesign/simplecart-js#32]
When items are added to the cart, sometimes it overwrites another item that was already in the cart, and keeps doing it! Has anyone experienced this? And resolved the issue?

**Comment by zacksiri** [comment]
i am having the same issues, i think its related to cookies.

**Comment by kevinirish** [comment]
Yes, me to. Great piece of code but useless as it keeps over writing items in the cart. Can anyone keep please?

**Comment by fidoogle** [comment]
I have the same problem on IE8 on Windows XP, but works fine in Firefox. I am using the link version with an onclick like: onclick="simpleCart.add( 'name=mytitle' , 'thumb=myimage.jpg', 'price=0.99' , 'quantity=1' );"
Are you using this link version or the div version?

**Comment by lukevdp** [comment]
I couldn't find the root of the problem but found a very very bad solution to it.

It seems that the NextId variable, for whatever reason, wasn't getting set properly, and I'm guessing it has something to do with qty's, but never mind, the crappy fix is

Replace this line

this.id = "c" + NextId++;

with this

this.id = "c" + NextId++ + Math.floor(Math.random()*10000001);

If anyone can find the root of the problem, please post it!

**Comment by grahamx** [comment]
i experienced this issue when i changed the itemThumb to itemDetail in my add to cart and cart display items pages.  as it is clearly a cookies issue i restarted my browser (cleared all cookies) and testing server and everything worked ok again.  So i guess its worth trying that if you are developing....

**Comment by chekobil** [comment]
Like Lukevdp says the problem is with the NextId variable, Simplecart don´t look if the number already exists in a different row, only add 1 to the LAST ID stored in the cookie, and sometimes the LAST ID isn´t the higher value ...
my solution is to check all ID´s looking for the "real" LAST ID ...
here it is ...

me.load = function () {
...
if( readCookie('simpleCart') ){
...
for(var x=0, xlen=data.length;x<xlen;x++){  
     var info = data[x].split('||');              # reading row data
       laid = info[0].substring(4)              # the ID
       lasids = lasids + "**_" + laid        # all the IDs in a string
...
}}
            function numberorder(a,b) { return a-b; }
           idsarray = lasids.split("**_");            # the IDs are an array  
           ordenaids = idsarray.sort(numberorder);   # order the array
           lastid = ordenaids[ordenaids.length-1]      # and look at the last value, now the last value is always the higher value
           if (NextId<=parseInt(lastid)) { NextId = parseInt(lastid,10) + 1; }   # and if default NextID is not the higher, then replace it by the higher + 1

else {}
}

regards, and happy coding !!

Felipe

**Comment by wojodesign** [comment]
Thank you @feliper and everyone else for your input.  I have integrated a solution into the 2.2.dev branch that solves this issue when the items are created as opposed to onload.
