### ISSUE TITLE
Multiple Payment Methods

### ISSUE THREAD

**Issue by sinepy** [wojodesign/simplecart-js#324]
Hi! I was wondering how to make the customer be able to choose the type of payment method? I want them to be able to choose between Paypal or the SendForm option. Can someone please teach me how to do this on simplecartjs? Thanks!

**Comment by drivebass** [comment]
You can have 2 separate simpleCart calls in your js with the 2 different checkout options. One for Paypal one for sendForm. Assign them on click events on two elements "Paypal Checkout" & "Mail Checkout". There you have both methods.

**Comment by sinepy** [comment]
Thanks so much, drivebass! I figured it out with your help. It's nice to know that the community is actively helping people who aren't too familiar with this.

**Comment by drivebass** [comment]
Hi sinepy, I'm glad to know it worked! Helping others means that you will get help when you need it too,  that's why it's called "community":)
