### ISSUE TITLE
Styling the cart (2 attributes in a div?)

### ISSUE THREAD

**Issue by drivebass** [wojodesign/simplecart-js#325]
This is an example setup for the cart columns:

```
cartColumns: [
               { attr: "image" , label: false, view:'image'},
               { attr: "name" , label: "Title" } ,
               { attr: "format" , label: false } ,
               { attr: "price" , label: "Price", view: 'currency' } ,
               { view: "remove" , text: "&times;" , label: false }
           ]
```

What i want is to have the attributes "name" and "format" to appear inside a div in the cart view. 
Right now the 2 attrs are rendered with this structure:

```
<div class="item-name">NAME OF THE ITEM</div>
<div class="item-format">FORMAT OF THE ITEM</div>

```

Is it possible to render with this structure?
"name" as a div containing the "format" in a span:

```
<div class="item-name">NAME OF THE ITEM
<span class="item-format">FORMAT OF THE ITEM</span>
</div>
```

**Comment by drivebass** [comment]
Help anyone?

**Comment by FletcherPink** [comment]
Hello, i'm just searching doing the same. Did you find a solution ? Would you share it with me ? Thanks

**Comment by iamstevemckinney** [comment]
Take a look at the simplecartjs.org cart. The configuration is in the footer. You can use a function to create custom cart views. You can add this to the cart columns array.

```
{ view: function(item, column){
    return    item.get('name')+"<span class='item-format'>"+item.get('format')+"</span>";
}, attr: 'custom' }
```

Also this is discussed in the documentation here, http://simplecartjs.org/documentation/cart_columns

**Comment by FletcherPink** [comment]
WAOH ! What an amazing fastly answer ! Is it a bird ? Is it a fly ? No, it is SuperCode ! Thanks for your reactivity, i try it now.

**Comment by drivebass** [comment]
This is really a surprise! 4 months ago i gave up:) Many thanks! By the way is this project abandoned?

**Comment by FletcherPink** [comment]
So i try it and it works ! But some products don't have specific details, like color or size, and display "undefined". Is there a way to return details under conditions into array cartColumns ?
Something like:
if(item.get('size').lenght > 0){
{ view: function…

I try several ways without result. Do i have to use beforeAdd ?

Thanks

**Comment by iamstevemckinney** [comment]
Yeah, that would be invalid syntax you can't throw an if statement in the middle of an array.

Try a tertiary operator inside the function

```
{ view: function(item, column){
    return    item.get('name')+(item.get('format') ? "<span class='item-format'>"+item.get('format')+"</span>" : "");
}, attr: 'custom' }
```

or just put the if statement around that whole return

```
{ view: function(item, column){
    if(item.get('format')){
        return    item.get('name')+"<span class='item-format'>"+item.get('format')+"</span>");
    else{
        return    item.get('name');
    }
}, attr: 'custom' }
```

**Comment by FletcherPink** [comment]
Exactly what i want ! Thanks a lot. The tool you've created is really impressive possibility. Congratulations.
