### ISSUE TITLE
Calculate Total Price according the quantity of items in the cart ?  (Wholesale Cart)

### ISSUE THREAD

**Issue by johnmerced-ks** [wojodesign/simplecart-js#33]
Excelent script, but I am trying to get this done.

Can someone help me out with this?
Thanks!

**Comment by stewartgcampbell68** [comment]
did you ever get an answer or solution?

**Comment by wojodesign** [comment]
Issue now at - https://github.com/thewojogroup/simplecart-js/issues/52 - closing
