### ISSUE TITLE
Html mark up in item name?

### ISSUE THREAD

**Issue by drivebass** [wojodesign/simplecart-js#330]
Right now i have a long name in my shelfItem with a <br> inside like this:

```
<h2 class="item_name">This is a very long name that<br>needs a line break</h2>
```

When i view the cart the <br> is ignored and it shown as a full line like this:
This is a very long name thatneeds a line break

Is it possible to make the shopping cart include the <br> in the item name?

Furthermore in the cart view is it possible to put 2 attributes in one div?
Say i have this for name:

```
<h2 class="item_name">This is a very long name that<br>needs a line break</h2>
and this for a format:
<h2 class="item_color">red</h2>
```

in the cart view can i put both information in one div containing them as two elements?

**Comment by drivebass** [comment]
In the source code on lines 51 to 60 there are some variables defined with the comment 'used in views' including 'html' along with value, text, click and etc which are included in the sites docs. I have tried to put an attr in the cart data with view':html' to check if this accepts html markup but it didn't. Any ideas what this 'html' might mean? https://github.com/wojodesign/simplecart-js/blob/master/simpleCart.js#L57-L61

**Comment by dicentiu** [comment]
you cant get that text inside .item-color with this: item.get('color');

and you can put this information in yout cart like this when you initialize simpleCart

{view: function(item) {return "html container"+item.get('color')+"/ html container"}, attr:'color'}

**Comment by drivebass** [comment]
Many thanks dicentu!
Just to clarify your example. 
1
You mean if i have a div with class '.item-color' i can use this:
{view: function(item) {return "html container"+item.get('color')+"/ html container"}, attr:'color'}
to get the content. 

2
By 'html container' you mean the div that i want the 'color' to be included in? Like if the container id is description i should put that the place of "html container" of your code?

**Comment by dicentiu** [comment]
the container can be span, div, p....

look in http://simplecartjs.org/ source code at the end. they use a similar return
