### ISSUE TITLE
how to set multiple cart in same domain

### ISSUE THREAD

**Issue by TUMRAI** [wojodesign/simplecart-js#333]
(simplecartjs v3)
I need multiple cart in same domain in difference directory 
e.g.
domain.com/book
domain.com/car

my problem.. when view cart , book and car in same cart.
I think about cookie or Local Storage  

Please help
Thank you.

**Comment by dicentiu** [comment]
i don't know if this helps, but you can use simplecart.empty() when entering in a page where you don't want to have previous products

add this script at the end of the page:

<script type="text/javascript">
simpleCart.ready(function(){
simpleCart.empty();
});
</script>

there is also a save option: http://simplecartjs.org/documentation/simplecart-save

**Comment by dicentiu** [comment]
read this http://simplecartjs.org/documentation/simplecart-copy

**Comment by TUMRAI** [comment]
Cool ----> simplecart-copy 
its work like magic !

**Comment by toxis** [comment]
Thanks for this trick! :smiley:
