### ISSUE TITLE
simpleCart_increment & simpleCart_decrement

### ISSUE THREAD

**Issue by nyubbie** [wojodesign/simplecart-js#337]
Pardon me if I missed anything out on your SimpleCartJS site, but I can't seem to find any leads on how to implement a increment / decrement in quantity.

Adding class="simpleCart_decrement" like the one in your main site doesn't work...

Is the function not included inside your .js file?

Also, only simpleCart_empty works, but I don't want the client to empty an entire shopping cart :(

**Comment by dicentiu** [comment]
go to http://simplecartjs.org/ , read the page source code, at the end of the page you'll find the increment/decrement function in simpleCart initialization

in  img src= you have to put a path to some arrow images in your folder

**Comment by rbwilkinson** [comment]
Thank you for that answer. I have been searching for too many hours to achieve that. The youtube video lacks clarity. The documentation needs lots of work.
