### ISSUE TITLE
Simplecart suppresses lightbox

### ISSUE THREAD

**Issue by Uzer1** [wojodesign/simplecart-js#338]
Hello. 

Lightbox stops working when loaded together with simplecart.

ok, no need for the code.

Firebug shows no errors. 

Any ideas?

**Comment by exside** [comment]
Probably some click event is rebound and both would like to use it =)...maybe you can add your lightbox initialization in the simplecart ready event or so, but this is completely out of the blue and untested...maybe it's even enough to call the lightbox script initialization after simplecart?

**Comment by Uzer1** [comment]
I was fooled by my own css. The images were not activated because they were marked with float:left and were covered by another layer as a result and couldn`t be clicked through to. 
So, there was no java conflict.
This issue must be closed.
