### ISSUE TITLE
Cart buttons not work...

### ISSUE THREAD

**Issue by mavichpe** [wojodesign/simplecart-js#340]
I am implementing a shopping cart with simplecart, but the increment, decrement, remove, view and checkout buttons do nothing. My site is developed with joomla, and this use mootools and jquery both. I think that the problem is on simpleCart.bindInputs , because  i was debugging the code and my site never pass into the callback function of the event click in each selector. but in the demo site of simplecart, when i make a debugging over it, the code pass into that callback function. Can you help me?

This is the my site 

http://tecnofor.pernix-solutions.com/index.php/es/news-3?view=detail&code=3

The shopping cart is show with the menu option called "Cesta"

**Comment by mavichpe** [comment]
If i put this code in the chrome javascript  console, the descrement button work perfect

$(".itemRow .item-decrement a").click(function () {
                            simpleCart.find(simpleCart.$(this).closest('.itemRow').attr('id').split("_")[1]).decrement();
                            simpleCart.update();
                        });

**Comment by dicentiu** [comment]
i've looked into your site and i can't figure out what it is. i think it's a problem with initialization of the cart...

try to reduce your page just to the cart and see if it's working. delete motools and other scripts/libraries. keep just the cart.

**Comment by mavichpe** [comment]
How can i rebind the input and output events ?. I think that it will solve my problem

**Comment by mavichpe** [comment]
I solved it :-D. 

The cart details are in a li with the class  menu_principal. In the follow hierarchy:
<li class ="menu_principal">
       <a>link</a>
       <div id="cartPopover">  . . . . . . . . </div>
</li>

 i was adding a toggle funccion to the class menu_principal. 
In this way:
$(".menu_principal").toggle(function(){
            $("#cartPopover").show();
            $("header .cartInfo").addClass('open');
        }, function(){
            $("#cartPopover").hide();
            $("header .cartInfo").removeClass('open');
        }); 

then when i clicked any button in the cartPopover the toggle function was executed instead of the simplecart function

i just change the toggle function assing and that is alll.. All the shopping cart is working fine:

new toogle function :
$(".menu_principal a").toggle(function(){
            $("#cartPopover").show();
            $("header .cartInfo").addClass('open');
        }, function(){
            $("#cartPopover").hide();
            $("header .cartInfo").removeClass('open');
        }); 

Thanks for all
