### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by tple** [wojodesign/simplecart-js#347]
Hello, I've been adjusting and tweaking the code for hours now and can't quite make the check boxes work. If anyone has any words of wisdom, I'd be very grateful!

**Comment by iamstevemckinney** [comment]
Can you be more specific?

They seem to work for me here, but I'm not sure what issue you're seeing.
http://jsfiddle.net/D3vzZ/

**Comment by tple** [comment]
Thanks for your reply, I've done something similar to yours <label> <input type="checkbox" class="item_voiceover" value="steffan"> Steffan</label> which is for a voice over ordering system but it just doesn't appear in the paypal checkout

**Comment by tple** [comment]
Whoops I did try to copy some code in but it didn't appear. Your code has really helped, it now works! Thank you very much, it was just my jquery version.
