### ISSUE TITLE
Simplecartjs - Paypal Problem

### ISSUE THREAD

**Issue by gmiller** [wojodesign/simplecart-js#35]
Hi - If I run the demo from the http://simplecartjs.com website when I use the 'Checkout' button the PayPal screen loads but option details do not display properly in internet explorer. It just looks like text - ie no images or descriptions show correctly.
EG
Options:image=http://demo.simplecartjs.com/images/attack-release.png displays not the image. Is there a bug or do I need to do something? The same occurs running the cart from my own PC.
Thank you in advance

Regards Graham

**Comment by ghost** [comment]
Same issue for me — "Options: ..." shown on PayPal checkout. Shouldn't be there.

**Comment by wojodesign** [comment]
This is a similar issue to the following problem.  Closing this issue - https://github.com/thewojogroup/simplecart-js/issues/14
