### ISSUE TITLE
Check if Simplecart_Items has items

### ISSUE THREAD

**Issue by mbeeswiss** [wojodesign/simplecart-js#350]
Hi, is it possible to check if div class simplecart_items has items in it, like this way?

if simplecart_items == 0 {
NO ITEMS IN THE CARD // Shows no add to card, no total coast and no products quantity
}
else {
The "normal" output // Shows add to card, total coasts and products
}

Is there a way? Many thanks..

**Comment by dicentiu** [comment]
simpleCart.quantity() returns the total nr of items in the cart

read the documentation
