### ISSUE TITLE
no method 'submit'

### ISSUE THREAD

**Issue by StingerMKO** [wojodesign/simplecart-js#354]
Hi, suddenly an js error comes up at my local site.
I think, that I did not change anything in the code, it just stopeed working.
I can put items in the cart and also remove them, but when I click on submit the following error comes up in the console:
Uncaught TypeError: Object #<Object> has no method 'submit' in simpleCart.js:914
What can it be?
Thanks in advance!

**Comment by FletcherPink** [comment]
Hello,
I'm not a specialist but you could look at this: http://stackoverflow.com/questions/9070979/uncaught-typeerror-object-object-object-has-no-method-fancybox
And perhaps also use firebug and its console who helps a lot.
;-)
