### ISSUE TITLE
Data to Paypal - Thumb send

### ISSUE THREAD

**Issue by FletcherPink** [wojodesign/simplecart-js#355]
Hello,
In my checkout cart, the first column is reserved to thumb 
`cartColumns: [
         {view:'image' , attr:'thumb', label: '&nbsp;'},`
On Paypal payment page, "options" display the name of the thumb.

But in SimpleCart.js file, line 105, there is
`excludeFromCheckout  : ['thumb'],`
So my question is… Why and how can i set another column to be display in "options"'s PayPal payment page ?

**Comment by dicentiu** [comment]
i don't understand your question very well

you can comment that line(exclude) if you want. 

if you want other data to be added to options, you can add class="item_dataname"  to your element

**Comment by FletcherPink** [comment]
Maybe because I'm French! ;-) My question is: when I go to the Paypal's page, SimpleCart variables are transmitted. Product name, price, ... Once all essential variables are transmitted SimpleCart takes the contents of the basket. 

However, the first column of my cart is an image and is assigned to the Paypal's variable "on0". So that on the Paypal payment page, the variable "options" returns the image name instead of the size or color (for example). I looked into the code SimpleCart and I saw that line 105 software ruled out sending variable containing "thumb". So I wonder why this variable appears and how I can change it.

If you want to try to understand, here is a demo : http://www.parc-montozarbres.com/V1/e-boutique/?&menu=boutique

Thanks

**Comment by dicentiu** [comment]
if you want to return something else instead of the image name or image src you can use smth like this

cartColumns: [
{ attr: "image", label: "Imagine", view: function(item, column){return  $("<img>").attr('src',item.get('imagine'))}  },

replace what you need after return

---

if you want to change something added to simplecart you can use a function to make changes before checkout

  simpleCart.bind( 'beforeCheckout' , function( data ){
    return closeForm();
    })

---

you can cycle through items in the simpleCart like this

simpleCart.ready(function(){
var items = [];
simpleCart.each(function( item , x ){
items.push( item.name );
});
console.log( items );
})

---

i hope one of this helps you.

**Comment by FletcherPink** [comment]
I thank you for your answer, but…

It seems that I am (still) poorly expressed. A picture is worth a thousand words, here are two:
![example](https://f.cloud.github.com/assets/1735184/315305/281b29d4-97e3-11e2-8daf-8480f21f070f.jpg)
![example-1](https://f.cloud.github.com/assets/1735184/315308/2d8b3238-97e3-11e2-8ea6-3b0243b0bedb.jpg)

On the first screen Paypal payment and the variable "option" that contains the name of the thumbnail.
The second, the summary of the order.
We see that the first column is for the thumbnail.
I do not want this column to be taken into account when sending variables to Paypal. Y is there a way to avoid this?

**Comment by dicentiu** [comment]
in the simpleCart initialization on your checkout page add this

excludeFromCheckout: ['thumb']

this only works for options. you can exclude multiple categories from options array. excludeFromCheckout: ['option1','option2']

read this, also: http://simplecartjs.org/documentation/setup_initialization

**Comment by FletcherPink** [comment]
Bravo, that was it! For your information, I suspected that it was this "explodeFromCheckout" array but at no time I thought to look in the SimpleCart initialization. On one side (simplecart.js), the array contained 'thumb' and the other (initialization) the array was empty. Shame on me! 
Thank you for your patience.

**Comment by valeria-io** [comment]
How can I resize the thumb?????
