### ISSUE TITLE
Silent php checkout

### ISSUE THREAD

**Issue by FletcherPink** [wojodesign/simplecart-js#357]
Hello,
I would like to send a php form when clicking on simpleCart_checkout button using "silent way" as ajax with post method. Is ther a way to do this ?

**Comment by chekobil** [comment]
You said "... as ajax with post method ...", ... why not use exactly ajax with post method ? There´s no way to do this only with php, but with ajax calling a php form is possible
Happy coding !

**Comment by FletcherPink** [comment]
Thank you for this answer. But… I know how to call php file throw js. What i don't know, is how to tell to simplecart.js: "please, use $.ajax({url:…, type:"POST",…}); instead $_POST".
My knowledge is not so high. Can you show me the way ?

**Comment by FletcherPink** [comment]
Ok, i found a solution using another button than simpleCart_checkout and getting the content of the cart with simplecart.each function.
Thanks
