### ISSUE TITLE
Items stay in cart after checkout?

### ISSUE THREAD

**Issue by dffmonolith** [wojodesign/simplecart-js#36]
The minimalist documentation for Simplecart says nothing about what happens to contents of the cart after you traipse off to PayPal to pay for the stuff. There doesn't seem to be any callback mechanism, so is that what really is supposed to happen? Stuff just sits there with no feedback?

I can't even find a clear-the-cart setting for when checking out....

Any suggestions?

**Comment by kissGyuri** [comment]
Hi there,

I think U can solve it like this (I'm a designer with a little coding skill, so I'm not a programmer):
there's line 182, it looks like this:
me.checkout = function() {
        if( simpleCart[QUANTITY] === 0 ){
            error("Cart is empty");
            return;
        }
        switch( simpleCart.checkoutTo ){
            case PayPal:
                simpleCart.paypalCheckout();
                break;
            case GoogleCheckout:
                simpleCart.googleCheckout();
                break;
            case Email:
                simpleCart.emailCheckout();
                break;
            default:
                simpleCart.customCheckout();
                break;
        }
    };

You can modify the code like this:
me.checkout = function() {
        if( simpleCart[QUANTITY] === 0 ){
            error("Cart is empty");
            return;
        }
        switch( simpleCart.checkoutTo ){
            case PayPal:
                simpleCart.paypalCheckout();
                break;
            case GoogleCheckout:
                simpleCart.googleCheckout();
                break;
            case Email:
                simpleCart.emailCheckout();
                break;
            default:
                simpleCart.customCheckout();
                break;
        }

```
    simpleCart.items = {};
    simpleCart.update();
};
```

I managed to solve it on my own at email checkout, but I think it should work for You too.

**Comment by dffmonolith** [comment]
Thanks, I'll give this a try.

It seems odd that the package doesn't provide some way to do this....

**Comment by Mauschen** [comment]
Does anyone know how to get a feedback? I would like to get the car items before I check out in order to get a buy-confirmation so I could save this item in a database.
