### ISSUE TITLE
How I can add some classes to cart elements?

### ISSUE THREAD

**Issue by inlanger** [wojodesign/simplecart-js#362]
I'm trying to use simplecart in my current project(twitter bootstrap template), but simplecart provides own classes. Can I add my bootstrap classes to simplecart output? It's not a good idea to copy bootstrap styles for new class names...

For table layout I just need to add class="table" to my cart, but now I must to copy many lines of code.

Thanks!

**Comment by inlanger** [comment]
Now I add this line to simpleCart.js file(before 638 line):

``` javascript
cart_container.addClass('table'); // some hack for twitter bootstrap
```

and it's working for me, but patching code of library is bad idea :(

**Comment by rodrigoAbril** [comment]
I think it would be better for you to add it with jQuery just link to another js file or in the head of your html ad a script tag with:

<div>
<pre>
 <code>
          simpleCart.ready( function(){
               $('.simpleCart_items table').addClass("table");
          });
 </code>
</pre>
</div>

<p>
Hope this helps</p>

**Comment by iamstevemckinney** [comment]
You also don't need to copy the entire class in bootstrap, you can just modify the selector in the CSS.

```
.table,
.simpleCart_items table {
  width: 100%;
  margin-bottom: 20px;
}
```

**Comment by klodenet** [comment]
I have added a new event, "afterCreate".
1. Add event callbacks:

``` javascript
afterCreate: null
```

even in the code and in the config.js file (if you use, or if you declare events callback on configuration of simpleCart).
2. On `simpleCart.ready`, for `items` param, (this is about on row `1693`) add this command:

``` javascript
simpleCart.trigger("afterCreate");
```

So before:

``` javascript
items: function (selector) {
    simpleCart.writeCart(selector);
}
```

and after:

``` javascript
items: function (selector) {
    simpleCart.writeCart(selector);
    simpleCart.trigger("afterCreate");
}
```

so, you can add a new trigger on event afterCreate to add class on elements into items of Cart.
