### ISSUE TITLE
Paypal checkout send custom attribute

### ISSUE THREAD

**Issue by vicentegarciadiez** [wojodesign/simplecart-js#366]
I'd like to use Simplecart + Paypal IPN and I'd like to send in the custom parameter a OrderId or a CartId, something that identifies the shopOrder but I don't know how to specify it to simplecart.

Thanks a lot for your work :)

**Comment by vicentegarciadiez** [comment]
I'm using this 

http://simplecartjs.org/documentation/beforecheckout-event

// simple callback example
simpleCart.bind( 'beforeCheckout' , function( data ){
  data.custom= "ABC-123456789";
});

Thanks a lot :)

**Comment by Pauliosro** [comment]
I'm keen to find a solution for this too... any updates on a working solution vicentegarciadiez?

**Comment by nka11** [comment]
True documentation is the code....
Try the following sniplet in simpleCart config :

``` javascript
checkout: {
    type: "custom",
    fn: function(options) {
        // at this point, this references simpleCart
        this.items().forEach(function (item, x, name) {
            cartData.items.push({id:item.get("id"), quantity: item.get("quantity")});
          });
        // or do whatever you want !!!
        // for example link your backend for paypal express processing then redirect current page
    }
}
```
