### ISSUE TITLE
Send item-id by SendForm method POST after Checkout to URL "controlador_checkout.php"

### ISSUE THREAD

**Issue by PeterConchaR** [wojodesign/simplecart-js#369]
Code Example:
///Config Shop Cart
simpleCart({
    // array representing the format and columns of the cart,
    // see the cart columns documentation
    cartColumns: [
                { attr: "id", label: "Código"}, //<---- Present Id Product in ShopCart
                { attr: "name", label: "Nombre"},
        { view: "currency", attr: "price", label: "Precio"},
        { attr: "quantity", label: "Cantidad"},
        { view: "currency", attr: "total", label: "SubTotal" },
        { view: "remove", text: "Remove", label: false}
    ],

//Config CheckOut

```
checkout: { 
    type: "SendForm" , 
    url: "controlador_checkout.php" ,

    // http method for form, "POST" or "GET", default is "POST"
    method: "POST" , 
```

**********_Display**_*************

<table>
<tbody>
<tr class="headerRow">
<tr id="cartItem_ 84LM9600 " class="itemRow row-0 odd">
<td class="item-id"> 84LM9600 </td> 
<td class="item-name"> Tv Led De 84'' Ultra Hd Smart </td>
<td class="item-price">$9,742.59</td>
<td class="item-quantity">1</td>
<td class="item-total">$9,742.59</td>
<td class="item-remove">
</tr>
</tbody>
</table>

**Comment by webguru-in-ua** [comment]
Add a custom class field to product block, // NOT ADD CLASS 'item_id' - DONT WORK )

<?php echo '<span class="item_pid" style="display:none;">'.$product_id.'</span>'; ?>

POST result
....
itemCount   3
item_name_1 BA RPF2365
item_name_2 AE MVB2365R7
item_name_3 AJ 50236500
item_options_1  pid: BARPF2365
item_options_2  pid: AEMVB2365R7
item_options_3  pid: AJ50236500
item_price_1    40.04
item_price_2    306.63
item_price_3    4462.54
item_quantity_1 1
item_quantity_2 1
item_quantity_3 1
....

**Comment by alexzaporozhets** [comment]
Example from http://zubizub.com.ua/dnevnoe-otbelivanie:

``` html
<div class="row simpleCart_shelfItem">
                        <div class="span1">
                            <input class="item_product" style="display: none" type="text" value="121">
                            <a href="/white-light.html">

                                    <img class="item_image" alt="White Light" src="/media/product/2816220.jpg.jpg">

                            </a>
                        </div>

                        <div class="span6">
                            <a href="/white-light.html"><h5 class="item_name">White Light</h5></a>
                            <p>Вайт Лайт (White light) - новейшая разработка по уходу за зубами - система осуществляет отбеливание зубов светом.
Система White Light – это быстрый, легкий, удобный способ отбеливания зубов в домашних условиях.
Отбеливание проходит курсом, который длится от 5* дней с продолжительностью сеанса о... &nbsp;</p>
                        </div>

                        <div class="span1 item_price">
                            <p>135.00 грн</p>
                        </div>

                        <div class="span2">
                            <p><a class="btn btn-primary item_add" href="javascript:;">В корзину</a></p>

                            <p><a class="" href="#">Добавить в список</a></p>

                            <p><a class="" href="compare.html">Добавить к сравнению</a></p>
                        </div>
                    </div>
```

**Comment by PeterConchaR** [comment]
@alexzaporozhets "item_product" It is an "id" used in this framework?
@webguru-in-ua I do not understand your answer
