### ISSUE TITLE
Email option issue

### ISSUE THREAD

**Issue by tozebaiao** [wojodesign/simplecart-js#37]
Hi Guys,
First of all, great script. I will be using it in my site for online Sushi orders.
Since I need to check my orders on email and clients pay when they pick their order up at the restaurant.
 Is there a way I can put 2 more options on the email.php file, like YOUR NAME and YOUR PHONE, so I can phone clients back confirming the order?

Thanks

TOZE

**Comment by maticd** [comment]
I'm looking for this too, I have a form set up but can't seem to be able to pass the values to email.php. Can someone please help?

**Comment by tozebaiao** [comment]
hi there,
I never managed to get the options on the email file to work, so I got another solution, since I was using paypal as payment method, there is an option on the paypal account that is; purchaser must insert a phone number in a compulsory field. otherwise the purchase does not go on. This works fine, my client gets the name from the card and the phone to call back and confirm the order. Me be this is you case.
In google check out I do not know.
Good luck with that.

TZ
