### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by williewh** [wojodesign/simplecart-js#370]
Hi, this website is down:
http://simplecartjs.org/

Need it.

**Comment by agdm** [comment]
+1

I was attempting to use the documentation this weekend for a project but ended up just fiddling around in chrome inspector trying to figure out how things worked. 

It has been down since Saturday night sometime....

**Comment by iamstevemckinney** [comment]
We're looking into this. Thanks for letting us know.

**Comment by iamstevemckinney** [comment]
I believe we've identified the problem. We're running some updates and should have the site backup within the next hour or so. I'll post here again when its back up.

**Comment by iamstevemckinney** [comment]
Site is back up.

**Comment by williewh** [comment]
If we're still getting these comments, the site just went down again. Ha, I'm on it way too much. Love this script!
