### ISSUE TITLE
what is about the commits from the 17th march

### ISSUE THREAD

**Issue by DanielRuf** [wojodesign/simplecart-js#373]
https://github.com/DanielRuf/simplecart-js/commits/master

Will they be added to the current master branch?

**Comment by DanielRuf** [comment]
no statement? =(

there are many fixes and important changes which should be part of simplecart-js.

**Comment by darkchaz** [comment]
Hello DanielRuf,
The branch linked to above (https://github.com/BandManager/simplecart-js/commits/master) leads to a 404. I thought it may no longer be valid.

**Comment by iamstevemckinney** [comment]
simpleCart.min.js in the repo is compressed with Google Closure Compiler.

**Comment by DanielRuf** [comment]
@darkchaz sorry, my fault.
It is now at https://github.com/DanielRuf/simplecart-js  (and also in the fork graph view) ;-)
