### ISSUE TITLE
Page Link not Working for Me

### ISSUE THREAD

**Issue by kahunacoder** [wojodesign/simplecart-js#378]
I have the following code to create columns:

cartColumns: [
    {attr: 'pageLink' , view:'link' , label: 'Details' ,  text: 'View Item' },
    { attr:'thumb', view:'image' , label: "Item"},
        { attr: "name", label: false},
        { view: "currency", attr: "price", label: "Price"},
        { view: "remove", text: "Remove", label: false}
    ]

And my items have the following code to add a link to their product page:

< a class="item_pageLink"  pageLink="test.html" href="<?php echo $_SERVER['REQUEST_URI']; ?>"></a>

In simpleCart.js at line 574 (inside link: function (item, column)) 
I added two alerts as follows:

alert(column.attr); returns 'pageLink'
alert(item.get(column.attr)); returns undefined

I'm using jQuery 1.9.1 and simpleCart.js 3.0.5

I've tried everything I can think of but it seems broken to me.

Thanks,
Gary

**Comment by iamstevemckinney** [comment]
The "attr" property does not refer to an actual HTML element attribute. It is referring to the attribute in relation to the product. If you would like the pageLink cart column to display "test.html" you must make the innerHTML of the element with the class "item_pageLink" be "test.html".

**Comment by kahunacoder** [comment]
Thanks for the reply. I still can't get it to work, here is what I tried.

I changed this:
< a class="item_pageLink" pageLink="test.html" href="<?php echo $_SERVER['REQUEST_URI']; ?>"></a>
to this:
< a class="item_pageLink" href="<?php echo $_SERVER['REQUEST_URI']; ?>"><?php echo $_SERVER['REQUEST_URI']; ?>< /a>
To simplify things I also tried this:
< span class="item_pageLink">test.html< /span>

What am I doing wrong?

**Comment by kahunacoder** [comment]
Any help would be appreciated.

**Comment by iamstevemckinney** [comment]
The problem seems to be the camel case of the attribute. Strange, but i have it working without the camel case here, http://jsfiddle.net/z7xW4/

**Comment by kahunacoder** [comment]
Thanks for the reply, I haven't tried it yet, but I noticed your example isn't outputting a link.

**Comment by kahunacoder** [comment]
Thanks, it's working now.
