### ISSUE TITLE
Price Formating - Currency Symbol to appear after value ie 0.00€

### ISSUE THREAD

**Issue by xxxbenny** [wojodesign/simplecart-js#39]
I am no .js programmer but have been trying to get the Euro symbol to appear after the value ie 
0.00€ with no joy can anyone help?

**Comment by tinox** [comment]
Hi! I was looking for the solution to that and I've found one just today. I don't know if there is a better way, but for now this worked for me. 
Find the comment  \* Helpers on the script and replace this line:
Number.prototype.toCurrency=function(){return(arguments[0]?arguments[0]:"$")+this.withCommas();};

by this:
Number.prototype.toCurrency=function(){return this.withCommas()+(arguments[0]?arguments[0]:"$");};

Regards!

**Comment by xxxbenny** [comment]
Thanks.

**Comment by wzazza** [comment]
Thank you. Saved some time.

**Comment by camyo** [comment]
Thanks a lot !!!
