### ISSUE TITLE
document.getelementbyid not working

### ISSUE THREAD

**Issue by weformengineering** [wojodesign/simplecart-js#396]
Please delete this thread, since no one is able to help me.

**Comment by iamstevemckinney** [comment]
Do you have a working example of the page. Its pretty difficult to see what's going on with the 3 different pastebins.

I'm also not sure exactly what you're asking, are you wanting the checkout button of the cart to send along custom data? if so you'll want to grab that data in the before checkout event. See this page in the docs, http://simplecartjs.org/documentation/beforecheckout-event

**Comment by iamstevemckinney** [comment]
There is a syntax error in your code above.

```
data.levering : document.getElementById("levering").value;
```

should be

```
data.levering = document.getElementById("levering").value;
```
