### ISSUE TITLE
PayPal checkout with item_number

### ISSUE THREAD

**Issue by anrosol** [wojodesign/simplecart-js#402]
My shelfitem contains the following element:

``` html
<div class="item_number">20</div>
```

I was unable to pass the item_number to PayPal upon checkout. I traced the issue down to this line here: 

``` javascript
data["item_number_" + counter] = item.get("item_number") || counter;
```

item.get("item_number") remains undefined. I modified the line as follows, and it PayPal is now sent a proper item_number variable.

``` javascript
data["item_number_" + counter] = item.get("number") || counter;
```

Is this possible bug reproducible?

**Comment by kmcarter** [comment]
I am having issues with this too.  For anyone else viewing this and trying to work around it, here is a workaround without modifying the core code:

``` JavaScript
simpleCart.bind( 'beforeAdd' , function( item ){
    item.set("item_number", paypalid);
});
```

`paypalid` can be another item option (although beware, it will still be passed to Paypal as a custom option) or generated via some other method.

**Comment by kmcarter** [comment]
I just used @dvroman's workaround, but you also have to change `item_number` to just `number` line 834:

``` JavaScript
// special fields for items
reservedFields: function () {
    return ['quantity', 'id', 'number', 'price', 'name', 'shipping', 'tax', 'taxRate'];
},
```

Otherwise, you get not only the Item Number set properly, but an additional "number" custom option.

**Comment by designlook** [comment]
Thanks so much! Gave me a headache until I saw this!
