### ISSUE TITLE
Setting return URL

### ISSUE THREAD

**Issue by wgmp** [wojodesign/simplecart-js#405]
Hi, 

Thanks for this! Nearly working, I just can't get the custom return url working.

I'm initialising as below...
simpleCart({
                checkout: {
                  type: "PayPal",
                  email: "xxx@yyy.com"
                },
                success: "wgmphoto.com/fandj/index.html?paypal-confirm",
                currency: "GBP"
              });

Following making the payment, I'm redirected back to default page set in the paypal account, rather than to the success url above.

Any help would be massively appreciated.

Thanks, Will.

**Comment by ghost** [comment]
The easiest way I found to do it was to set the return address in your simplecart.js script. Under the default settings:

```
settings = {
    checkout: {
type: "PayPal", success: "http://wgmphoto.com/fandj/index.html?paypal-confirm"},
                currency                : "GBP",
                language                : "english-us",
```

**Comment by wgmp** [comment]
Thank You Sir! 

I had success at the top level of the data param, not inside the checkout object.

Senior moment. Thanks again. W.
