### ISSUE TITLE
Free Shipping Over a Certain Dollar Amount

### ISSUE THREAD

**Issue by mikebennett** [wojodesign/simplecart-js#41]
Hey y'all, I LOVE this shopping cart, and pretty much have it all set in place except for one thing:

I want to offer my customers free shipping if they spend $25 or more on my site (http://lpcustomcreations.com).

I can't figure out how to make the "view cart" page show this.  So if the cart total is $25 or more, I want the shipping field to show $0.00.  If the cart total is $24.99 or less, I want the shipping field to show $2.99.  

Knowing very little about Javascript, I thought one of you awesome ninjas could help me out.  Oh, and I have paypal set to work all of this out, I just want the view cart page on my site to reflect what they will see in paypal.

Thanks so much,

Mike

**Comment by mistralc** [comment]
Hi, i have try to do this function, but it doesn't work...
I need help too.
