### ISSUE TITLE
Email not sending all up total

### ISSUE THREAD

**Issue by ismadman** [wojodesign/simplecart-js#42]
Great script . Not a big coder so still trying to get my head around it. I grabbed the email version from http://github.com/thewojogroup/simplecart-js/tree/email and set up my email etc . When I receive my test order there are totals for the items but not a final total of all items . How would i go about just getting :- Item | amount | total For all the items then just a FINAL TOTAL ( all up ) 
sent to my email?
I am trying to use this for a restaurant who just want to take online orders with no payment 
(They either pay on pick up or delivery)
I really like the way this works as every other one I find makes you leave the page .
I like how this is all stays in one place but unless I can work out a few things i'm going to have to keep looking .
Has anyone mastered this as there still is no instructions in the wiki under the Email section .
And another thing ...How would i go about styling the email as at the moment it comes through as one downward line . Do I add the css inline in the email.php?? So confused 
This is what i see :-
Thumb
Name
Size
Price
decrement
Quantity
increment
remove
Total

Zebra
## $187.95

2
+
Remove
$375.90

Cow
## $18.00

2
+
Remove
$36.00

---

So alls I need is someone to point me in the right direction on receiving the Final total as well ( And possibly telling me how to get rid of the -+ and remove) and just some tips on styling the Email . ( Unless someone out their has written a verbose Manual for dummies lol - ie : i'd take it )
Cheers
Kevin Messer

**Comment by wojodesign** [comment]
The css needs to be added inline for the emails to be formatted correctly.  This is a work in progress for the email feature.
