### ISSUE TITLE
Empty cart after checkout [Solved]

### ISSUE THREAD

**Issue by cube3** [wojodesign/simplecart-js#424]
Hi guys. It become big problem to find solution for this, but I think this function should be as default, ins't it?
Hoe can this functionallity can be reached? 

This issue is too old https://github.com/wojodesign/simplecart-js/issues/36
and this one doesn't provide solution for simplecart https://github.com/wojodesign/simplecart-js/issues/132

**Comment by iamstevemckinney** [comment]
This requires a return url at Paypal or one of the other checkout methods. On that url that you return to, you can call simpleCart.empty();

**Comment by cube3** [comment]
the best way! thanks a lot.
problem officially solved!

**Comment by bhabhie** [comment]
how to remove the cart automatically after the checkout process is complete

**Comment by cube3** [comment]
Pass the parameter  ( success: "success.html" )  to the SImpleCart where you initialize it, and after checkout process is complete billing will return to success.html (and in this html call simpleCart.empty(); method)
http://simplecartjs.org/documentation/paypal
http://simplecartjs.org/documentation/simplecart-empty
