### ISSUE TITLE
Please help me, quantity minimum order

### ISSUE THREAD

**Issue by wavedev** [wojodesign/simplecart-js#428]
Hello,

Firstly thank you for the script SimpleCart!it's fantastic.
I could make a good customization script but I stuck on something that is not yet complicated.

I want to put a "minimum order" on the website.

When the user click on checkout button, I would like the following rule:

If quantity> 2 is true ==> play checkout.

Else quantity> 2 is false ==> display an alert message "The minimum order is 2 products" (ideally in a div block)

I tried a lot of possibilities, and saw many forums ...

Please help me, easy problem but I am seriously stuck

**Comment by chekobil** [comment]
Hello, I'm sure there's a better way to do it, but this works for me

LINE 930 aprox.

```
generateAndSendForm: function (opts) {

    // set your minimum quantity
      var Minquantity = 2;
    // get total quantity
    var Totalquantity = 0;
    simpleCart.each( function (item) {  Totalquantity += item.quantity(); } );

    // compare both, and if total is minor than minimum don't do the checkout and append a new div to the body                  
    if (Totalquantity < Minquantity) {
        var msg = simpleCart.$create("div").text("ERROR quantity = "+ Totalquantity);
        simpleCart.$("body").append(msg);
    }
    else{                                       
        var form = simpleCart.$create("form");
        ....
          form.remove();                                            
    }
}
```

**Comment by wavedev** [comment]
Felipe,

"Thank you" is not big enough to tell you how to help me.

a night's work won ...

Code works perfectly with the current customization, thank you again for taking the time to share your work!

I'm not familiar with javascript but I understand how this script works. Your code will allow me to customize other elements.

Thank you Felipe!!

**Comment by soydemadrid** [comment]
Hi this works well. :)
