### ISSUE TITLE
Ajax loading problem

### ISSUE THREAD

**Issue by arsicfilip** [wojodesign/simplecart-js#435]
When page with simplecart(js) is loaded into ajax dynamic content, cartinfo doesn't show anything (simpleCart_quantity, simpleCart_total), Only after refresh or adding item it show data. Same thing happening when browsing other pages and returning to page where simplecart is. 
Any information is valuable to resolve this problem.
Thanks in ahead

**Comment by DrPennybags** [comment]
Use the .ready() event. When that is triggered then call .load(). That should solve your problem. Good luck!

**Comment by arsicfilip** [comment]
DrPennybags, thank You for Your fast reply!

Unfortunately I'm little bit short on knowledge of java script coding, so if You please to help me with this. I will try to explain how I understand You:

document.ready(){} 
simpleCart({       cartStyle: "table",
             cartColumns: [
                    { attr: "sku" , label: "&#352;ifra" } ,
                    { attr: "name" , label: "Naziv proizvoda" } ,
                    { attr: "price" , label: "Cena", view: 'currency' } ,
                    { view: "decrement" , label: false , text: "-" } ,
                    { attr: "quantity" , label: "Koli&#269;ina" } ,
                    { view: "increment" , label: false , text: "+" } ,
                    { attr: "total" , label: "Ukupno", view: 'currency' } ,
                    { view: "remove" , text: "&nbsp;&nbsp;X" , label: true }],
                currency: "RSD",
                checkout: { 
                type: "SendForm" , 
                url: "cart.php",
                method: "GET" ,
                // url to return to on successful checkout, default is null
                success: "success.html" ,
                // url to return to on cancelled checkout, default is null
                cancel: "cancel.html" ,
                // an option list of extra name/value pairs that can
                // be sent along with the checkout data
                extra_data: {
                storename: "Bob's cool plumbing store",
                cartid: "12321321"}
                }
});

and after that? Same thing with document.load?

**Comment by DrPennybags** [comment]
simpleCart.ready(function(){
     simpleCart.load();
});

**Comment by arsicfilip** [comment]
Thank You for reply but no luck at all... I've tried with this code all over site, in .js, on page, everywhere but still the same.
Is it help to solve problem to say that I'm using tweeter bootstrap?
Any other idea? 
There's many solutions for e-commerce on net but I found simpleCart, most adequate for my needs

**Comment by arsicfilip** [comment]
Ok, I solved with placing simpleCart.update(); on few places, it works now. thanks for helping at any case.

**Comment by ChaseRaz** [comment]
I am running a new installation of simpleCart and am running against the same issue.  None of the above solutions seem to be working.  Can you please post specifics on what has solved this problem?

Edit: Moments after posting, I realized that the script actually was working, but another .js file was snagging and causing scripts to take a long time to load.  The quantity and total values weren't populated until after load, so it was a matter of making sure the page had finished loading in an appropriate time. (Under 1-2 seconds)  Otherwise it appeared as if the values weren't present until finished loading.  I'd still like to see other people's solutions.
