### ISSUE TITLE
Items in cart displayed horizontally?

### ISSUE THREAD

**Issue by jsarnold** [wojodesign/simplecart-js#44]
At the moment when users add items to the cart, the cart contents is built up as a vertical list, with all of the headers in a vertical list at the top, and the elements of each item underneath that - as in:

Name
Price
Quantity
Total
Red t-shirt
$6.00
2
$12.00
Blue t-shirt
$8.00
2
$16.00

What I need is to have the headers running horizontally (in a table ideally) like this:

Name             Price     Quantity    Total
Red t-shirt             $6.00   2      $12.00
Blue t-shirt                    $8.00   2      $16.00

Can anyone help me - please?

**Comment by nathannash** [comment]
Add this to your CSS file, make sure the parent div has a set width.
.itemContainer{float:left;position: relative;margin-right: 20px;}

**Comment by KIKOL** [comment]
I've been trying to horizonally align the cart items for a while now and that solution is not working. All parents divs have a set width and I'm still getting a vertical alignment over the horizontal.

Is there another solution that anyone can think of? This is the only thing holding back the new cart for the website I'm working on, everything has been perfect but this.

**Comment by alexjong** [comment]
{
simpleCart({
        //Setting the Cart Columns for the sidebar cart display.
        cartColumns: [
            //Name of the item

```
        { attr: "name" , label: "Name" },
        //Price of item
        { attr: "price", label: "Price"},
        //Quantity displayed as an input
        { attr: "quantity", label: "Quantity", view: "input"},
        //Subtotal of that row (quantity of that item * the price)
        { attr: "total" , label: "Subtotal", view: "currency"  }
    ],
```

// adding this line will help
        cartStyle: "table"
    });
}
