### ISSUE TITLE
Adding items to cart via URL?

### ISSUE THREAD

**Issue by brakai295** [wojodesign/simplecart-js#443]
Hey there,

is it possible to fill a cart by passing on values/variables through a URL? 
If not, how else can I send a link to someone per email that leads to a cart filled with certain items? Possible?

**Comment by iamstevemckinney** [comment]
You can grab the parameters with a little advanced JS kung foo, see here, http://stackoverflow.com/questions/11582512/how-to-get-url-parameters-with-javascript

Then you can add things to a cart manually, see the documentation here, http://simplecartjs.org/documentation/simplecart-add

**Comment by brakai295** [comment]
Unfortunately, not a developer enough to know how to do this. ;) But thanks!
