### ISSUE TITLE
images in cart not showing up

### ISSUE THREAD

**Issue by deboard4** [wojodesign/simplecart-js#453]
On your sample site...add something to your cart, then view the cart
http://simplecartjs.org/cart/
The images are not pulling through...
Can you send me the fix for this?

**Comment by diarise** [comment]
Same issue, after adding this piece of code 
{view:'image' , attr:'thumb', label: false},
the image source still undefined on the output HTML.
If someone have a idea please share it :)
please see demo http://jsfiddle.net/z7xW4/15/

**Comment by madebymats** [comment]
I had the same problem. Solved it by using a custom view:

```
cartColumns: [
     { view: function(item, column){
          return"<img src='"+item.get('myimage')+"'>";
       },
      attr: 'myimage' },
]
```

And in the html:

```
<img class='item_myimage' src='/path/to/myimage' alt='Alt text' >
```

**Comment by madebymats** [comment]
http://jsfiddle.net/z7xW4/22/

**Comment by ed-ma** [comment]
you would need to change the class of the image to "item_thumb" and add an attribute to the img tag "thumb".

e.g.:

```
<img alt="image" src="http://placehold.it/100x100" thumb="http://placehold.it/100x100" class="item_thumb"/>
```

Here is a working version of the first jsfiddle:
http://jsfiddle.net/88XsM/
