### ISSUE TITLE
SendForm checkout sometimes return 403-error 

### ISSUE THREAD

**Issue by jannejava** [wojodesign/simplecart-js#457]
I have some users complaining that the SendForm-checkout gives an 403 error. I haven't been able to track down it more than different independent users with different browsers are reporting this. Also I can see in the logs that the page with the cart is generating the 403-error. 

Anyone have any ideas or speculations? 

Thanks in advance!

**Comment by anubisson** [comment]
You exposed the wrong rights for the folder in which there is a required file, or on any of its parent directories.

**Comment by jannejava** [comment]
It works for most of the time for most users so it cannot be the permissions.

I think I have tracked down to be the web host's mod_secure. Some of mod_secure's rules are engaged on javacsripts form posts. This seems to be a common problem.
