### ISSUE TITLE
Change checkout language

### ISSUE THREAD

**Issue by romulopimentel** [wojodesign/simplecart-js#46]
Since there is no option for it on the documentation, I've tried to edit the code.
I've e-mailed PayPal about this issue, and they sent me the answer that I shoud add the following variables on my button:
<input type="hidden" name="LC" value="BR"> or LC=BR
Then, I found this funcion on the code:

var me = this,
            winpar = "scrollbars,location,resizable,status",
            strn  = "https://www.paypal.com/cgi-bin/webscr?cmd=_cart" +
                    "&upload=1" +
                            "&business=" + me.email + 
                    "&currency_code=" + me.currency,  
            counter = 1,
            itemsString = "";

I thought on putting something like this on the code, but it didn't work:

"&LC=BR" +

Any ideas about this? It's really important, so any help is welcome.
Thank you very very much!

**Comment by piperh** [comment]
BR is paypal code for Brazil, yes?  I've found that one can make the change work by putting your   &lc=BR   directly into the paypal address line before the + variables, like so:

<pre><code>
"https://www.paypal.com/cgi-bin/webscr?cmd=_cart&lc=BR" +
</code></pre>

and the other variables are added normally when the cart is sent off to ppal.
