### ISSUE TITLE
Only display one cart at one page

### ISSUE THREAD

**Issue by hancheester** [wojodesign/simplecart-js#47]
I encouter a problem when i try to place multiple < div class="simpleCart_items" > < /div > in a page, it always displays items on the last div. The other divs will show nothing except the last div. When I look at the script, I found out that cartDivs uses appendChild method to add item rows. Look like only last cartDiv will be able to display items. Thus, I come up with a quick fix with codes below:

me.updateView = function() {
        me.updateViewTotals();
        if( me.cartDivs && me.cartDivs.length > 0 ){ 
            for(current in me.cartDivs) {
                me.updateCartView(me.cartDivs[current]); 
            }
        }
    };

This will ensure every <div class="simpleCart_items"></div> in a page will be able to show items. But Im not sure whether this is a good way to fix it, maybe you can do it in a better way, like deep cloning object? Just my 2 cents.

Cheers

**Comment by brettwejrowski** [comment]
This is being added to v3
