### ISSUE TITLE
size options where each size is a different price

### ISSUE THREAD

**Issue by piperh** [wojodesign/simplecart-js#48]
Hello, if anyone's listening out there I'd be glad to know if it's possible to configure simplecart so that each option (like, for example, the "Awesome T-Shirt" small, medium, large) can have a different price returned to the cart. I'm not a javascript coder though I've spent some time looking at all the configuration possibilities and cannot see if what I need is possible with the packaged code. TIA

**Comment by wojodesign** [comment]
duplicate issue - https://github.com/thewojogroup/simplecart-js/issues/52 - closing
