### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by Finetuned** [wojodesign/simplecart-js#497]
http://simplecartjs.org 

Uncaught ReferenceError: simpleCart is not defined because there is a 404 on https://raw.githubusercontent.com/wojodesign/simplecart-js/v3/simpleCart.js

**Comment by saosasa156** [comment]
usually adress the page still can not read or known

2015-02-02 23:07 GMT+07:00 hypo.io notifications@github.com:

**Comment by yanick** [comment]
fwiw, duplicate of #492

**Comment by Finetuned** [comment]
@yanick not worth much either way it seems…

**Comment by yanick** [comment]
@hyponym Stuff to do typically has that way to overwhelm the time available to do them. Have faith: they'll eventually get to it.  :-)
