### ISSUE TITLE
[Wordpress] Displaying items in cart using onclick method

### ISSUE THREAD

**Issue by nathannash** [wojodesign/simplecart-js#50]
I'm having an issue using Wordpress 3.0 and the onclick method to add items to the cart. The store items are inside the wordpress loop, and the cart is outside the loop. When I click "add to cart" (for one item) I get two items. One that displays everything perfectly. Along with the first item I get a duplicate item that displays NaN for the price, and doesn't update the total for that item when I increment and decrement the quantity. Here is the console output:

No quantity for item. simpleCart.js:1048
No price for item or price not properly formatted. simpleCart.js:1048

*
When I don't use the onclick parameter simplecart adds the item with the NaN value only.

**Comment by nathannash** [comment]
Removing class="item_add" solves the duplication issue.

**Comment by wojodesign** [comment]
The NaN issue has been solved in 2.1
