### ISSUE TITLE
simplecartjs issue with google chrome

### ISSUE THREAD

**Issue by grantca** [wojodesign/simplecart-js#51]
I have used to simple cart in a project of mine, however i am having an issue as it relate to maintaining my cart information while navigating through multiple pages. I have tested this using mozilla firefox and there is no problem but i would really like this issue to be resolved.

Thank you

**Comment by bacalov** [comment]
I guess you are not initializing it properly, i did not find this issue. Chrome is maintaining the info after restart browser/pc.
