### ISSUE TITLE
Getting empty cart error in Paypal

### ISSUE THREAD

**Issue by Albermonte** [wojodesign/simplecart-js#511]
I'm getting an empty cart error when I try to checkout.

This is the paypal error: https://www.paypal.com/cgi-bin/webscr?cmd=_cart&upload=1&currency_code=EUR&business=alberto.monterroso%40hotmail.com&rm=0&tax_cart=0.00&handling_cart=0.00&charset=utf-8&quantity_1=1&amount_1=20.00&item_number_1=1&option_index_0=0

**Comment by Albermonte** [comment]
Anyone?

**Comment by iamstevemckinney** [comment]
Do you have anymore information? a place to try your code out that
generates that link?

**Comment by Albermonte** [comment]
Here you have part of the code: https://drive.google.com/file/d/0B0zT8NvJAIwQdGtKenlZT29UWHc/view?usp=sharing

Also you can check it at http://boostinges.ga/

**Comment by Albermonte** [comment]
I've just found the mistake, I forgot to include the class="item_name"

Thx
