### ISSUE TITLE
Last commit is 3 years ago?

### ISSUE THREAD

**Issue by ronenteva** [wojodesign/simplecart-js#517]
Is this project maintained?
How come nothing has been updated for more than 3 years?

**Comment by georgesuba** [comment]
@ronenteva what would you like to update? Perhaps you can see this : [https://github.com/wojodesign/simplecart-js/issues/516](https://github.com/wojodesign/simplecart-js/issues/516)

**Comment by ronenteva** [comment]
Yeah I was also wondering because of the example not working... thank you for your quick reply!
Personally I have no idea if this project needs an update or not, but I saw 180 issues and 23 pull requests, so I assumed at least one of them would have worth updating :)
