### ISSUE TITLE
Additional Payment Gateways?

### ISSUE THREAD

**Issue by jdawson** [wojodesign/simplecart-js#53]
Wondering how to add additional payment gateways other than Paypal (e.g., PayJunction)

Thanks,
John

**Comment by Guldstrand** [comment]
I´m wondering the exact same thing.
Maybe a gateway for a swedish company called payson?

**Comment by wojodesign** [comment]
Custom checkout functions can be added.  If I get multiple requests for specific gateways, I can develop them. Otherwise, others can contribute solutions.
