### ISSUE TITLE
Cart Header alignment issues

### ISSUE THREAD

**Issue by CraigReville** [wojodesign/simplecart-js#58]
I am using 

simpleCart.cartHeaders = ["Name", "decrement_noHeader", "Quantity", "increment_noHeader", "Amount", "Price", "Shipping", "Delivery" ]; 

which has a few non standard header which appears without any issues, the problem is that the headers are out of alignment whenever using non standard headers,

Anyone to fix this been trying for 4hrs to fix the alignment.

**Comment by wojodesign** [comment]
Are they out of order or are the widths incorrect?

**Comment by CraigReville** [comment]
Hello,
I maybe should have posted back earlier :S

I found that they were out of order for some reason however I discovered that there were issues when using prototype, I managed to fix this by swapping scripts to a newer more updated version, really weird but the issue has been resolved.

Kindest Regards
