### ISSUE TITLE
Fixed Quantity

### ISSUE THREAD

**Issue by pankajtamrakar** [wojodesign/simplecart-js#61]
Hi

For Some products We want it should not go beyond limits, like domain name,you can have more then 1 quantity.
so is it possible to fix item quantity for specific product. 

PS : I Love your Cart

Thanks

**Comment by wojodesign** [comment]
Currently there is no built in limit option, but you could always write a function that checks and lowers the quality:

``` javascript
function checkQuantity(item, limit){
  if( item.quantity > limit ){
    item.quantity = limit;
  }
```
