### ISSUE TITLE
Checkout with paypal or email

### ISSUE THREAD

**Issue by Liebling65** [wojodesign/simplecart-js#64]
Is it possible that the user can select to checkout with Paypal or email?

regards
Erich

**Comment by rtgebm** [comment]
comment out all your checkoutto:

// simpleCart.checkoutTo = GoogleCheckout;

and add a function: I created an easy function:
function passPaypal(){ simpleCart.checkoutTo = PayPal; } function passGoogle(){ simpleCart.checkoutTo = GoogleCheckout; }

And then my checkout options:

a href="javascript:;" class="simpleCart_checkout" onclick="passPaypal();" >checkoutpaypal

/a>

a href="javascript:;" class="simpleCart_checkout" onclick="passGoogle();" >checkoutgoogle

/a>

(Put a < in front of a href obviously) Seems to work good, but I am no coder...
