### ISSUE TITLE
cart item images disappearing

### ISSUE THREAD

**Issue by formermember** [wojodesign/simplecart-js#65]
So when I add an item the cart the thumbnail images shows up as expected in the cart.  Then if I navigate to another page and come back to the store all the thumbnails in the cart are gone until I add another item to the cart at which point they all come back.

http://stormshow.com/?/store/

it seems that the cart_headers are being over written as the increment and decrement also disappear until something else is added to the cart after retuning.

Any ideas.  Thanks

**Comment by wojodesign** [comment]
simpleCart(js) is being initialized before you set the headers.  If you are doing your config onload, you can do 

``` javascript

simpleCart.update();

```

to update the cart with your preferences.
