### ISSUE TITLE
Clear Cookie after Successful Purchase

### ISSUE THREAD

**Issue by MarcLotter** [wojodesign/simplecart-js#67]
When I have successfully made an online purchase using SimpleCartJS and return the product List "the Shelf", the items of the previous purchase are still in the basket. 

How do remove these values (I assume Cookies) on load of my success page so that when I return to the Shelf my basket will be clean?

**Comment by chekobil** [comment]
Hi Marc, 
you need to add this line after your succes page

<script>eraseCookie('simpleCart');</script>


this function is a part of the Simplecart code

happy coding !!

**Comment by MarcLotter** [comment]
Wow! thanks a million guys!
Please let us know how we can reciprocate!
Marc...

**Comment by Dudikowski** [comment]
Could someone please clearify the meaning of this:

"you need to add this line after your succes page"

How can I add a line after a page? 
Or should it say after the page loads? If so where do I put it and how?

Sorry for the dumb questions but I am in dire need to fix this in my shop.

**Comment by Dudikowski** [comment]
Sorry for my previous question. I used the wrong name for the cookie. It was as simple as that.

And I think I also saw another cookie that needed to be erased
sc_simpleCart_chunks

If I didn't delete this second cookie the basket showed one item still (but the price was zero)
