### ISSUE TITLE
Multiple Checkout Method

### ISSUE THREAD

**Issue by MarcLotter** [wojodesign/simplecart-js#69]
Hi,
How can I use multiple payment methods ('simpleCart_checkout' Buttons) on the same page?
EG:

<a href="javascript:;"><input type="button" class="simpleCart_checkout" value="Credit Card"></a>
<a href="javascript:;"><input type="button" class="simpleCart_checkout" value="PayPal"></a>

**Comment by rtgebm** [comment]
comment out all your checkoutto:

// simpleCart.checkoutTo = GoogleCheckout;

and add a function: I created an easy function:
function passPaypal(){ simpleCart.checkoutTo = PayPal; } function passGoogle(){ simpleCart.checkoutTo = GoogleCheckout; }

And then my checkout options:

a href="javascript:;" class="simpleCart_checkout" onclick="passPaypal();" >checkoutpaypal

/a>

a href="javascript:;" class="simpleCart_checkout" onclick="passGoogle();" >checkoutgoogle

/a>

(Put a < in front of a href obviously) Seems to work good, but I am no coder...

**Comment by wojodesign** [comment]
Thanks, rtgebm.  This is how I would do it right now as well.

**Comment by HarveyEV** [comment]
I assume this is slightly different in version 3 as I have not seen a checkoutTo function in V3. I am attempting to use paypal and sendForm together. I assume the two functions should look something like below. Could someone confirm this?

Paypal:

```
function passPaypal(){
    simpleCart({
            checkout: {
                type: "PayPal",
                email: "you@yours.dom"
            }
    });
 }
```

and Sendform:

```
function passForm(){
    simpleCart({
        checkout: { 
        type: "SendForm" , 
        url: "http://www.domain.dom/checkout.php"
            }
    });
 }
```
