### ISSUE TITLE
Price format

### ISSUE THREAD

**Issue by theikid** [wojodesign/simplecart-js#70]
Hi there. I'm trying to implement simplecart on a website and for nwo it's working good. But I go item with a price writeen 12,50€ and the script make it 1250€ Can't i use the comma sign?

Thank you

**Comment by chekobil** [comment]
Hello, 
without modifications it´s impossible ...
I get it changing the default values in this function

Number.prototype.withCommas=function()

Regards
felipe

**Comment by dvdotsenko** [comment]
CartItem instantiator has the following code:

```
} else if( field == "price"){
    value = value.replace( /[^(\d|\.)]*/gi, "");
    value = value.replace(/,*/gi , "");
    value = parseFloat( value );
}
```

If i read it right, the "US" convention ("millions,thousands,whole.fraction) is assumed as the only correct one when cart population code updates the cart total, at least. The comas are replaced by "", at least in this case. You may need to do more code audits to ensure "," is treated as decimal separator.
