### ISSUE TITLE
Form validator

### ISSUE THREAD

**Issue by theikid** [wojodesign/simplecart-js#71]
Hi there I got a second issue. I add a custom select into my form to choose shipping. I'd love to validate the select before adding the item to the cart but as the script isnt using a form I can't make it. Anyone would mind helping me?

Thank you !

**Comment by chekobil** [comment]
Hi, 
me.shipping = function(){
...
return shipping   }
this is where the shipping value is calculated every time the cart is modified,
here you can validate your new selection and return the new value ...

regards
Felipe
