### ISSUE TITLE
More than one Javascript and it doesn't work?

### ISSUE THREAD

**Issue by samxyouxwell** [wojodesign/simplecart-js#73]
I am trying to use the cart on a page that is also using another javascript, so it looks like this in my head tag:

```
<script type='text/javascript' src='../MagicLine/js/jquery.color-RGBa-patch.js'></script>
<script type='text/javascript' src='../MagicLine/js/example.js'></script>
<script type="text/javascript' src='../shop/simplecart.js'></script>
```

the problem is, if i have it that way, the cart simply doesn't work. my Add to Cart link doesn't work, nothing shows up in the cart, i get nothin.

but, if i delete the top two script lines

```
<script type='text/javascript' src='../MagicLine/js/jquery.color-RGBa-patch.js'></script>
<script type='text/javascript' src='../MagicLine/js/example.js'></script>
```

then it works just fine.

here's links to those two files:

http://samgordon.net/MagicLine/js/jquery.color-RGBa-patch.js
http://samgordon.net/MagicLine/js/example.js

and i havent changed anything in the simplecart.js file

any ideas would be much appreciated!
thank you.

**Comment by nolawill** [comment]
You may find this useful. I'm having similar problems and am trying to work it out myself. Let me know if you have any success with it. I'll do the same.

http://api.jquery.com/jQuery.noConflict/
http://stackoverflow.com/questions/690890/javascript-conflict-on-my-html-page
(This last one is about a different subject, but I still think it applies in principal.)

**Comment by wojodesign** [comment]
I would have to take a look at your scripts to see what the issue is.  Version 3 will have much improved compatibility and will not pollute the global space like v2.x, so most of these conflicts should be avoided

**Comment by wojodesign** [comment]
I tested loading your scripts with the version 2.2.dev and didn't have any issues.  Let me know if you continue to have problems.
