### ISSUE TITLE
item.childNodes is undefined (MooTools & Prototype Error)

### ISSUE THREAD

**Issue by webmatrix** [wojodesign/simplecart-js#74]
I am getting item.childNodes is undefined error while loading the page in firebug console.On clicking Add to  Cart. I get same error again and again.

Regards
Abhijit

**Comment by wojodesign** [comment]
This is an error when using MooTools or Prototype.  It is an open bug and is being worked on - thanks for the heads up.

**Comment by wojodesign** [comment]
working in 2.2.dev
