### ISSUE TITLE
Standard & Next Day Postage 

### ISSUE THREAD

**Issue by mrtom100** [wojodesign/simplecart-js#76]
Hello
    I am trying to get simplecart to have a drop down in the cart so once all items are added it defaults to standard postage but can opt in to next day that will then amend the postage price by adding money onto the current price depending on the quantity of items in the cart...

HELP i have not be able to do this any help to solve this

**Comment by fmforyou** [comment]
Hi,

I found this on here a few days ago. Hope it helps.

<SELECT name="number" style="width:100px; font-size: 10px;" class="inputBx" onchange="simpleCart.shippingFlatRate = this.options[selectedIndex].value; simpleCart.update();">
<OPTION selected value="2.95">4 - 5 business days UK (+ &pound;2.95)</OPTION>
<OPTION value="5.00"> 48 hr UK (+ &pound;5)</OPTION>
<OPTION value="6.00">Next Day UK (+ &pound;6)</OPTION>
</SELECT>
<br>

Probably best to remove my styling and class before use. It can be placed in with shopping cart or as an added "step" before checkout. My shopping cart display is small so when they click "Checkout" it shows a hidden div with the above shipping options and a real "Checkout" button!

EDIT: Just noticed the options box coding doesn't display! Here is the code you need to a select box to work with cart - onchange="simpleCart.shippingFlatRate = this.options[selectedIndex].value; simpleCart.update();"

**Comment by mrtom100** [comment]
That works great one thing as you seem like an expert at this, how can i show this either in Paypal or in the cart so I know what postage they have paid for without doing the maths to break down the postage per item to work out the extra they have paid...

**Comment by fmforyou** [comment]
Hi, you shouldn't need to do anything other than have simpleCart.shippingFlatRate enabled.

**Comment by mrtom100** [comment]
Its to add to the shipping so say you have 5 items to send one box signed
for be an extra $5 on top of the already set postage of $2 an item... so its
an extra for the postage really
On 25 Mar 2011 12:58, "fmforyou" <
reply@reply.github.com>
wrote:

**Comment by fmforyou** [comment]
Sorry! DISABLE simplecart.ShippingFlatRate in script that goes on main page. Just checked my coding :-0

**Comment by mrtom100** [comment]
Its to add to the shipping so say you have 5 items to send one box signed for be an extra $5 on top of the already set postage of $2 an item... so its an extra for the postage really
