### ISSUE TITLE
Email Checkout problems and answers

### ISSUE THREAD

**Issue by emvbase** [wojodesign/simplecart-js#78]
Hi. I've downloaded SimpleCart with the email checkout option (https://github.com/thewojogroup/simplecart-js/tree/email) configure index.html with my email and email.php with the same email. When I'm testing online and checkout i get a box SUCESS! but i don't receive any message with the order... This is the first problem.

The second problem is: Where or How I can put some customer fields for contact like name, phone, email address... Could anyone help me to solve this?

**Comment by makuc** [comment]
I have managed to get the second thing done. About the first thing I don't know yet, because I still did not upoad it to net to completly try it out.

Edit:
I will post link to download it soon ...

**Comment by dvdotsenko** [comment]
Contents of emailCheckout function:

```
me.emailCheckout = function() {
    return;
};
```

What this means is that there is no code there. You need to write it, i guess with something like:

**Comment by makuc** [comment]
well if you download simpleCart.js from email section, everything is in. But if you don't, this are the lines:

me.emailCheckout = function() {
        var div = me.updateCartView( document.createElement("div") );
        div = "<div class='simpleCart_items'>" + div.innerHTML + "</div>";
        $.post("email.php" , {div:div} , function(data) {
            alert( data );
        });
    };

Or link to full js:

https://github.com/thewojogroup/simplecart-js/blob/email/simpleCart.js
