### ISSUE TITLE
Currency, how to put another?

### ISSUE THREAD

**Issue by emvbase** [wojodesign/simplecart-js#79]
It's possible to ADD a currency, how can I proceed to do this?

**Comment by illya09** [comment]
I added Thai currency
,ThaiBaht=THB="THB",USDollar=USD="USD";

case THB:
                return  "&#3647;";

simpleCart.currency = THB;

**Comment by illya09** [comment]
above should return currency code not the Baht symbol

baht symbol is  &  #  3  6  4  7;  not as shown by the browsers interpretation ฿

without spaces

**Comment by wojodesign** [comment]
Thanks guys, we can always use suggestions for more languages and currencies.  I will add this currency into the core for 2.2
