### ISSUE TITLE
set item.price in simpleCart.js?

### ISSUE THREAD

**Issue by kellyrnh** [wojodesign/simplecart-js#81]
I am trying to figure out a way to give a discount depending on quantity. I would like to know if there is any way to set the price for the items (they are all the same price) so I can do a conditional statement to determine if the regular or bulk pricing applies? I have this working using javascript and a form on a page without SimpleCart, but when it goes to PayPal, if any of the items are 0 it gives an error.   

My (non SimpleCart) code:

function CalculateOrder(form) {
if (document.theForm.totalBooks.value < 20)
  {
   document.theForm.amount_1.value = "14.99";
   document.theForm.amount_2.value = "14.99";
   document.theForm.amount_3.value = "14.99";
   }
else
  {
  document.theForm.amount_1.value = "9.99";
  document.theForm.amount_2.value = "9.99";
  document.theForm.amount_3.value = "9.99";
  }
}

I would like to do something similar by setting:
 item.price = 14.99 
unless total cart quantity is 20+, then, 
item.price = 9.99

HELP starting to lose my mind...

**Comment by fmforyou** [comment]
Hi,

I have managed to add a 10% discount if someone buys 2 or more of the same product. Also 10%, 15% or 20% on whole cart (uses MySQL database) Gift Vouchers etc. I don't know if the code is perfect (self taught by trial and error) but it all works. I can send you it and you can have a look to see if you can use parts of it for your project? Let me know.

**Comment by kellyrnh** [comment]
Yes, that would be great. Mine it doesn't matter how many of a specific product, just as long as there is at least 20 items in the cart then either it gets a discount or the price is changed to the reduced price (either would work). I've been looking for a good solution to this for a long time, so you would be my hero if it worked! :)

**Comment by wojodesign** [comment]
This issue is the same as https://github.com/thewojogroup/simplecart-js/issues/52 - closing.

**Comment by misbach** [comment]
Here is a good link to the duplicate issue #52.

@wojodesign Both issues are closed and there doesn't seem to be a current slick way of implementing volume or bulk discounts per item. Can we re-open one of these issues, or create a new one?
