### ISSUE TITLE
Cookies shouldn't use the '=' character

### ISSUE THREAD

**Issue by mattbishop** [wojodesign/simplecart-js#82]
Right now the cart is stored in the cookie with the logical 'name=value||name=value' pattern. The problem with this is that Tomcat, and probably others, will incorrectly parse the cookie header so that the only thing assigned to the simpleCart cookie is the first 'name' object.  The rest is dropped.

Please change the '=' to something more server-friendly like '~'.

**Comment by wojodesign** [comment]
Thanks matt,  you are definitely correct.  I will change the delimiter in the next version

**Comment by wojodesign** [comment]
currently this parsing of the cookie is done by the same function as the add to cart parser.  this may require some more complicated fixes

**Comment by mattbishop** [comment]
Here's my fix. I'd do a patch, but I have made other changes too.

In createCookie(), last two lines:

  value = value.replace(/=/g, '~');
  document.cookie = name + "=" + value + expires + "; path=/";

and, towards the end of readCookie():

```
if (c.indexOf(nameEQ) === 0) {
  var value = c.substring(nameEQ.length, c.length);
  return value.replace(/~/g, '=');
}
```

**Comment by wojodesign** [comment]
ah nice, this is a great easy solution.  I added it into 2.2.dev
