### ISSUE TITLE
New input fields - name, address...

### ISSUE THREAD

**Issue by westsomething** [wojodesign/simplecart-js#84]
Hi,
I have managed to make the simplecart working with my cgi-form mail script on server - which i think is better solution.
But i'm really exhausted to make simplecart working not only as the cart but also as the submitting form - which is what i need.
I don't need Paypal or Google and other kind of checkouts - mostly just like instrument to choose the needed product - calculate its price and sending me this order with customer's contact inside it.
So the problem is obvious - missing input fields and how to process them.
I'm not really pro in java and i need help - how to make text input fields for example - Name:, Address: and Your email: - like from any form to be them processed by this script?
I can't find the way to processing and submitting of such input fields to my cgi-mail script - simplecart javascript not grabbing info from them.
Can anyone know the fastest way to make simplecart.js to grab info from such input fields and include written text from them inside submitted order?
Thanks for any answers.

**Comment by Andre-Agi** [comment]
It's quite easy.

open index.html
add this code where you want it:

<form id="formail" action="" method ="post" enctype="multipart/form-data">

                <label for="name">Name : </label>
                <input type="text" name="name" id="name" />

                <label>Adress : </label>
                <input type="text" name="adress" id="adress" />
            </form>


open email.php
find: $div = $_POST['div'];
below add:

$name = $_POST['name'];
$adress = $_POST['adress'];

find: " . $div . "
after add:

" . $name . " " . $adress . "

open simplecart.js
find:

```
me.emailCheckout = function() {
    var div = me.updateCartView( document.createElement("div") );
    div = "<div class='simpleCart_items'>" + div.innerHTML + "</div>";
    jQuery.post("/shop/email.php" , {div:div} , function(data) {
        alert( data );
    });
    eraseCookie('simpleCart');
};
```

replace with:

```
me.emailCheckout = function() {
    var div = me.updateCartView( document.createElement("diver") );
    diver = "<div class='simpleCart_items'>" + div.innerHTML + "</div>";

    var name = jQuery("#name").val();
    var adress = jQuery("#adress").val();

    var datastring = 'div=' + diver + '&name=' + name + '&adress=' + adress; 


    jQuery.ajax({
            type: "POST",
            url: "email.php",
            scriptCharset: "utf-8",
            contentType: "application/x-www-form-urlencoded; charset=UTF-8",
            data: datastring,
            success: function(data) {alert(data);}
        });
        eraseCookie('simpleCart');
};
```

there you go ;)

**Comment by ariebombarie** [comment]
Hi trickoff,

That works quite nice, that is, I get one additional line at the bottom of my e-mail. It now says:

undefined undefined

So, next thing is to get the client information in these fields.

Do I understand correctly that I need to add the line

Name : Adress : 

in the index.html file? I seem to miss the point here. Anyway, my issue remains how to gather the client information from the client (through a form?) in such a way that the information is passed to the script that is then displayed at the bottom line of the e-mail.

Thanks a lot in advance for helping me

**Comment by Andre-Agi** [comment]
Well somehow github changed the code that i posted for index.html
it should be like this:

```
            <form id="formail" action="" method ="post" enctype="multipart/form-data">

                <label for="name">Name : </label>
                <input type="text" name="name" id="name" />

                <label>Adress : </label>
                <input type="text" name="adress" id="adress" />
            </form>
```

**Comment by ariebombarie** [comment]
Hi Trickoff,

Thanks a lot for that. That was exactly the missing piece. It works fine for me now!
Many people will be happy with this solution. Great work.

Cheers

**Comment by westsomething** [comment]
Hm, i tried this method and found that using mailing through PHP with jquery unacceptable slow to operate - when someone click on checkout button the script need at least 7 second to just show the message that all info "was sent". In contrast the cgi-mail working just immediately - and it can be tuned additionaly to redirect consumer to other page instead of waiting for message. I think that i will abandon this method because so big waiting time is force me to write stupid warning messages like "do not click twice and wait for confirmation".
I will stay my way - all i have done to work it with cgi-mail - without using PHP and jQuery - copied the part of code from Google_checkout - this one:
this.emailCheckout = function () {
        var form = document.createElement("form"),
            counter = 1;
        form.style.display = "none";
        form.method = "POST";
        form.action = "/cgi-bin/your_cgi_script";
        form.acceptCharset = "utf-8";

```
    for( var current in this.items ){
        var item                = this.items[current];
        form.appendChild( this.createHiddenElement( "item_name_"        + counter, item.name        ) );
        form.appendChild( this.createHiddenElement( "item_quantity_"    + counter, item.quantity    ) );
        form.appendChild( this.createHiddenElement( "item_price_"       + counter, item.price       ) );
        form.appendChild( this.createHiddenElement( "item_currency_" , this.currency    ) );
        form.appendChild( this.createHiddenElement( "adress"    + counter, this.adress  ) );
        form.appendChild( this.createHiddenElement( "_charset_"                  , ""               ) );
        form.appendChild( this.createHiddenElement( "recipient" , "your_email_address"      ) );

        var descriptionString = "";

        for( var field in item){
            if( typeof( item[field] ) != "function" && 
                                field != "id"       && 
                                field != "quantity" && 
                                field != "price" )
            {
                    descriptionString = descriptionString + ", " + field + ": " + item[field];              
            }
        }
        descriptionString = descriptionString.substring( 1 );
        form.appendChild( this.createHiddenElement( "item_description_" + counter, descriptionString) );
    }

    document.body.appendChild( form );
    form.submit();
    document.body.removeChild( form );
};
```

It's working, the result is little messy - but it's cosmetic, for resolve later. I found that this part of code - exactly grabs the info from the cart.
The only problem i have here is with the input fields i wanna use, for example:
form.appendChild( this.createHiddenElement( "adress"    + counter, this.adress  ) );
in result page it shows me - "adress: undefined, undefined" - instead of undefined i need to have the customer info...

**Comment by westsomething** [comment]
At last, i found it - what grabs and how to manage it - only by using the method of comparing and not knowing anything in Javascript.
The cgi-script works really faster than jquery - so i will stay with it. Also i found some good coding for the input text fields - like description inside which disappears but help the client to find the field and tell him what to write there.
Case closed and many decorative work after...
Need to be like this:

or( var current in this.items ){
        var item                = this.items[current];
        form.appendChild( this.createHiddenElement( "item_name_"        + counter, item.name        ) );
        form.appendChild( this.createHiddenElement( "item_quantity_"    + counter, item.quantity    ) );
        form.appendChild( this.createHiddenElement( "item_price_"       + counter, item.price       ) );
        form.appendChild( this.createHiddenElement( "item_currency_" , this.currency    ) );
        form.appendChild( this.createHiddenElement( "_charset_"                  , ""               ) );
        form.appendChild( this.createHiddenElement( "recipient" , "your_email_address"      ) );

```
   var adressinfo = document.getElementById('adress').value;
        form.appendChild( this.createHiddenElement( "adress_" , adressinfo) );

    var descriptionString = "";

    for( var field in item){
        if( typeof( item[field] ) != "function" && 
                            field != "id"       && 
                            field != "quantity" && 
                            field != "price" )
        {
                descriptionString = descriptionString + ", " + field + ": " + item[field];              
        }
    }
    descriptionString = descriptionString.substring( 1 );
    form.appendChild( this.createHiddenElement( "item_description_" + counter, descriptionString) );
}

document.body.appendChild( form );
form.submit();
document.body.removeChild( form );
```

};

The input fields on the HTML page can be like trickoff proposed.

For example this is what this gets me in cgi-mail script by this code (i think it is very important to not include images of products in your submitted message - because this requires many additional space which used ineffectively):

Thank You For Filling Out This Form
Below is what you submitted to *****\* on Saturday, May 14, 2011 at 16:21:41

item_name_1: Sample CD 3

item_quantity_1: 1

item_price_1: 13.49

item_currency_: USD

_charset_: UTF-8

adress_: test - test 34535345

item_description_1: image: ********/attack-release.png, name: Sample CD 3, description: A class of simpleCart_checkout will send you off to Paypal or Google Checkout , thumb: images/attack-release_tn.png

**Comment by westsomething** [comment]
Hi,
Anyone know how to make variable get value from the input field only once?

This is really annoying now when address info multiplies many times as the items in the cart - in simple if i choose two different items - the address info in result i have also two:
Below is the result of your feedback form.  It was submitted by
() on Wednesday, May 25, 2011 at 10:52:26
item_name_1: Sample CD, Sample CD 2, Sample CD 3

item_quantity_1: 1, 1, 1

item_price_1: 8.99, 8.97, 13.49

item_currency_: USD, USD, USD

Name:: ddgdsgdsg, ddgdsgdsg, ddgdsgdsg

## Address:: 23532525, 23532525, 23532525

Yeah jQuery smooth this all automatically but i chose the hardest way and want to resolve it.
Is it possible to make DOM methods (getElementById or appendChild) take value only ONCE - not as many times as value inserted now?

**Comment by antonyf** [comment]
URGENT!! does any body have a function for this, THat doesnt include JQUERY!.. Its conflicting with everything on my site when i include it..
just a nice simple ajax or javascript function..

**Comment by Andre-Agi** [comment]
Just use a jQuery no conflict http://api.jquery.com/jQuery.noConflict/

**Comment by antonyf** [comment]
Thanks trickoff for the reply.
I did look into the no conflict.. My consists of components and modules and at different times calls different javascript and jquery scripts, i wouldn't know where to put the 
 $.noConflict();
  jQuery(document).ready(function($) {

Javascript or a Prototype script is the only way for me to go..

I used the example you posted in the forum with the name and address to get the form setup..
regards
Antony

**Comment by antonyf** [comment]
As you can see its 03:19 am here by me and im still on this problem. 
this is the form setup example of yours i used:
https://github.com/wojodesign/simplecart-js/issues/84#issuecomment-3056269
i use the email.php form setup as you did here. i also added more fields for information from the site user. but even in its default, when i click the checkout, it does nothing... My site does load the jquery-1.4.3.min.js maybe the example just needs a tweak to work with the upgrade jquery version...
I don't know.
Im looking at all examples on the net now.. 
I can get forms and working but i cant get the classes added to the forms..
Any-way if you can help that's awesome.
regards
Antony

**Comment by antonyf** [comment]
Ok heres what i have noticed. Weather i include the jquery 1.3 or 1.4. the email function works on the email version of the simpleCart script... on its own without loading my pages.. I copied all relevent code to 2.2 but when i hit the checkout nothing happens...
what was changed in the email version of the script to make it have the email checkout as an option?
i must be missing something??
can you put the steps here: just for the email checkoout and only what was changed

**Comment by antonyf** [comment]
Please can some one do a prototype version of the jquery above for the post email..
