### ISSUE TITLE
Donation link not clearly formatted

### ISSUE THREAD

**Issue by dmethvin** [wojodesign/simplecart-js#85]
On the home page of simplecartjs.com, the donation text box isn't clearly formatted (light gray box on a slightly darker gray background). If an inattentive user clicks the Donate button without entering a value, Paypal gives an unhelpful message "The link you have used to enter the PayPal system contains an incorrectly formatted item amount."  

http://gyazo.com/619960af10f463da9111cdfe0b6c6e95.png

Suggested fixes include a lighter background color for the text box, a fieldset group border around both the button and the text box, and/or prefilled amount in the box.

Signed, inattentive user.

**Comment by wojodesign** [comment]
Thanks! I put in a default amount..
