### ISSUE TITLE
PayPal error on IE6: Your last action could not be completed

### ISSUE THREAD

**Issue by j-greig** [wojodesign/simplecart-js#92]
Hi all,

When I checkout on IE6, I get this error message from PayPal:

"sorry your last action could not be completed"

I get this problem on the main simpleCart demo... has anyone else experienced this?

(PS. I changed the paypal checkout method to use hidden forms, in case the string was too long for IE6, but still get the same error... see http://clients.avdisco.net/camillameijer/sample_orders.html for my test)

**Comment by wojodesign** [comment]
3stripe, Unfortunately IE6 is not actively supported.  Have you experienced a similar issue in any other browsers?
