### ISSUE TITLE
What is the default cookie duration

### ISSUE THREAD

**Issue by bizking** [wojodesign/simplecart-js#93]
What is the default cookie duration?

How can I modify this to (for example) erase itself after a set period?

I have some problems with this because I cannot find where to set the cookie duration (in easy to understand formats please, I am fighting my way back from a stroke).

Cheers
Biz

**Comment by wojodesign** [comment]
the default is 30 right now.  I added an option to change this in the 2.2.dev branch by adding this to your config code:

me.cookieDuration = 30;  // duration in days
