### ISSUE TITLE
How to translate in other language ?

### ISSUE THREAD

**Issue by Nicolas-37000** [wojodesign/simplecart-js#95]
hello

when i use the class "simpleCart_items", i would to translate  
Name,
Price,
Quantity,
Total,
in French. How can i do this ?

Thank you

**Comment by westsomething** [comment]
i think only manually, every word.

**Comment by wojodesign** [comment]
I am trying to think of a better way of doing this, I will work it into 2.2

**Comment by wojodesign** [comment]
Hey guys, I have added some simple translation support into the 2.2.dev branch.  Currently there are no other translations than english, so you have to add yours before using it.  If you provide me with a translation here, I can add it into the core.

To add a translation, put this code (except with your language and translations in quotes) in your config code: 

```
    simpleCart.ln[ "Your Language Code" ] = {

          quantity: "Quantity"
        , price: "Price"
        , total: "Total"
        , decrement: "Decrement"
        , increment: "Increment"
        , remove: "Remove"
        , tax: "Tax"
        , shipping: "Shipping"
        , image: "Image"
};

me.language = "Your Language Code"; 
```

**Comment by Nicolas-37000** [comment]
Great thank you for the help i'll gonna test this code.

**Comment by Mediabahn** [comment]
Here's a french or CAD translation !

Qté or Quantité

simpleCart.ln[ "CAD" ] = {

```
      quantity: "Qté"
    , price: "Prix"
    , total: "Total"
    , decrement: "-"
    , increment: "+"
    , remove: "Enlever"
    , tax: "Taxes"
    , shipping: "Transport"
    , image: "Image"
```

};

me.language = "CAD"; 

Where exactly do we put this code in the page that receive the cart or in the simplecart.js ????

TIA

PS: super script ;-))
