### ISSUE TITLE
Paypal Checkout shows Options and has Thumb URL (How can i remove that)

### ISSUE THREAD

**Issue by ragtech** [wojodesign/simplecart-js#96]
Not sure that serves any purpose and it seems that it would be confusing to the customer/buyer. Can anyone tell me the reason behind this or how to removed the image URL?

Thanks in advance
Regards
!ragtech

**Comment by wojodesign** [comment]
This is an issue where anything in the cart is sent to the checkout.  There will be an option to select what to send in future versions, but for now, it would have to be done by modifying the checkout.

**Comment by ragtech** [comment]
Gracias my friend...

And thanks for the reply and really nice script... any chance of getting it to use mySql instead of the cookie thing? It's such a nice easy Cart but by using cookies; you are limited to how many items you can put in the cart. You have to keep in mind there is a 4K limit and about 20-30 items and you're out of luck.

Really Nice though... I wish I knew enough about js to help but my area is xhtml and css (some PhP)
ragtech

**Comment by wojodesign** [comment]
one solution i may do is to use my simpleStorage script.  This uses the html5 local storage if its available, otherwise uses cookies that avoid the limit by appending multiple cookies if needed.  

Version 3 should have some features for tying in your own storage solutions, so hopefully there will be a way to communicate with a server side layer and store in SQL then.

**Comment by ragtech** [comment]
Me again... Just made two donations ($10.00ea) to support your efforts...

Also would like to contribute something else... it isn't much but, perhaps some could make use of it...  It's a simple 'Add State Tax Check Box' specifically it adds the sales tax by checking a simple check-box... remove the check and it removes the sales tax...  it pretty much my limits when it comes to js...

The Example can be found here...(it's self contained so I can zip it up and send to you... if you would like ---I'm not quite sure how long I can leave it up in that location)

http://friendlyfumes.com/new/tax_example/tax_example.html

Thanks Again for a great script! A little bit more security and store in SQL and it would be the perfect setup...

...BTW; what's the ETA on Version 3

Regards,
ragtech

**Comment by ragtech** [comment]
duh...

put it here permanently... (Not sure why I didn't in the first place)

http://uswebsitecreation.com/tax_example/tax_example.html

Regards,
ragtech

**Comment by wojodesign** [comment]
thanks for the donations and the script! I will see if I can work it into the code base, or at least the documentation.  

my main concern for now is cleaning up the errors in v2 and adding some simple features, hopefully that will be done in the next week or so.  

I am very much looking forward to improving the overall code in v3, and introducing new features that will allow for more customization.  I will hopefully get started on it as soon as next week, but it may be a couple months or more before a stable release is ready.

**Comment by mattbishop** [comment]
It should be pretty easy to omit the _image_ properties from going to paypal. Please don't remove the options send because I use those to communicate things like color.
