### ISSUE TITLE
IE 8 Error with attributes passing to cart

### ISSUE THREAD

**Issue by robertcedwards** [wojodesign/simplecart-js#99]
I have a select dropdown menu to have the customer select a store to ship to.
In IE8 all of the options are passed to the checkout instead of just one.
Any suggestions?

**Comment by fmforyou** [comment]
HI,
Can you post your select coding? I have select boxes an have no issues.

**Comment by martincf** [comment]
Hi... I've the same issue. All options for an item (for example, sizes) are being passed to the basket. So, an item which should have one size selected from a select's option element, seems to be passing all the options (100cm, 110cm, 120cm). 

And when viewing the items summary in Paypal... the HTML for the options seems to be passed through as well (so stating <OPTION>100cm</OPTION><OPTION>110cm</OPTION>, and so on (uppercase not my doing!)

Here's an example of the select code:

```
            <ul>
                <li class="simpleCart_shelfItem">Size:
                    <span class="item_name">Kamae Standard Gi</span>
                    <select class="item_size">
                        <option>100cm</option>
                        <option>110cm</option>
                        <option>120cm</option>
                        <option>130cm</option>
                    </select>
                    <em class="item_price">&pound;19.50</em>
                    <a class="item_add" href="javascript:;"><img src="img/button_add.png" alt="Add to shopping basket" /></a>
                </li>
```

**Comment by martincf** [comment]
Try adding 'value' attribute to the option element.
